import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
 title:'Career Training, WIOA & Apprenticeship Opportunities in Gary, Indiana | Elevate for Humanity',
 description:'Explore career training, workforce development, employer partnerships, WIOA pathways and Registered Apprenticeship opportunities serving Gary and Northwest Indiana.',
 keywords:['Gary Indiana career training','Gary Indiana apprenticeship','Northwest Indiana workforce training','WIOA Gary Indiana','WorkOne Gary Indiana','registered apprenticeship Gary','job training Gary Indiana','Lake County Indiana career training'],
 alternates:{canonical:'https://www.elevateforhumanity.org/gary-indiana'},
 robots:{index:true,follow:true},
};
export default function GaryPage(){const ld={'@context':'https://schema.org','@type':'Service',name:'Gary and Northwest Indiana workforce training and apprenticeship support',provider:{'@type':'Organization',name:'Elevate for Humanity'},areaServed:[{'@type':'City',name:'Gary'},{'@type':'AdministrativeArea',name:'Northwest Indiana'}],serviceType:'Career training, workforce development and Registered Apprenticeship coordination'};return <main className="bg-white text-slate-950"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(ld)}}/><section className="px-4 py-20 sm:py-28"><div className="mx-auto max-w-6xl"><p className="text-sm font-black uppercase tracking-[.16em] text-blue-800">Gary & Northwest Indiana</p><h1 className="mt-4 max-w-5xl text-4xl font-black tracking-tight sm:text-6xl">Career training and apprenticeship pathways for Gary and Northwest Indiana.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-700">Elevate connects eligible residents with career-training pathways, employers, apprenticeship opportunities, and workforce resources. Funding and program eligibility depend on the individual, program, employer, and applicable workforce authorization.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/apply" className="rounded-xl bg-blue-800 px-6 py-3 font-black text-white">Apply for Training</Link><Link href="/partners/host-shops" className="rounded-xl border-2 border-slate-950 px-6 py-3 font-black">Find Apprenticeship Opportunities</Link><Link href="/apply/employer" className="rounded-xl border-2 border-slate-300 px-6 py-3 font-black">Employers: Partner With Us</Link></div></div></section><section className="border-y border-slate-200 px-4 py-14"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-3"><Card t="Job seekers" d="Explore training, credentials, apprenticeship and employment pathways serving Northwest Indiana."/><Card t="Employers" d="Discuss OJT, apprenticeship, candidate pipelines and workforce partnership opportunities."/><Card t="Workforce partners" d="Coordinate participant referrals, training authorization, employer development and documented outcomes."/></div></section></main>}
function Card({t,d}:{t:string;d:string}){return <article className="rounded-2xl border border-slate-200 p-6"><h2 className="text-xl font-black">{t}</h2><p className="mt-3 leading-7 text-slate-700">{d}</p></article>}