// pre-auth-registry: exempt - Dev Studio auth gates deployment ledger access.
import { NextRequest,NextResponse } from 'next/server';
import { apiRequireDevStudio } from '@/lib/devstudio/api-auth';
import { requireAdminClient } from '@/lib/supabase/admin';
import { safeError } from '@/lib/api/safe-error';
import { requireTypedConfirmation } from '@/lib/security/require-confirmation';
import { getGoogleServices,getGoogleService } from '@/lib/google/runtime';
export const dynamic='force-dynamic';
export async function GET(req:NextRequest){const auth=await apiRequireDevStudio(req);if(auth.error)return auth.error;const db=await requireAdminClient();const {data,error}=await db.from('ai_deployments').select('*').order('started_at',{ascending:false}).limit(20);if(error)return safeError('Failed to fetch Dev Studio builds',500);const health=await Promise.all(getGoogleServices().map(async s=>{try{return (await getGoogleService(s)).healthy}catch{return false}}));return NextResponse.json({builds:data,provider:'google-cloud',googleConfigured:health.every(Boolean)});}
export async function POST(req:NextRequest){const auth=await apiRequireDevStudio(req);if(auth.error)return auth.error;const body=await req.json().catch(()=>({}));const confirmation=requireTypedConfirmation(body.confirmation,'deploy_autopilot');if(!confirmation.ok)return NextResponse.json({error:'Production deployment requires typed confirmation.',requiredConfirmation:confirmation.required},{status:409});const db=await requireAdminClient();const requested=body.service??'admin';const services=requested==='all'?getGoogleServices():getGoogleServices().filter(s=>s.key===requested||s.id===requested);if(!services.length)return safeError(`Unknown Google service: ${requested}`,400);const {data,error}=await db.from('ai_deployments').insert({service:requested,environment:body.environment??'production',status:'verifying',commit_sha:body.commit_sha??null,triggered_by:auth.id}).select().single();if(error)return safeError('Failed to create Dev Studio deployment record',500);const checks=await Promise.all(services.map(async s=>({service:s.id,health:await getGoogleService(s)})));const healthy=checks.every(x=>x.health.healthy);await db.from('ai_deployments').update({status:healthy?'deployed':'failed'}).eq('id',data.id);await db.from('dev_audit_logs').insert({user_id:auth.id,action:'google_deployment_verified',resource_type:'ai_deployment',resource_id:data.id,metadata:{services:services.map(s=>s.id),healthy}});return NextResponse.json({build:{...data,status:healthy?'deployed':'failed'},provider:'google-cloud',services:checks},{status:healthy?201:503});}