# Dockerfile.assets
# Lightweight Static Server for images/videos
FROM node:22-bookworm-slim

RUN npm install -g serve
WORKDIR /app
COPY public ./public

# Assets only need to serve the public folder
EXPOSE 8080
CMD ["serve", "-s", "public", "-l", "8080"]
