'use client';
import{useEffect,useState}from'react';
type Provider='paypal'|'branch';type Status={provider:Provider|null;destination:string|null;transfersEnabled:boolean;payoutsEnabled:boolean;providerConfigured:boolean;verificationStatus:string;onboardingReady:boolean;missingRequirements:string[]};
const initial:Status={provider:null,destination:null,transfersEnabled:false,payoutsEnabled:false,providerConfigured:false,verificationStatus:'not_started',onboardingReady:false,missingRequirements:[]};
export function PayoutAccessPanel(){const[s,setS]=useState(initial),[provider,setProvider]=useState<Provider>('paypal'),[email,setEmail]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState('');
const load=()=>fetch('/api/program-holder/payouts').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setS(d);if(d.provider)setProvider(d.provider)}).catch(e=>setError(e.message)).finally(()=>setBusy(false));
useEffect(()=>{void load()},[]);
async function act(action:'configure'|'onboard'|'dashboard'){setBusy(true);setError('');try{const r=await fetch('/api/program-holder/payouts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,provider,paypalEmail:email})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to continue.');if(d.url)location.assign(d.url);else{setS(x=>({...x,...d}));setBusy(false)}}catch(e){setError(e instanceof Error?e.message:'Unable to continue.');setBusy(false)}}
const ready=s.onboardingReady&&s.transfersEnabled&&s.payoutsEnabled&&s.providerConfigured;
return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.16em] text-blue-700">Secure contractor payouts</p><h2 className="mt-2 text-2xl font-black">{ready?'Funds access is ready':'Connect a payout provider'}</h2><p className="mt-2 text-sm text-slate-600">PayPal/Hyperwallet or Branch securely holds banking and card information. Elevate never stores full account numbers.</p>
<div className="mt-5 flex gap-3"><button className={`rounded-xl border px-4 py-3 font-bold ${provider==='paypal'?'border-blue-700 bg-blue-50':''}`} onClick={()=>setProvider('paypal')}>PayPal / Hyperwallet</button><button className={`rounded-xl border px-4 py-3 font-bold ${provider==='branch'?'border-blue-700 bg-blue-50':''}`} onClick={()=>setProvider('branch')}>Branch</button></div>
{provider==='paypal'?<input className="mt-4 w-full rounded-xl border p-3" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="PayPal email address"/>:<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm">Branch access becomes available after Elevate's partner account is activated.</p>}
{s.destination?<p className="mt-3 text-sm">Connected destination: {s.destination}</p>:null}{error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-800">{error}</p>:null}
<div className="mt-5 flex gap-3"><button disabled={busy} onClick={()=>act('configure')} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?'Checking…':'Save payout method'}</button>{s.provider?<button disabled={busy} onClick={()=>act(ready?'dashboard':'onboard')} className="rounded-xl border px-5 py-3 font-bold">{ready?'Access funds':'Continue provider setup'}</button>:null}</div></section>}
