'use client';
import { FormEvent, useEffect, useState } from 'react';

export function ProgramHolderOfficeTools({mode}:{mode:'meetings'|'mail'}){
 const endpoint=mode==='meetings'?'/api/program-holder/meetings':'/api/program-holder/office-mail';
 const[data,setData]=useState<any>({meetings:[],messages:[],applicants:[],recipients:[]});
 const[status,setStatus]=useState('');
 async function load(){const r=await fetch(endpoint,{cache:'no-store'});setData(await r.json())}
 useEffect(()=>{void load()},[endpoint]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('Saving…');const f=new FormData(e.currentTarget);const body=mode==='meetings'?{programHolderStudentId:f.get('student'),startsAt:f.get('startsAt'),meetingMethod:f.get('method'),durationMinutes:30,meetingUrl:f.get('meetingUrl'),location:f.get('location'),agenda:f.get('agenda')}:{recipientId:f.get('recipient'),subject:f.get('subject'),message:f.get('message')};const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await r.json();setStatus(r.ok?(mode==='meetings'?'Meeting scheduled.':'Office message sent.'):result.error||'Unable to save.');if(r.ok){e.currentTarget.reset();await load()}}
 if(mode==='meetings')return <main className="mx-auto max-w-5xl space-y-6 p-4 sm:p-8"><header><p className="text-xs font-black uppercase tracking-widest text-blue-700">Calendar</p><h1 className="text-3xl font-black">Applicant meetings</h1><p className="mt-2 text-slate-600">Schedule phone, video, or in-person enrollment meetings and keep the agenda with the applicant record.</p></header><form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-2"><select name="student" required className="min-h-11 rounded-xl border px-3"><option value="">Choose applicant</option>{data.applicants?.map((x:any)=><option key={x.id} value={x.id}>{x.applicant_name}</option>)}</select><input name="startsAt" type="datetime-local" required className="min-h-11 rounded-xl border px-3"/><select name="method" required className="min-h-11 rounded-xl border px-3"><option value="phone">Phone</option><option value="video">Video</option><option value="in_person">In person</option></select><input name="meetingUrl" placeholder="Video meeting link (optional)" className="min-h-11 rounded-xl border px-3"/><input name="location" placeholder="Location (optional)" className="min-h-11 rounded-xl border px-3 sm:col-span-2"/><textarea name="agenda" placeholder="Meeting agenda and preparation notes" className="rounded-xl border p-3 sm:col-span-2"/><button className="min-h-11 rounded-xl bg-blue-700 px-4 font-black text-white">Schedule meeting</button><p role="status" className="self-center text-sm font-bold">{status}</p></form><section className="grid gap-3">{data.meetings?.map((x:any)=><article key={x.id} className="rounded-xl border bg-white p-4"><p className="font-black">{x.title}</p><p className="text-sm text-slate-600">{new Date(x.starts_at).toLocaleString()} · {x.meeting_method.replace('_',' ')}</p>{x.agenda?<p className="mt-2 text-sm">{x.agenda}</p>:null}</article>)}</section></main>;
 return <main className="mx-auto max-w-5xl space-y-6 p-4 sm:p-8"><header><p className="text-xs font-black uppercase tracking-widest text-blue-700">Private workspace</p><h1 className="text-3xl font-black">Inter-office mail</h1><p className="mt-2 text-slate-600">Send private, auditable messages to Elevate staff and administrators.</p></header><form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm"><select name="recipient" required className="min-h-11 rounded-xl border px-3"><option value="">Choose recipient</option>{data.recipients?.map((x:any)=><option key={x.id} value={x.id}>{x.full_name||x.role} · {x.role}</option>)}</select><input name="subject" required maxLength={180} placeholder="Subject" className="min-h-11 rounded-xl border px-3"/><textarea name="message" required maxLength={5000} rows={6} placeholder="Write your message" className="rounded-xl border p-3"/><button className="min-h-11 rounded-xl bg-blue-700 px-4 font-black text-white">Send office message</button><p role="status" className="text-sm font-bold">{status}</p></form><section className="grid gap-3">{data.messages?.map((x:any)=><article key={x.id} className="rounded-xl border bg-white p-4"><p className="font-black">{x.subject}</p><p className="mt-1 whitespace-pre-wrap text-sm">{x.body}</p><p className="mt-2 text-xs text-slate-500">{new Date(x.created_at).toLocaleString()}</p></article>)}</section></main>
}
