/**
 * heroBanners - type definitions and runtime loader.
 *
 * Data lives in public/data/hero-banners.json (generated by scripts/export-hero-banners.ts).
 * Runtime normalization protects public pages from stale generated banner copy.
 */

import { loadJsonOnce } from '@/lib/data/json-cache';
import { RAPIDS_CONFIG } from '@/lib/compliance/rapids-config';

export interface HeroBannerCta {
  label: string;
  href: string;
  variant?: 'primary' | 'secondary';
}

export interface HeroBannerConfig {
  pageKey: string;
  videoSrcDesktop?: string;
  videoSrcMobile?: string;
  posterImage?: string;
  voiceoverSrc?: string;
  microLabel?: string;
  belowHeroHeadline: string;
  belowHeroSubheadline: string;
  primaryCta: HeroBannerCta;
  secondaryCta?: HeroBannerCta;
  trustIndicators?: string[];
  transcript?: string;
  analyticsName: string;
}

type RawHeroBannerConfig = Partial<HeroBannerConfig> & {
  headline?: string;
  subheadline?: string;
  ctaPrimary?: HeroBannerCta;
  ctaSecondary?: HeroBannerCta;
};

export type ProgramHeroBannerConfig = HeroBannerConfig & {
  microLabel: string;
  credentialLabel: string;
  durationLabel: string;
  secondaryCta: HeroBannerCta;
  trustIndicators: string[];
  transcript: string;
} & (
    | { salaryExempt?: false; salaryRangeLabel: string }
    | { salaryExempt: true; salaryNote: string; salaryRangeLabel?: string }
  );

let normalizedData: Record<string, HeroBannerConfig> | null = null;

function normalizeBanner(key: string, banner: RawHeroBannerConfig): HeroBannerConfig {
  const primaryCta = banner.primaryCta ?? banner.ctaPrimary ?? {
    label: 'View Programs',
    href: '/programs',
  };
  const secondaryCta = banner.secondaryCta ?? banner.ctaSecondary;

  const normalized: HeroBannerConfig = {
    ...banner,
    pageKey: banner.pageKey ?? key,
    belowHeroHeadline: banner.belowHeroHeadline ?? banner.headline ?? '',
    belowHeroSubheadline: banner.belowHeroSubheadline ?? banner.subheadline ?? '',
    primaryCta,
    secondaryCta,
    analyticsName: banner.analyticsName ?? key,
    ...(banner.videoSrcDesktop ? { videoSrcMobile: banner.videoSrcDesktop } : {}),
  };

  if (key === 'barber-apprenticeship') {
    const barber = RAPIDS_CONFIG.programs.barber;
    return {
      ...normalized,
      microLabel: 'DOL Registered Apprenticeship',
      belowHeroHeadline: 'Earn your Indiana Barber License through registered apprenticeship.',
      belowHeroSubheadline: `Complete ${barber.totalHours.toLocaleString('en-US')} hours of supervised on-the-job learning plus ${barber.relatedInstructionHours} hours of Related Technical Instruction under the registered program standards.`,
      primaryCta: {
        label: 'Enroll Now',
        href: '/programs/barber-apprenticeship/apply',
      },
      secondaryCta: {
        label: 'Request Information',
        href: '/programs/barber-apprenticeship/request-info',
        variant: 'secondary',
      },
      transcript: `The Barber Apprenticeship combines ${barber.totalHours.toLocaleString('en-US')} hours of supervised on-the-job learning with ${barber.relatedInstructionHours} hours of Related Technical Instruction. Apprentices complete documented workplace training, coursework, progress reviews, and licensing preparation through the registered program.`,
    };
  }

  return normalized;
}

function getData(): Record<string, HeroBannerConfig> {
  if (normalizedData) return normalizedData;

  const raw = loadJsonOnce<Record<string, RawHeroBannerConfig>>('hero-banners.json');
  normalizedData = Object.fromEntries(
    Object.entries(raw).map(([key, banner]) => [key, normalizeBanner(key, banner)]),
  );

  return normalizedData;
}

const heroBanners: Record<string, HeroBannerConfig> = new Proxy(
  {} as Record<string, HeroBannerConfig>,
  {
    get(_t, key: string) {
      return getData()[key];
    },
    ownKeys() {
      return Object.keys(getData());
    },
    has(_t, key: string) {
      return key in getData();
    },
    getOwnPropertyDescriptor(_t, key: string) {
      const d = getData();
      if (key in d) return { configurable: true, enumerable: true, value: d[key] };
      return undefined;
    },
  },
);

export default heroBanners;

export const internalProgramHeroBanners: Record<string, ProgramHeroBannerConfig> = new Proxy(
  {} as Record<string, ProgramHeroBannerConfig>,
  {
    get(_t, key: string) {
      const e = getData()[key] as any;
      return e?.credentialLabel ? e : undefined;
    },
    ownKeys() {
      return Object.keys(getData()).filter((k) => (getData()[k] as any)?.credentialLabel);
    },
    has(_t, key: string) {
      const e = getData()[key] as any;
      return !!e?.credentialLabel;
    },
    getOwnPropertyDescriptor(_t, key: string) {
      const e = getData()[key] as any;
      if (e?.credentialLabel) return { configurable: true, enumerable: true, value: e };
      return undefined;
    },
  },
);
