/**
 * heroBanners - type definitions and runtime loader.
 *
 * Data lives in public/data/hero-banners.json (generated by scripts/export-hero-banners.ts).
 * Runtime normalization protects public pages from stale generated banner copy
 * and prevents one generic media asset from appearing as unrelated page heroes.
 */

import { loadJsonOnce } from '@/lib/data/json-cache';
import { RAPIDS_CONFIG } from '@/lib/compliance/rapids-config';
import { PROGRAM_IMAGES, getProgramHeroImage } from '@/lib/images/programImages';

export interface HeroBannerCta {
  label: string;
  href: string;
  variant?: 'primary' | 'secondary';
}

export interface HeroBannerConfig {
  pageKey: string;
  videoSrcDesktop?: string;
  videoSrcMobile?: string;
  posterImage?: string;
  voiceoverSrc?: string;
  microLabel?: string;
  belowHeroHeadline: string;
  belowHeroSubheadline: string;
  primaryCta: HeroBannerCta;
  secondaryCta?: HeroBannerCta;
  trustIndicators?: string[];
  transcript?: string;
  analyticsName: string;
}

type RawHeroBannerConfig = Partial<HeroBannerConfig> & {
  headline?: string;
  subheadline?: string;
  ctaPrimary?: HeroBannerCta;
  ctaSecondary?: HeroBannerCta;
};

export type ProgramHeroBannerConfig = HeroBannerConfig & {
  microLabel: string;
  credentialLabel: string;
  durationLabel: string;
  secondaryCta: HeroBannerCta;
  trustIndicators: string[];
  transcript: string;
} & (
    | { salaryExempt?: false; salaryRangeLabel: string }
    | { salaryExempt: true; salaryNote: string; salaryRangeLabel?: string }
  );

const SHARED_GENERIC_VIDEO_FILES = [
  '/hero-home-fast.mp4',
  '/programs-overview-video-with-narration.mp4',
  '/hvac-hero-final.mp4',
  '/cna-hero.mp4',
  '/it-technology.mp4',
] as const;

const PAGE_PICTURE_OVERRIDES: Record<string, string> = {
  about: '/images/pages/about-hero.webp',
  platform: '/images/hero/admin-hero.webp',
  'funding-how-it-works': '/images/pages/about-funding-nav.webp',
  healthcare: '/images/pages/healthcare-hero.webp',
  programs: '/images/hero/hero-hands-on-training.webp',
  'building-services-technician': '/images/building-maintenance.webp',
  'federal-funded': '/images/heroes/hero-federal-funding.webp',
  'micro-programs': '/images/micro-classes-hero.webp',
  'skilled-trades': '/images/hero/hero-skilled-trades.webp',
  'home-health-aide': '/images/healthcare/hero-program-patient-care.webp',
};

function isSharedGenericVideo(value?: string): boolean {
  if (!value) return false;
  return SHARED_GENERIC_VIDEO_FILES.some((file) => value.endsWith(file));
}

function uniquePictureFor(key: string, banner: RawHeroBannerConfig): string | undefined {
  if (PROGRAM_IMAGES[key]) return getProgramHeroImage(key);
  return PAGE_PICTURE_OVERRIDES[key] ?? banner.posterImage;
}

function normalizeMedia(
  key: string,
  banner: RawHeroBannerConfig,
  normalized: HeroBannerConfig,
): HeroBannerConfig {
  const desktopShared = isSharedGenericVideo(banner.videoSrcDesktop);
  const mobileShared = isSharedGenericVideo(banner.videoSrcMobile);
  const picture = uniquePictureFor(key, banner);

  // If the desktop hero itself is one of the proven cross-page shared videos,
  // use a unique picture for this page/program instead of repeating the video.
  if (desktopShared && picture) {
    return {
      ...normalized,
      videoSrcDesktop: undefined,
      videoSrcMobile: undefined,
      posterImage: picture,
    };
  }

  // Keep a genuinely page-specific desktop video, but never substitute a
  // generic shared mobile video. Reuse this page's own desktop media on mobile.
  if (mobileShared && banner.videoSrcDesktop && !desktopShared) {
    return {
      ...normalized,
      videoSrcMobile: banner.videoSrcDesktop,
      posterImage: picture ?? normalized.posterImage,
    };
  }

  // Picture-only entries must always have an actual picture.
  if (!banner.videoSrcDesktop && !banner.videoSrcMobile && picture) {
    return { ...normalized, posterImage: picture };
  }

  return normalized;
}

let normalizedData: Record<string, HeroBannerConfig> | null = null;

function normalizeBanner(key: string, banner: RawHeroBannerConfig): HeroBannerConfig {
  const primaryCta = banner.primaryCta ?? banner.ctaPrimary ?? {
    label: 'View Programs',
    href: '/programs',
  };
  const secondaryCta = banner.secondaryCta ?? banner.ctaSecondary;

  let normalized: HeroBannerConfig = {
    ...banner,
    pageKey: banner.pageKey ?? key,
    belowHeroHeadline: banner.belowHeroHeadline ?? banner.headline ?? '',
    belowHeroSubheadline: banner.belowHeroSubheadline ?? banner.subheadline ?? '',
    primaryCta,
    secondaryCta,
    analyticsName: banner.analyticsName ?? key,
    ...(banner.videoSrcDesktop || banner.videoSrcMobile
      ? { videoSrcMobile: banner.videoSrcMobile ?? banner.videoSrcDesktop }
      : {}),
  };

  normalized = normalizeMedia(key, banner, normalized);

  if (key === 'barber-apprenticeship') {
    const barber = RAPIDS_CONFIG.programs.barber;
    return {
      ...normalized,
      microLabel: 'DOL Registered Apprenticeship',
      belowHeroHeadline: 'Earn your Indiana Barber License through registered apprenticeship.',
      belowHeroSubheadline: `Complete ${barber.totalHours.toLocaleString('en-US')} hours of supervised on-the-job learning plus ${barber.relatedInstructionHours} hours of Related Technical Instruction under the registered program standards.`,
      primaryCta: {
        label: 'Enroll Now',
        href: '/programs/barber-apprenticeship/apply',
      },
      secondaryCta: {
        label: 'Request Information',
        href: '/programs/barber-apprenticeship/request-info',
        variant: 'secondary',
      },
      transcript: `The Barber Apprenticeship combines ${barber.totalHours.toLocaleString('en-US')} hours of supervised on-the-job learning with ${barber.relatedInstructionHours} hours of Related Technical Instruction. Apprentices complete documented workplace training, coursework, progress reviews, and licensing preparation through the registered program.`,
    };
  }

  return normalized;
}

function getData(): Record<string, HeroBannerConfig> {
  if (normalizedData) return normalizedData;

  const raw = loadJsonOnce<Record<string, RawHeroBannerConfig>>('hero-banners.json');
  normalizedData = Object.fromEntries(
    Object.entries(raw).map(([key, banner]) => [key, normalizeBanner(key, banner)]),
  );

  return normalizedData;
}

const heroBanners: Record<string, HeroBannerConfig> = new Proxy(
  {} as Record<string, HeroBannerConfig>,
  {
    get(_t, key: string) {
      return getData()[key];
    },
    ownKeys() {
      return Object.keys(getData());
    },
    has(_t, key: string) {
      return key in getData();
    },
    getOwnPropertyDescriptor(_t, key: string) {
      const d = getData();
      if (key in d) return { configurable: true, enumerable: true, value: d[key] };
      return undefined;
    },
  },
);

export default heroBanners;

export const internalProgramHeroBanners: Record<string, ProgramHeroBannerConfig> = new Proxy(
  {} as Record<string, ProgramHeroBannerConfig>,
  {
    get(_t, key: string) {
      const e = getData()[key] as any;
      return e?.credentialLabel ? e : undefined;
    },
    ownKeys() {
      return Object.keys(getData()).filter((k) => (getData()[k] as any)?.credentialLabel);
    },
    has(_t, key: string) {
      const e = getData()[key] as any;
      return !!e?.credentialLabel;
    },
    getOwnPropertyDescriptor(_t, key: string) {
      const e = getData()[key] as any;
      if (e?.credentialLabel) return { configurable: true, enumerable: true, value: e };
      return undefined;
    },
  },
);