import 'server-only';
import { hydrateProcessEnv } from '@/lib/secrets';
type HolderContext={mode:'holder';user:{id:string;email?:string};holderId:string;db:any};
export type PayoutProvider='paypal'|'branch';
export type PayoutReadiness={provider:PayoutProvider|null;accountId:string|null;destination:string|null;transfersEnabled:boolean;payoutsEnabled:boolean;providerConfigured:boolean;verificationStatus:'not_started'|'pending'|'restricted'|'active'};
const masked=(v?:string|null)=>v?v.replace(/^(.{2}).*(@.*|.{2})$/,'$1••••$2'):null;
export async function payoutProviderConfigured(p:PayoutProvider){await hydrateProcessEnv();return p==='paypal'?Boolean(process.env.PAYPAL_CLIENT_ID&&process.env.PAYPAL_CLIENT_SECRET):Boolean(process.env.BRANCH_PARTNER_ID&&process.env.BRANCH_ONBOARDING_URL)}
export async function getProgramHolderPayoutAccount(ctx:HolderContext):Promise<PayoutReadiness>{const{data}=await ctx.db.from('program_holder_payouts').select('payout_provider,provider_recipient_id,transfers_enabled,payouts_enabled,verification_status').eq('user_id',ctx.user.id).maybeSingle();const provider=(data?.payout_provider||null)as PayoutProvider|null;return{provider,accountId:data?.provider_recipient_id||null,destination:masked(data?.provider_recipient_id),transfersEnabled:Boolean(data?.transfers_enabled),payoutsEnabled:Boolean(data?.payouts_enabled),providerConfigured:provider?await payoutProviderConfigured(provider):false,verificationStatus:data?.verification_status||'not_started'}}
export async function configureProgramHolderPayoutAccount(ctx:HolderContext,provider:PayoutProvider,paypalEmail?:string){if(provider==='paypal'&&!/^\S+@\S+\.\S+$/.test(paypalEmail||''))throw new Error('Enter a valid PayPal email address.');const recipient=provider==='paypal'?paypalEmail!.trim().toLowerCase():null;const active=provider==='paypal';const{error}=await ctx.db.from('program_holder_payouts').upsert({user_id:ctx.user.id,payout_provider:provider,provider_recipient_id:recipient,paypal_recipient_email:recipient,transfers_enabled:active,payouts_enabled:active,charges_enabled:false,instant_payouts_enabled:false,verification_status:active?'active':'pending',quickbooks_sync_status:'not_ready',updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw new Error('Unable to save the payout account.');await ctx.db.from('program_holders').update({payout_status:active?'active':'pending'}).eq('id',ctx.holderId);return getProgramHolderPayoutAccount(ctx)}
export async function payoutProviderUrl(provider:PayoutProvider,action:'onboard'|'dashboard'){await hydrateProcessEnv();if(provider==='paypal')return action==='dashboard'?process.env.HYPERWALLET_PAY_PORTAL_URL||'https://www.paypal.com/myaccount/money/':process.env.HYPERWALLET_ONBOARDING_URL||'https://www.paypal.com/myaccount/money/';return action==='dashboard'?process.env.BRANCH_DASHBOARD_URL:process.env.BRANCH_ONBOARDING_URL}
