import test from 'node:test';
import assert from 'node:assert/strict';
import {pcm16ToUlaw,wavToUlaw,makeTurnHandler} from './turn-adapter.mjs';
function wav(samples){const b=Buffer.alloc(44+samples.length*2);b.write('RIFF',0);b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(samples.length*2,40);samples.forEach((s,i)=>b.writeInt16LE(s,44+i*2));return b;}
test('8 kHz 16-bit PCM WAV becomes packet-aligned PCMU',()=>{const out=wavToUlaw(wav(Array(200).fill(0)));assert.equal(out.length,320);assert.equal(out[0],0xff);assert.equal(out[319],0xff);});
test('rejects audio outside strict mono 8k format',()=>{const bad=wav(Array(160).fill(0));bad.writeUInt32LE(16000,24);assert.throws(()=>wavToUlaw(bad),/FORMAT/);});
test('PCMU silence is encoded predictably',()=>assert.equal(pcm16ToUlaw(0),0xff));
test('auth failures do not invoke AI functions',async()=>{let called=false;const handler=makeTurnHandler({token:'x'.repeat(40),stt:async()=>{called=true;}});const res={writeHead(code){this.code=code;},end(body){this.body=body;}};await handler({method:'POST',url:'/internal/paris/turn',headers:{authorization:'Bearer wrong'},async *[Symbol.asyncIterator](){yield Buffer.alloc(0);}},res);assert.equal(res.code,401);assert.equal(called,false);});
test('valid audio uses real processor interfaces and produces spoken audio',async()=>{const calls=[];const handler=makeTurnHandler({token:'x'.repeat(40),stt:async()=>{calls.push('stt');return 'What programs?';},llm:async history=>{calls.push('llm');assert.equal(history[0].role,'user');return 'Ask admissions about current programs.';},tts:async()=>{calls.push('tts');return Buffer.alloc(160,0xff).toString('base64');}});const payload={sessionId:'a'.repeat(24),sequence:0,encoding:'PCMU',sampleRate:8000,audioBase64:Buffer.alloc(160,0xff).toString('base64')};const res={writeHead(code){this.code=code;},end(body){this.body=body;}};await handler({method:'POST',url:'/internal/paris/turn',headers:{authorization:'Bearer '+'x'.repeat(40)},async *[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify(payload));}},res);assert.equal(res.code,200);assert.deepEqual(calls,['stt','llm','tts']);assert.equal(JSON.parse(res.body).endCall,false);});
