import Link from 'next/link';
import { APPRENTICE_TIME_POLICY } from '@/lib/timeclock/policy';

const steps = [
  ['Programs & standards', '/host-shop/dashboard/programs', 'Open the assigned occupation and each apprentice’s syllabus. Review the registered term, required RTI, supervision, and completion criteria. Course length depends on that registered standard and demonstrated progress; do not promise the same completion date to every apprentice.'],
  ['Training schedule', '/host-shop/dashboard/schedule', 'Review the apprentice’s current theory course, completed lessons, and next lesson. Use the matching syllabus module for shop coaching, then keep the supervised schedule current.'],
  ['Apprentices', '/host-shop/dashboard/apprentices', 'Open the correct apprentice and confirm the active placement, supervisor, program, and contact details before recording anything.'],
  ['Attendance and work hours', '/host-shop/dashboard/hours/pending', 'Review actual supervised work each week. Approve accurate entries and return incorrect ones with a correction note. A geofence exception is evidence to investigate, not permission to approve work you did not supervise.'],
  ['Competency progress', '/host-shop/dashboard/competencies', 'Select the apprentice and the assigned registered competency. Observe the skill, record the evidence, and complete the electronic verification only after it is demonstrated. These records feed student progress; printing a checklist does not replace online verification.'],
  ['Wages and commission', '/host-shop/dashboard/wages', 'Read the displayed employer wage schedule and the apprentice’s current milestone. Record the actual effective date and hourly equivalent. Commission arrangements must meet the applicable registered wage floor and wage requirements; commission alone does not remove the employer’s wage obligations.'],
  ['Documents and agreements', '/host-shop/dashboard/documents', 'Open each missing requirement, upload the correct readable document, and wait for review. Replace expired evidence. Open your assigned MOU from Guides & Agreements and review the shop’s actual responsibilities.'],
  ['Reporting center', '/host-shop/dashboard/reports', 'Review attendance, RTI, OJL, wages, competency evidence, and exceptions before each reporting deadline. Resolve missing evidence with the apprentice and Administration.'],
] as const;

export function HostShopProgramGuide() {
  return <section className="my-6 rounded-3xl border border-fuchsia-200 bg-white p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-widest text-fuchsia-800">Your electronic program guide</p><h2 className="mt-2 text-2xl font-black">Run your apprenticeship, one step at a time</h2><p className="mt-3 text-sm leading-7">Weekly limits: {APPRENTICE_TIME_POLICY.weeklyOjlMaxHours} OJL hours, a {APPRENTICE_TIME_POLICY.weeklyTheoryTargetHours}-hour RTI target and {APPRENTICE_TIME_POLICY.weeklyTheoryMaxHours}-hour RTI maximum, and {APPRENTICE_TIME_POLICY.weeklyCombinedMaxHours} combined hours. OJL and RTI cannot overlap. The student supplies their personal tools and supplies.</p><details className="mt-4 rounded-2xl bg-cyan-50 p-4"><summary className="cursor-pointer font-black">How the geofence works</summary><p className="mt-3 text-sm leading-7">The timeclock uses the radius configured for the approved worksite. Students must allow location access and clock out before leaving. After {APPRENTICE_TIME_POLICY.outsideGeofenceGraceMinutes} continuous minutes outside the geofence, the system may clock them out. Review any shortened or disputed shift, confirm actual supervised times and evidence, and use the correction/approval workflow. Time after the system clock-out is not automatically credited.</p></details><div className="mt-4 grid gap-3 sm:grid-cols-2">{steps.map(([title,href,detail]) => <details key={href} className="rounded-2xl border border-slate-200 p-4"><summary className="cursor-pointer font-black text-slate-950">{title}: what to do</summary><p className="mt-3 text-sm leading-7 text-slate-700">{detail}</p><Link className="mt-3 inline-flex min-h-11 items-center font-bold text-blue-800 underline" href={href}>Open {title}</Link></details>)}</div></section>;
}
