/**
 * GET /api/learner/progress
 * Canonical learner dashboard API.
 */
import { NextRequest, NextResponse } from 'next/server';
import type { SupabaseClient } from '@supabase/supabase-js';
import { requireAuth } from '@/lib/auth/requireAuth';
import { createClient } from '@/lib/supabase/server';
import { loadBlueprintWithProgram } from '@/lib/course-factory/blueprint-loader';
import { blueprintToDashboard, type LearnerContext, type CourseProgress, type ModuleProgress, type LessonProgress, type CompetencyProgress, type CertificationReadiness, type PracticeExam, type ApprenticeshipProgress } from '@/lib/course-factory/integration/types';
export const dynamic='force-dynamic';
interface RouteContext { params: Promise<{courseId?:string}> }
export async function GET(request:NextRequest,context:RouteContext){try{const {user,error:authError}=await requireAuth(request);if(authError)return NextResponse.json({error:'Unauthorized'},{status:401});const {courseId}=await context.params;const programSlug=request.nextUrl.searchParams.get('programSlug');const supabase=await createClient();let q=supabase.from('enrollments').select('*, courses(*)').eq('user_id',user!.id);if(courseId)q=q.eq('course_id',courseId);else if(programSlug)q=q.eq('courses.program_slug',programSlug).eq('status','active');const {data:enrollment,error}=await q.single();if(error||!enrollment)return NextResponse.json({error:'Not enrolled'},{status:404});const course=enrollment.courses;const blueprint=await loadBlueprintWithProgram(supabase,{programId:course.program_id});if(!blueprint)return NextResponse.json({error:'Blueprint not found'},{status:404});const learnerContext:LearnerContext={learnerId:user!.id,enrollmentId:enrollment.id,programSlug:course.program_slug,courseId:enrollment.course_id,enrollmentType:enrollment.enrollment_type||'standard',startedAt:new Date(enrollment.created_at),lastActiveAt:new Date()};const [mp,lp,cp,cert,exams,apprentice]=await Promise.all([supabase.from('module_progress').select('*').eq('learner_id',user!.id).eq('course_id',enrollment.course_id),supabase.from('lesson_progress').select('*').eq('learner_id',user!.id).eq('course_id',enrollment.course_id),supabase.from('competency_progress').select('*').eq('learner_id',user!.id).eq('course_id',enrollment.course_id),blueprint.certificationPathway?supabase.from('certification_readiness').select('*').eq('learner_id',user!.id).eq('certification_id',blueprint.certificationPathway.certificationBodyId).single():Promise.resolve({data:null}),supabase.from('practice_exams').select('*').eq('program_id',course.program_id).eq('is_active',true),enrollment.enrollment_type==='apprentice'?supabase.from('apprenticeship_progress').select('*').eq('learner_id',user!.id).eq('enrollment_id',enrollment.id).single():Promise.resolve({data:null})]);const courseProgress=buildCourseProgress(enrollment,blueprint,lp.data||[]);const dashboard=blueprintToDashboard(blueprint,learnerContext,courseProgress,buildModuleProgress(blueprint,mp.data||[]),buildLessonProgress(blueprint,lp.data||[]),buildCompetencyProgress(blueprint,cp.data||[]),cert.data as CertificationReadiness|null,(exams.data||[]) as PracticeExam[],apprentice.data as ApprenticeshipProgress|null);dashboard.notifications=await getNotificationSummary(supabase,user!.id);return NextResponse.json({success:true,dashboard});}catch(error){console.error('[Learner Dashboard] Error:',error);return NextResponse.json({error:'Failed to load dashboard'},{status:500});}}
function buildCourseProgress(e:Record<string,unknown>,b:{modules:Array<{lessons?:unknown[]}>},l:Array<{completed:boolean}>):CourseProgress{const total=b.modules.reduce((s,m)=>s+(m.lessons?.length||0),0),done=l.filter(x=>x.completed).length;return{courseId:e.course_id as string,learnerId:e.user_id as string,percentComplete:total?Math.round(done/total*100):0,currentModuleSlug:'',currentLessonSlug:'',totalTimeSpent:0,completedLessons:done,totalLessons:total,completedModules:0,totalModules:b.modules.length,status:done?'in-progress':'not-started',lastActiveAt:new Date()};}
function buildModuleProgress(b:any,d:Record<string,unknown>[]):ModuleProgress[]{const m=new Map(d.map(x=>[x.module_slug,x]));return b.modules.map((x:any)=>{const s=m.get(x.slug),t=x.lessons?.length||0,c=(s?.lessons_completed as number)||0;return{moduleSlug:x.slug,moduleTitle:x.title,orderIndex:x.orderIndex,percentComplete:t?Math.round(c/t*100):0,lessonsCompleted:c,totalLessons:t,quizScores:[],competencyProgress:{},startedAt:new Date((s?.started_at as string)||Date.now()),completedAt:s?.completed_at?new Date(s.completed_at as string):undefined};});}
function buildLessonProgress(b:any,d:Record<string,unknown>[]):LessonProgress[]{const m=new Map(d.map(x=>[x.lesson_slug,x])),out:LessonProgress[]=[];for(const mod of b.modules)for(const x of mod.lessons||[]){const s=m.get(x.slug);out.push({lessonSlug:x.slug,lessonTitle:x.title,order:x.order,percentComplete:(s?.percent_complete as number)||0,timeSpent:(s?.time_spent as number)||0,completed:!!s?.completed,completedAt:s?.completed_at?new Date(s.completed_at as string):undefined,interactionsCompleted:(s?.interactions_completed as string[])||[],interactionsTotal:0,knowledgeCheckScore:s?.quiz_score as number|undefined,flashcardMastery:s?.flashcard_mastery as number|undefined});}return out;}
function buildCompetencyProgress(b:any,d:Record<string,unknown>[]):CompetencyProgress[]{const m=new Map<string,CompetencyProgress>();for(const mod of b.modules)for(const c of mod.competencies||[])if(!m.has(c.competencyKey))m.set(c.competencyKey,{competencyKey:c.competencyKey,competencyName:c.competencyKey.replace(/_/g,' '),currentLevel:0,targetLevel:100,touchpoints:[],verified:false,requiredSkills:c.minimumTouchpoints,completedSkills:0});for(const r of d){const x=m.get(r.competency_key as string);if(x){x.currentLevel=(r.current_level as number)||0;x.verified=!!r.verified;}}return[...m.values()];}
async function getNotificationSummary(supabase:SupabaseClient<any>,userId:string){const {data}=await supabase.from('notifications').select('id, type, title, read_at, created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(5);return{unread:data?.filter(n=>!n.read_at).length||0,recent:(data||[]).map(n=>({id:n.id,type:n.type,title:n.title,body:'',createdAt:n.created_at,read:!!n.read_at,priority:'medium' as const}))};}
