import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createServer } from 'node:http';
import { chmod, chown, mkdir, readFile, readdir, readlink, rename, rm, symlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const execFileAsync = promisify(execFile);
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ENDPOINT = /^pwa-[0-9a-f]{40}$/;
const EXTENSION = /^(0|[1-9][0-9]{2})$/;
const DEVICE = /^[A-Za-z0-9_-]{8,128}$/;
const SECRET_VERSION = /^projects\/(elegant-racer-299721|484736877039)\/secrets\/[A-Za-z0-9_-]+\/versions\/([0-9]+|latest)$/;
const LEASE_MS = 10 * 60 * 1000;
const DAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
const TIME = /^(?:[01][0-9]|2[0-3]):[0-5][0-9]$/;

class ProvisioningError extends Error {
  constructor(code, status = 503) { super(code); this.code = code; this.status = status; }
}

export function validateIdentity(input) {
  if (!input || !UUID.test(input.profileId || '') || !UUID.test(input.extensionId || '') || !DEVICE.test(input.deviceId || '')) {
    throw new ProvisioningError('invalid_identity', 400);
  }
  return { profileId: input.profileId.toLowerCase(), extensionId: input.extensionId.toLowerCase(), deviceId: input.deviceId };
}

export function endpointFor(identity) {
  return `pwa-${createHash('sha256').update(`${identity.profileId}:${identity.deviceId}`).digest('hex').slice(0, 40)}`;
}

function validateRecord(record) {
  const identity = validateIdentity(record);
  if (record.endpointId !== endpointFor(identity) || !ENDPOINT.test(record.endpointId) ||
      !EXTENSION.test(record.extension) || !/^[A-Za-z0-9_-]{43}$/.test(record.password) ||
      !Number.isInteger(record.ringSeconds) || record.ringSeconds < 5 || record.ringSeconds > 60 ||
      !Number.isSafeInteger(record.expiresAt) || !EXTENSION.test(record.adminExtension) ||
      !/^[A-Za-z_]+(?:\/[A-Za-z_+-]+)+$/.test(record.timezone) ||
      !['ring', 'vibrate', 'silent', 'do_not_disturb', 'offline'].includes(record.ringMode) ||
      !['manual', 'schedule'].includes(record.availabilitySource)) {
    throw new ProvisioningError('invalid_stored_record');
  }
  return record;
}

export function renderConfiguration(records) {
  records.forEach(validateRecord);
  const extensionOwners = new Map();
  for (const record of records) {
    const owner = extensionOwners.get(record.extension);
    if (owner && owner !== record.extensionId) throw new ProvisioningError('duplicate_extension');
    extensionOwners.set(record.extension, record.extensionId);
  }
  const pjsip = ['; Generated by Elevate PBX provisioning. Contains credentials; never log or commit.'];
  const dialplan = ['; Generated scoped WebRTC routes. Carrier and PARIS routes remain unchanged.', '[elevate-pwa]',
    'exten => 0,1,Goto(elevate-pwa-dispatch,0,1)', 'exten => _XXX,1,Goto(elevate-pwa-dispatch,${EXTEN},1)',
    'exten => _.,1,Congestion(3)', ' same => n,Hangup()', '[elevate-pwa-dispatch]',
    'exten => _X!,1,GotoIf($[${ELEVATE_PWA_LEASE}<=${EPOCH}]?unavailable)',
    ' same => n,GotoIf($[${DIALPLAN_EXISTS(elevate-pwa-extensions,${EXTEN},1)}=0]?unavailable)',
    ' same => n,Gosub(elevate-pwa-extensions,${EXTEN},1)',
    ' same => n,GotoIf($["${DIALSTATUS}"="ANSWER"]?finished)',
    ' same => n(unavailable),Congestion(3)', ' same => n(finished),Hangup()', '[elevate-pwa-extensions]'];
  for (const record of records) {
    const id = record.endpointId;
    pjsip.push(`\n[${id}]`, 'type=endpoint', 'context=elevate-pwa', 'disallow=all', 'allow=ulaw,alaw',
      `auth=${id}-auth`, `aors=${id}`, 'webrtc=yes', 'dtls_auto_generate_cert=yes', 'media_encryption=dtls',
      'dtls_verify=fingerprint', 'dtls_setup=actpass', 'ice_support=yes', 'rtcp_mux=yes', 'use_avpf=yes',
      'media_use_received_transport=yes', 'direct_media=no', 'rewrite_contact=yes', 'force_rport=yes',
      'rtp_symmetric=yes', 'identify_by=username,auth_username', `callerid=Extension ${record.extension} <${record.extension}>`,
      `set_var=ELEVATE_PWA_LEASE=${Math.floor(record.expiresAt / 1000)}`,
      `\n[${id}-auth]`, 'type=auth', 'auth_type=userpass', `username=${id}`, `password=${record.password}`,
      `\n[${id}]`, 'type=aor', 'max_contacts=1', 'remove_existing=yes', 'default_expiration=120',
      'minimum_expiration=60', 'maximum_expiration=300', 'qualify_frequency=30', 'qualify_timeout=3.0');
  }
  for (const extension of [...extensionOwners.keys()].sort()) {
    const devices = records.filter(record => record.extension === extension);
    const policy = devices[0];
    dialplan.push(`exten => ${extension},1,Set(PWA_CONTACTS=)`);
    if (['offline', 'do_not_disturb'].includes(policy.ringMode)) {
      dialplan.push(' same => n,Set(DIALSTATUS=CHANUNAVAIL)', ' same => n,Return()');
      continue;
    }
    if (policy.availabilitySource === 'schedule') {
      for (const day of DAYS) {
        const window = policy.availabilitySchedule?.[day];
        if (Array.isArray(window) && window.length === 2 && TIME.test(window[0]) && TIME.test(window[1]) && window[0] < window[1]) {
          // Asterisk time ranges include their final minute; app policy excludes it.
          const [hour, minute] = window[1].split(':').map(Number);
          const finalMinute = hour * 60 + minute - 1;
          const inclusiveEnd = `${String(Math.floor(finalMinute / 60)).padStart(2, '0')}:${String(finalMinute % 60).padStart(2, '0')}`;
          dialplan.push(` same => n,GotoIfTime(${window[0]}-${inclusiveEnd},${day},*,*,${policy.timezone}?available)`);
        }
      }
      dialplan.push(' same => n,Goto(unavailable)');
    }
    dialplan.push(' same => n(available),NoOp(Authenticated internal device ring group)');
    for (const record of devices) {
      dialplan.push(' same => n,Set(PWA_DEVICE_CONTACTS=)',
        ` same => n,ExecIf($[\${EPOCH}<${Math.floor(record.expiresAt / 1000)}]?Set(PWA_DEVICE_CONTACTS=\${PJSIP_DIAL_CONTACTS(${record.endpointId})}))`,
        ' same => n,ExecIf($[${LEN(${PWA_DEVICE_CONTACTS})}>0]?Set(PWA_CONTACTS=${PWA_CONTACTS}${IF($[${LEN(${PWA_CONTACTS})}>0]?&:)}${PWA_DEVICE_CONTACTS}))');
    }
    dialplan.push(
      ' same => n,GotoIf($[${LEN(${PWA_CONTACTS})}=0]?unavailable)',
      ` same => n,Dial(\${PWA_CONTACTS},${devices[0].ringSeconds})`,
      ' same => n,Return()', ' same => n(unavailable),Set(DIALSTATUS=CHANUNAVAIL)', ' same => n,Return()');
  }
  if (records.length && !extensionOwners.has('0')) {
    const adminExtension = records[0].adminExtension;
    if (extensionOwners.has(adminExtension)) {
      dialplan.push(`exten => 0,1,Gosub(elevate-pwa-extensions,${adminExtension},1)`, ' same => n,Return()');
    }
  }
  return { pjsip: `${pjsip.join('\n')}\n`, dialplan: `${dialplan.join('\n')}\n` };
}

export function parseContacts(output, endpointId) {
  if (!ENDPOINT.test(endpointId) || !new RegExp(`Aor:\\s+${endpointId}\\s`).test(output)) {
    throw new ProvisioningError('asterisk_aor_unverified');
  }
  const contacts = output.split('\n').filter(line => line.trim().startsWith(`Contact:  ${endpointId}/`) ||
    new RegExp(`^\\s*Contact:\\s+${endpointId}/`).test(line));
  return { contactCount: contacts.length, reachableContactCount: contacts.filter(line => /\sAvail\s/.test(line)).length };
}

async function supabaseOwner(identity, config, fetchImpl) {
  const query = new URL('/rest/v1/communication_extensions', config.supabaseUrl);
  query.searchParams.set('id', `eq.${identity.extensionId}`);
  query.searchParams.set('profile_id', `eq.${identity.profileId}`);
  query.searchParams.set('select', 'id,profile_id,extension,enabled,webrtc_provider,ring_seconds,ring_mode,availability_source,availability_schedule,communication_workspaces!inner(phone_system_id,phone_systems!inner(admin_extension,timezone,status))');
  const response = await fetchImpl(query, {
    headers: { apikey: config.supabaseKey, authorization: `Bearer ${config.supabaseKey}` },
    signal: AbortSignal.timeout(10000), redirect: 'error',
  });
  if (!response.ok) throw new ProvisioningError('ownership_unavailable');
  const rows = await response.json();
  if (!Array.isArray(rows) || rows.length !== 1) throw new ProvisioningError('device_not_authorized', 403);
  const row = rows[0];
  if (!row.enabled || row.webrtc_provider !== 'asterisk' || !EXTENSION.test(row.extension) ||
      row.communication_workspaces?.phone_system_id !== config.phoneSystemId) {
    throw new ProvisioningError('device_not_authorized', 403);
  }
  const system = row.communication_workspaces.phone_systems;
  if (!system || system.status !== 'active' || !EXTENSION.test(system.admin_extension) || !/^[A-Za-z_]+(?:\/[A-Za-z_+-]+)+$/.test(system.timezone)) {
    throw new ProvisioningError('phone_system_configuration_invalid');
  }
  try { new Intl.DateTimeFormat('en-US', { timeZone: system.timezone }).format(); }
  catch { throw new ProvisioningError('phone_system_configuration_invalid'); }
  return { extension: row.extension, ringSeconds: Number.isInteger(row.ring_seconds) ? Math.max(5, Math.min(60, row.ring_seconds)) : 20,
    ringMode: row.ring_mode, availabilitySource: row.availability_source, availabilitySchedule: row.availability_schedule,
    adminExtension: system.admin_extension, timezone: system.timezone };
}

async function confirmActiveDevice(identity, endpointId, config, fetchImpl) {
  const query = new URL('/rest/v1/phone_webrtc_devices', config.supabaseUrl);
  for (const [field, value] of Object.entries({ profile_id: identity.profileId, device_id: identity.deviceId,
    extension_id: identity.extensionId, status: 'active', provider_credential_id: endpointId })) {
    query.searchParams.set(field, `eq.${value}`);
  }
  query.searchParams.set('select', 'id');
  const response = await fetchImpl(query, { headers: { apikey: config.supabaseKey, authorization: `Bearer ${config.supabaseKey}` },
    signal: AbortSignal.timeout(10000), redirect: 'error' });
  if (!response.ok) throw new ProvisioningError('device_authorization_unavailable');
  const rows = await response.json();
  if (!Array.isArray(rows) || rows.length !== 1) throw new ProvisioningError('device_not_authorized', 403);
}

async function defaultCommand(container, command) {
  try {
    const { stdout } = await execFileAsync('/usr/bin/docker', ['exec', container, 'asterisk', '-rx', command], {
      timeout: 15000, maxBuffer: 1024 * 1024,
    });
    return stdout;
  } catch {
    // Never expose exec error objects: their stdout/stderr may contain credentials.
    throw new ProvisioningError('asterisk_command_failed');
  }
}

export function createProvisioner(config, dependencies = {}) {
  if (!config.token || Buffer.byteLength(config.token) < 32 || !UUID.test(config.phoneSystemId || '') ||
      new URL(config.supabaseUrl).protocol !== 'https:' || !config.supabaseKey ||
      !/^[A-Za-z0-9_.-]+$/.test(config.container || '') || !Number.isInteger(config.asteriskGid) || config.asteriskGid < 0 ||
      config.sipDomain !== 'phone.elevateforhumanity.org' || config.wsUrl !== 'wss://phone.elevateforhumanity.org/ws' ||
      !path.isAbsolute(config.generatedRoot || '')) throw new Error('Invalid PBX provisioning configuration');
  const fetchImpl = dependencies.fetch || fetch;
  const now = dependencies.now || Date.now;
  const command = dependencies.command || (value => defaultCommand(config.container, value));
  const owner = identity => supabaseOwner(identity, config, fetchImpl);
  let records = [];
  let queue = Promise.resolve();
  let initialized = false;
  let quarantined = false;

  function serialize(operation) {
    const result = queue.then(operation);
    queue = result.catch(() => {});
    return result;
  }

  async function protect(filename, mode) {
    await chmod(filename, mode);
    await chown(filename, process.getuid(), config.asteriskGid);
  }

  async function inspect(record) {
    const text = await command(`pjsip show endpoint ${record.endpointId}`);
    if (!new RegExp(`Endpoint:\\s+${record.endpointId}(?:[ /]|$)`, 'm').test(text) ||
        !/context\s*:\s*elevate-pwa\s/.test(text) ||
        !new RegExp(`auth\\s*:\\s*${record.endpointId}-auth\\s`).test(text) ||
        !new RegExp(`aors\\s*:\\s*${record.endpointId}\\s`).test(text) ||
        !/media_encryption\s*:\s*dtls\s/.test(text)) {
      throw new ProvisioningError('asterisk_endpoint_unverified');
    }
    const status = parseContacts(await command(`pjsip show aor ${record.endpointId}`), record.endpointId);
    const plan = await command(`dialplan show ${record.extension}@elevate-pwa-extensions`);
    if (!plan.includes('elevate-pwa-extensions') ||
        (!['offline', 'do_not_disturb'].includes(record.ringMode) && !plan.includes('PJSIP_DIAL_CONTACTS(' + record.endpointId + ')')) ||
        /no such|not exist/i.test(plan)) throw new ProvisioningError('asterisk_dialplan_unverified');
    return status;
  }

  async function reloadAndVerify(next, removed = []) {
    for (const operation of ['pjsip reload', 'dialplan reload']) {
      const output = await command(operation);
      if (/no such command|unable to reload|failed to reload/i.test(output)) throw new ProvisioningError('asterisk_reload_failed');
    }
    for (const record of next) await inspect(record);
    for (const record of removed) {
      const endpoint = await command(`pjsip show endpoint ${record.endpointId}`);
      if (!/unable to find object|not found|no such/i.test(endpoint)) throw new ProvisioningError('asterisk_revocation_unverified');
    }
  }

  async function apply(next) {
    const rendered = renderConfiguration(next);
    const current = path.join(config.generatedRoot, 'current');
    let previous;
    try { previous = await readlink(current); } catch (error) { if (error.code !== 'ENOENT') throw error; }
    const generation = `generation-${randomBytes(12).toString('hex')}`;
    const directory = path.join(config.generatedRoot, generation);
    await mkdir(directory, { mode: 0o750 });
    await protect(directory, 0o750);
    for (const [name, contents, mode] of [
      ['pjsip.conf', rendered.pjsip, 0o640], ['extensions.conf', rendered.dialplan, 0o640],
      ['state.json', JSON.stringify(next), 0o600],
    ]) {
      await writeFile(path.join(directory, name), contents, { mode, flag: 'wx' });
      await protect(path.join(directory, name), mode);
    }
    const link = path.join(config.generatedRoot, `pending-${randomBytes(12).toString('hex')}`);
    await symlink(generation, link);
    await rename(link, current);
    try {
      await reloadAndVerify(next, records.filter(record => !next.some(candidate => candidate.endpointId === record.endpointId)));
      records = next;
    } catch {
      try {
        if (previous) { await symlink(previous, link); await rename(link, current); }
        else await rm(current);
        await reloadAndVerify(records, next.filter(record => !records.some(candidate => candidate.endpointId === record.endpointId)));
      } catch {
        quarantined = true;
        throw new ProvisioningError('asterisk_rollback_failed');
      }
      await rm(directory, { recursive: true, force: true });
      throw new ProvisioningError('asterisk_configuration_rejected');
    }
    // Retain only the active and previous generations for rollback. These are
    // service-owned files; production call records and voicemail are untouched.
    for (const name of await readdir(config.generatedRoot)) {
      if (/^generation-[0-9a-f]{24}$/.test(name) && name !== generation && name !== previous) {
        // Cleanup cannot turn an applied credential into a failed API response.
        await rm(path.join(config.generatedRoot, name), { recursive: true, force: true }).catch(() => {});
      }
    }
  }

  async function initialize() {
    await mkdir(config.generatedRoot, { recursive: true, mode: 0o750 });
    await protect(config.generatedRoot, 0o750);
    try {
      const generation = await readlink(path.join(config.generatedRoot, 'current'));
      if (!/^generation-[0-9a-f]{24}$/.test(generation)) throw new ProvisioningError('invalid_generation');
      records = JSON.parse(await readFile(path.join(config.generatedRoot, generation, 'state.json'), 'utf8'));
      if (!Array.isArray(records)) throw new ProvisioningError('invalid_stored_state');
      records.forEach(validateRecord);
    } catch (error) { if (error.code !== 'ENOENT') throw error; }
    // Reconcile crash recovery before accepting new credentials. Fail closed if
    // Supabase cannot confirm authority; never silently overwrite existing state.
    await reconcile();
    initialized = true;
  }

  async function pruneExpired() {
    return serialize(async () => {
      if (quarantined) throw new ProvisioningError('provisioner_quarantined');
      const active = records.filter(record => record.expiresAt > now());
      if (active.length !== records.length) await apply(active);
    });
  }

  async function reconcile() {
    return serialize(async () => {
      if (quarantined) throw new ProvisioningError('provisioner_quarantined');
      const active = [];
      for (const record of records) {
        if (record.expiresAt <= now()) continue;
        try { active.push({ ...record, ...await owner(record) }); }
        catch (error) { if (error.code !== 'device_not_authorized') throw error; }
      }
      if (JSON.stringify(active) !== JSON.stringify(records)) await apply(active);
      else for (const record of records) await inspect(record);
    });
  }

  async function operate(action, input) {
    const identity = validateIdentity(input);
    return serialize(async () => {
      if (!initialized || quarantined) throw new ProvisioningError('provisioner_unavailable');
      const metadata = await owner(identity);
      const endpointId = endpointFor(identity);
      let existing = records.find(record => record.endpointId === endpointId);
      if (existing && existing.extensionId !== identity.extensionId) throw new ProvisioningError('device_assignment_conflict', 409);
      if (action === 'status') {
        if (existing && existing.expiresAt <= now()) {
          await apply(records.filter(record => record.endpointId !== endpointId)); existing = undefined;
        }
        if (existing) {
          await confirmActiveDevice(identity, endpointId, config, fetchImpl);
          const refreshed = { ...existing, ...metadata };
          if (existing.expiresAt - now() < LEASE_MS / 2) refreshed.expiresAt = now() + LEASE_MS;
          if (JSON.stringify(refreshed) !== JSON.stringify(existing)) {
            await apply(records.map(record => record.endpointId === endpointId ? refreshed : record)); existing = refreshed;
          }
        }
        const status = existing ? await inspect(existing) : { contactCount: 0, reachableContactCount: 0 };
        return { provider: 'asterisk', endpointId, registered: status.contactCount > 0, ...status,
          connectionState: status.reachableContactCount > 0 ? 'connected' : 'disconnected', observedAt: new Date(now()).toISOString(),
          expiresAt: existing ? new Date(existing.expiresAt).toISOString() : null };
      }
      if (action === 'revoke') {
        if (existing) await apply(records.filter(record => record.endpointId !== endpointId));
        return { provider: 'asterisk', endpointId, revoked: true, observedAt: new Date().toISOString() };
      }
      if (records.filter(record => record.profileId === identity.profileId).length >= 10 && !existing) {
        throw new ProvisioningError('device_limit_reached', 409);
      }
      const record = existing ? { ...existing, ...metadata, expiresAt: now() + LEASE_MS } : {
        ...identity, ...metadata, endpointId, password: randomBytes(32).toString('base64url'), expiresAt: now() + LEASE_MS,
      };
      if (!existing || JSON.stringify(record) !== JSON.stringify(existing)) {
        await apply([...records.filter(candidate => candidate.endpointId !== endpointId), record]);
      } else await inspect(existing);
      return { provider: 'asterisk', endpointId, sipUsername: endpointId, sipPassword: record.password,
        sipDomain: config.sipDomain, wsUrl: config.wsUrl, extensionId: identity.extensionId, extension: record.extension,
        registrationState: 'unregistered', connectionState: 'disconnected', expiresAt: new Date(record.expiresAt).toISOString() };
    });
  }

  const server = createServer(async (request, response) => {
    response.setHeader('Cache-Control', 'no-store');
    response.setHeader('Content-Type', 'application/json');
    const reply = (status, value) => { response.statusCode = status; response.end(JSON.stringify(value)); };
    const authorization = Buffer.from(request.headers.authorization || '');
    const expected = Buffer.from(`Bearer ${config.token}`);
    if (authorization.length !== expected.length || !timingSafeEqual(authorization, expected)) {
      request.resume(); return reply(401, { error: 'unauthorized' });
    }
    const actions = new Map([
      ['/internal/pbx/devices', 'provision'], ['/internal/pbx/devices/status', 'status'], ['/internal/pbx/devices/revoke', 'revoke'],
    ]);
    if (request.method !== 'POST' || !actions.has(request.url)) { request.resume(); return reply(404, { error: 'not_found' }); }
    if (!/^application\/json(?:\s*;|$)/i.test(request.headers['content-type'] || '')) {
      request.resume(); return reply(415, { error: 'json_required' });
    }
    try {
      const chunks = []; let size = 0;
      for await (const chunk of request) {
        size += chunk.length;
        if (size > 4096) throw new ProvisioningError('request_too_large', 413);
        chunks.push(chunk);
      }
      let input;
      try { input = JSON.parse(Buffer.concat(chunks).toString('utf8')); }
      catch { throw new ProvisioningError('invalid_json', 400); }
      reply(200, await operate(actions.get(request.url), input));
    } catch (error) {
      reply(error instanceof ProvisioningError ? error.status : 503,
        { error: error instanceof ProvisioningError ? error.code : 'provisioner_unavailable' });
    }
  });
  server.requestTimeout = 15000;
  server.headersTimeout = 10000;
  return { server, initialize, reconcile, pruneExpired };
}

async function secretFromGoogle(version) {
  if (!SECRET_VERSION.test(version || '')) throw new Error('Invalid Google Secret Manager resource');
  const metadata = await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token', {
    headers: { 'Metadata-Flavor': 'Google' }, signal: AbortSignal.timeout(5000), redirect: 'error',
  });
  if (!metadata.ok) throw new Error('Google workload identity unavailable');
  const { access_token: accessToken } = await metadata.json();
  const response = await fetch(`https://secretmanager.googleapis.com/v1/${version}:access`, {
    headers: { authorization: `Bearer ${accessToken}` }, signal: AbortSignal.timeout(10000), redirect: 'error',
  });
  if (!response.ok) throw new Error('Google Secret Manager access failed');
  const body = await response.json();
  if (!body.payload?.data) throw new Error('Google secret payload missing');
  return Buffer.from(body.payload.data, 'base64').toString('utf8').trim();
}

async function main() {
  if (process.argv.includes('--invalidate')) {
    // systemd invokes this after any process exit, including SIGKILL. Removing only
    // this service's include symlink prevents stale auth objects surviving a stopped
    // lease reconciler. Existing call dialogs are not hung up by PJSIP reload.
    const root = process.env.PBX_GENERATED_ROOT;
    const container = process.env.PBX_ASTERISK_CONTAINER;
    if (!path.isAbsolute(root || '') || !/^[A-Za-z0-9_.-]+$/.test(container || '')) throw new Error('Invalid cleanup configuration');
    await rm(path.join(root, 'current'), { force: true });
    for (const cmd of ['pjsip reload', 'dialplan reload']) {
      const output = await defaultCommand(container, cmd);
      if (/no such command|unable to reload|failed to reload/i.test(output)) throw new Error('Cleanup reload failed');
    }
    const endpoints = await defaultCommand(container, 'pjsip show endpoints');
    if (/Endpoint:\s+pwa-[0-9a-f]{40}/.test(endpoints)) throw new Error('Cleanup endpoint removal unverified');
    return;
  }
  const service = createProvisioner({
    token: await secretFromGoogle(process.env.PBX_PROVISIONING_TOKEN_SECRET),
    supabaseKey: await secretFromGoogle(process.env.SUPABASE_SERVICE_ROLE_KEY_SECRET),
    supabaseUrl: process.env.SUPABASE_URL, phoneSystemId: process.env.PBX_PHONE_SYSTEM_ID,
    sipDomain: 'phone.elevateforhumanity.org', wsUrl: 'wss://phone.elevateforhumanity.org/ws',
    container: process.env.PBX_ASTERISK_CONTAINER, asteriskGid: Number(process.env.PBX_ASTERISK_GID),
    generatedRoot: process.env.PBX_GENERATED_ROOT,
  });
  await service.initialize();
  service.server.listen(8090, '127.0.0.1');
  const timer = setInterval(() => service.reconcile().catch(() => {
    process.stderr.write('PBX ownership/runtime reconciliation failed; investigate before accepting new devices.\n');
  }), 60000);
  const expiryTimer = setInterval(() => service.pruneExpired().catch(() => {
    process.stderr.write('PBX expired-credential revocation failed; investigate immediately.\n');
  }), 5000);
  for (const signal of ['SIGTERM', 'SIGINT']) process.once(signal, () => {
    clearInterval(timer); clearInterval(expiryTimer); service.server.close();
  });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main().catch(() => { process.stderr.write('PBX provisioner startup failed. No credentials were logged.\n'); process.exitCode = 1; });
}
