import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Career Training & Apprenticeship Opportunities in Texas | Elevate for Humanity',
  description: 'Texas residents and employers can express interest in Elevate for Humanity career training, Registered Apprenticeship pathways, employer partnerships, and workforce-funded opportunities as Texas expansion develops.',
  keywords: ['Texas career training','Texas apprenticeship programs','registered apprenticeship Texas','workforce training Texas','Austin career training','Austin apprenticeship','San Antonio apprenticeship','Dallas apprenticeship','Houston apprenticeship','Texas workforce development'],
  alternates: { canonical: 'https://www.elevateforhumanity.org/texas' },
  robots: { index: true, follow: true },
};

export default function TexasPage() {
 const ld={ '@context':'https://schema.org','@type':'Service',name:'Texas workforce training and Registered Apprenticeship expansion',provider:{'@type':'Organization',name:'Elevate for Humanity'},areaServed:{'@type':'State',name:'Texas'},serviceType:'Career training, workforce development and Registered Apprenticeship coordination'};
 return <main className="bg-white text-slate-950"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(ld)}}/>
 <section className="px-4 py-20 sm:py-28"><div className="mx-auto max-w-6xl grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="text-sm font-black uppercase tracking-[.16em] text-red-700">Texas expansion</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">Career training and apprenticeship opportunities are expanding into Texas.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-700">Elevate for Humanity is developing Texas employer, workforce, and Registered Apprenticeship relationships beginning in Austin and expanding toward San Antonio, Dallas–Fort Worth, Houston, and additional communities. Residents can join the interest pipeline now; employers can request partnership information.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/apply" className="rounded-xl bg-red-700 px-6 py-3 font-black text-white">Texas Students: Start Here</Link><Link href="/apply/employer" className="rounded-xl border-2 border-slate-950 px-6 py-3 font-black">Texas Employers: Partner With Us</Link></div></div><div className="rounded-3xl border border-slate-200 p-7 shadow-xl"><h2 className="text-2xl font-black">Areas of interest</h2><p className="mt-3 leading-7 text-slate-700">Skilled trades and HVAC, healthcare, transportation, business pathways, and eligible Registered Apprenticeship occupations. Availability, funding, employer placement, and program approval vary by location and participant eligibility.</p><p className="mt-5 text-sm font-bold text-slate-600">Initial hub: Austin · Statewide Texas development</p></div></div></section>
 <section className="border-y border-slate-200 px-4 py-14"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black">Texas employers: help build the talent pipeline.</h2><p className="mt-3 max-w-3xl leading-7 text-slate-700">Employers can discuss hiring needs, supervised on-the-job learning, Registered Apprenticeship participation, and workforce partnership opportunities. Funding and reimbursement are never guaranteed and require approval from the applicable workforce authority.</p><Link href="/apply/employer" className="mt-6 inline-flex rounded-xl bg-slate-950 px-6 py-3 font-black text-white">Request Employer Partnership Information</Link></div></section></main>;
}