import{NextRequest,NextResponse}from'next/server';
import{verifyPayPalWebhookSignature}from'@/lib/payments/paypal-payouts';
import{recordContractorPaymentInQuickBooks}from'@/lib/integrations/quickbooks-contractor-payment';
import{requireAdminClient}from'@/lib/supabase/admin';
export const dynamic='force-dynamic';
type Event={event_type?:string;resource?:{payout_batch_id?:string;batch_header?:{payout_batch_id?:string};transaction_status?:string}};
const success=new Set(['PAYMENT.PAYOUTSBATCH.SUCCESS','PAYMENT.PAYOUTS-ITEM.SUCCEEDED']);
const failure=new Set(['PAYMENT.PAYOUTSBATCH.DENIED','PAYMENT.PAYOUTS-ITEM.BLOCKED','PAYMENT.PAYOUTS-ITEM.CANCELED','PAYMENT.PAYOUTS-ITEM.DENIED','PAYMENT.PAYOUTS-ITEM.FAILED','PAYMENT.PAYOUTS-ITEM.RETURNED']);
export async function POST(r:NextRequest){const e=await r.json().catch(()=>null)as Event|null;if(!e||!await verifyPayPalWebhookSignature(r.headers,e as Record<string,unknown>))return NextResponse.json({error:'Invalid PayPal signature.'},{status:401});const transfer=e.resource?.payout_batch_id||e.resource?.batch_header?.payout_batch_id;if(!transfer||!success.has(e.event_type||'')&&!failure.has(e.event_type||''))return NextResponse.json({received:true});const db=await requireAdminClient();const{data:t}=await db.from('program_holder_payout_transactions').select('id,payout_schedule_id,enrollment_id,program_holder_id,amount_cents,quickbooks_status').eq('provider','paypal').eq('provider_transfer_id',transfer).maybeSingle();if(!t)return NextResponse.json({received:true});const now=new Date().toISOString(),ok=success.has(e.event_type||'');await db.from('program_holder_payout_transactions').update({status:ok?'paid':'failed',provider_status:e.resource?.transaction_status||e.event_type,paid_at:ok?now:null,failure_reason:ok?null:e.event_type,updated_at:now}).eq('id',t.id);if(ok){await Promise.all([db.from('payout_schedules').update({increment_1_status:'paid',increment_1_paid_at:now,updated_at:now}).eq('id',t.payout_schedule_id),db.from('program_enrollments').update({payout_status:'paid',payout_paid_date:now}).eq('id',t.enrollment_id)]);const{data:claim}=await db.from('program_holder_payout_transactions').update({quickbooks_status:'processing'}).eq('id',t.id).in('quickbooks_status',['pending','failed']).select('id').maybeSingle();if(claim){const[{data:h},{data:n}]=await Promise.all([db.from('program_holders').select('name,organization_name,contact_email').eq('id',t.program_holder_id).maybeSingle(),db.from('program_enrollments').select('full_name').eq('id',t.enrollment_id).maybeSingle()]);const q=await recordContractorPaymentInQuickBooks(db,{contractorName:h?.organization_name||h?.name||'Program Holder',contractorEmail:h?.contact_email,amountCents:t.amount_cents,enrollmentId:t.enrollment_id,providerTransferId:transfer,memo:`Program training payment — ${n?.full_name||t.enrollment_id}`});await db.from('program_holder_payout_transactions').update({quickbooks_status:q.synced?'synced':'failed',quickbooks_payment_id:q.synced?q.paymentId:null,quickbooks_error:q.synced?null:q.reason,updated_at:new Date().toISOString()}).eq('id',t.id)}}return NextResponse.json({received:true})}
