import JSZip from 'jszip';
import { XMLParser } from 'fast-xml-parser';

export type EmployerImportRow = { row:number; business_name:string; address_line1:string; city:string; state:string; zip_code:string; fein?:string; contact_name?:string; contact_email?:string; contact_phone?:string };
export type EmployerImportError = { row:number; errors:string[] };
const REQUIRED = [['business_name','Name'],['address_line1','Street Address'],['city','City'],['state','State'],['zip_code','Zip Code']] as const;
const ALIASES:Record<string,keyof Omit<EmployerImportRow,'row'>>={name:'business_name',employer:'business_name',employername:'business_name',businessname:'business_name',companyname:'business_name',streetaddress:'address_line1',address:'address_line1',addressline1:'address_line1',city:'city',state:'state',zipcode:'zip_code',zip:'zip_code',postalcode:'zip_code',fein:'fein',ein:'fein',contactname:'contact_name',contactemail:'contact_email',email:'contact_email',contactphone:'contact_phone',phone:'contact_phone'};
const list=<T>(v:T|T[]|undefined):T[]=>v===undefined?[]:Array.isArray(v)?v:[v];
const normalize=(v:string)=>v.trim().toLowerCase().replace(/[^a-z0-9]/g,'');

export function parseCsv(text:string):string[][]{const rows:string[][]=[];let row:string[]=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){value+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);rows.push(row);row=[];value='';}else value+=c;}row.push(value);if(row.some(c=>c.trim()))rows.push(row);return rows;}

export async function parseXlsx(buffer:Buffer):Promise<string[][]>{const zip=await JSZip.loadAsync(buffer);const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:''});const xml=async(path:string)=>{const file=zip.file(path);return file?parser.parse(await file.async('text')):null;};const workbook=await xml('xl/workbook.xml');const rels=await xml('xl/_rels/workbook.xml.rels');const first=list(workbook?.workbook?.sheets?.sheet)[0] as any;if(!first||!rels)return[];const relation=list(rels.Relationships?.Relationship).find((r:any)=>r.Id===first['r:id']) as any;if(!relation?.Target)return[];const sharedDoc=await xml('xl/sharedStrings.xml');const shared=list(sharedDoc?.sst?.si).map((item:any)=>typeof item.t==='string'?item.t:list(item.r).map((run:any)=>String(run.t?.['#text']??run.t??'')).join(''));const target=String(relation.Target).replace(/^\/?xl\//,'');const sheet=await xml(`xl/${target}`);return list(sheet?.worksheet?.sheetData?.row).map((sheetRow:any)=>{const output:string[]=[];for(const cell of list(sheetRow.c) as any[]){const column=String(cell.r??'A').replace(/[0-9]/g,'');let index=0;for(const letter of column)index=index*26+letter.charCodeAt(0)-64;const raw=cell.v??cell.is?.t??'';output[index-1]=(cell.t==='s'?shared[Number(raw)]??'':String(typeof raw==='object'?raw['#text']??'':raw)).trim();}return output;});}

export function validateEmployerRows(matrix:string[][]){if(!matrix.length)return{valid:[] as EmployerImportRow[],errors:[{row:1,errors:['The file is empty.']}]};const headers=matrix[0].map(v=>ALIASES[normalize(v)]);const valid:EmployerImportRow[]=[];const errors:EmployerImportError[]=[];matrix.slice(1).forEach((cells,offset)=>{if(!cells.some(c=>String(c??'').trim()))return;const item:any={row:offset+2};headers.forEach((key,index)=>{if(key)item[key]=String(cells[index]??'').trim();});const rowErrors=REQUIRED.flatMap(([key,label],index)=>item[key]?[]:[`Column ${String.fromCharCode(65+index)}-Missing ${label}.`]);if(item.state&&!/^[A-Za-z]{2}$/.test(item.state))rowErrors.push('State must be a 2-letter abbreviation.');if(item.zip_code&&!/^\d{5}(?:-\d{4})?$/.test(item.zip_code))rowErrors.push('Zip Code must be 5 digits or ZIP+4.');if(item.contact_email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(item.contact_email))rowErrors.push('Contact Email is invalid.');if(rowErrors.length)errors.push({row:item.row,errors:rowErrors});else valid.push(item);});return{valid,errors};}
