/**
 * Canonical public program registry.
 * Exact published slugs only. No aliases, redirects, legacy slugs, or dedicated program application routes.
 */
export type ProgramEntry = { slug: string; name: string; category: string; formType: 'apply' | 'inquiry'; active: boolean };

export const PROGRAMS: ProgramEntry[] = [
  { slug: 'administrative-assistant', name: 'Administrative Assistant', category: 'business', formType: 'apply', active: true },
  { slug: 'automotive-technician', name: 'Automotive Technician', category: 'trades', formType: 'apply', active: true },
  { slug: 'barber-apprenticeship', name: 'Barber Apprenticeship', category: 'beauty', formType: 'apply', active: true },
  { slug: 'bookkeeping', name: 'Bookkeeping', category: 'business', formType: 'apply', active: true },
  { slug: 'building-maintenance-wrg', name: 'Building Maintenance Technician', category: 'trades', formType: 'apply', active: true },
  { slug: 'business-administration', name: 'Business Administration', category: 'business', formType: 'apply', active: true },
  { slug: 'business-startup', name: 'Business Start-Up', category: 'business', formType: 'apply', active: true },
  { slug: 'cad-drafting', name: 'CAD Drafting', category: 'technology', formType: 'apply', active: true },
  { slug: 'cdl-training', name: 'CDL Training', category: 'trades', formType: 'apply', active: true },
  { slug: 'chw-cert', name: 'Community Healthcare Worker', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'cna', name: 'Certified Nursing Assistant (CNA)', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'construction-trades-certification', name: 'Construction Trades', category: 'trades', formType: 'apply', active: true },
  { slug: 'cosmetology-apprenticeship', name: 'Cosmetology Apprenticeship', category: 'beauty', formType: 'apply', active: true },
  { slug: 'cpr-first-aid', name: 'CPR / First Aid', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'culinary-apprenticeship', name: 'Culinary Apprenticeship', category: 'apprenticeship', formType: 'apply', active: true },
  { slug: 'customer-service-representative', name: 'Customer Service Representative', category: 'business', formType: 'apply', active: true },
  { slug: 'cybersecurity-analyst', name: 'Cybersecurity Analyst', category: 'technology', formType: 'apply', active: true },
  { slug: 'data-analytics', name: 'Data Analytics', category: 'technology', formType: 'apply', active: true },
  { slug: 'dental-assistant', name: 'Dental Assistant', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'diesel-mechanic', name: 'Diesel Mechanic', category: 'trades', formType: 'apply', active: true },
  { slug: 'drug-alcohol-specimen-collector', name: 'Drug & Alcohol Specimen Collector', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'electrical', name: 'Electrical Apprenticeship', category: 'trades', formType: 'apply', active: true },
  { slug: 'emergency-health-safety', name: 'Emergency Health & Safety', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'emt-apprenticeship', name: 'Emergency Medical Technician Apprenticeship', category: 'apprenticeship', formType: 'apply', active: true },
  { slug: 'esthetician-apprenticeship', name: 'Esthetician Apprenticeship', category: 'beauty', formType: 'apply', active: true },
  { slug: 'financial-literacy', name: 'Financial Literacy', category: 'business', formType: 'apply', active: true },
  { slug: 'forklift', name: 'Forklift Operator Certification', category: 'trades', formType: 'apply', active: true },
  { slug: 'graphic-design', name: 'Graphic Design', category: 'technology', formType: 'apply', active: true },
  { slug: 'guest-service-gold', name: 'Guest Service Gold', category: 'hospitality', formType: 'apply', active: true },
  { slug: 'home-health-aide', name: 'Home Health Aide', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'hospitality', name: 'Hospitality & Service Industry', category: 'business', formType: 'apply', active: true },
  { slug: 'hvac-technician', name: 'HVAC Certification', category: 'trades', formType: 'apply', active: true },
  { slug: 'information-technology', name: 'Information Technology', category: 'technology', formType: 'apply', active: true },
  { slug: 'insurance-agent', name: 'Insurance Agent', category: 'business', formType: 'apply', active: true },
  { slug: 'it-help-desk', name: 'IT Help Desk', category: 'technology', formType: 'apply', active: true },
  { slug: 'jri-badge-1-mindsets', name: 'Badge 1: Mindsets', category: 'special', formType: 'apply', active: true },
  { slug: 'jri-badge-2-self-management', name: 'Badge 2: Self-Management', category: 'special', formType: 'apply', active: true },
  { slug: 'jri-badge-3-learning-strategies', name: 'Badge 3: Learning Strategies', category: 'special', formType: 'apply', active: true },
  { slug: 'jri-badge-4-social-skills', name: 'Badge 4: Social Skills', category: 'special', formType: 'apply', active: true },
  { slug: 'jri-badge-5-workplace-skills', name: 'Badge 5: Workplace Skills', category: 'special', formType: 'apply', active: true },
  { slug: 'jri-badge-6-launch-a-career', name: 'Badge 6: Launch a Career', category: 'special', formType: 'apply', active: true },
  { slug: 'jri-introduction', name: 'Introduction to Job Ready Indy', category: 'special', formType: 'apply', active: true },
  { slug: 'life-coach-certification-wioa', name: 'Life Coach Certification', category: 'special', formType: 'apply', active: true },
  { slug: 'manufacturing-technician', name: 'Manufacturing Technician', category: 'trades', formType: 'apply', active: true },
  { slug: 'medical-assistant', name: 'Medical Assistant', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'nail-technician-apprenticeship', name: 'Nail Technician Apprenticeship', category: 'beauty', formType: 'apply', active: true },
  { slug: 'network-administration', name: 'Network Administration', category: 'technology', formType: 'apply', active: true },
  { slug: 'network-support-technician', name: 'Network Support Technician', category: 'technology', formType: 'apply', active: true },
  { slug: 'nha-billing-coding', name: 'Medical Billing & Coding Program', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'nha-ehr', name: 'Electronic Health Records Program', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'nha-ekg-technician', name: 'EKG Technician Program', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'nha-medical-admin-assistant', name: 'Medical Administrative Assistant Program', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'nha-medical-assistant', name: 'Medical Assistant Program', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'nha-patient-care-technician', name: 'Patient Care Technician Program', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'nha-pharmacy-technician', name: 'Pharmacy Technician Program', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'nha-phlebotomy', name: 'Phlebotomy Technician Program', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'office-administration', name: 'Office Administration', category: 'business', formType: 'apply', active: true },
  { slug: 'peer-recovery-specialist', name: 'Peer Recovery Specialist', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'pharmacy-technician', name: 'Pharmacy Technician', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'phlebotomy', name: 'Phlebotomy', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'plumbing', name: 'Plumbing Apprenticeship', category: 'trades', formType: 'apply', active: true },
  { slug: 'project-management', name: 'Project Management', category: 'business', formType: 'apply', active: true },
  { slug: 'real-estate-agent', name: 'Real Estate Agent', category: 'business', formType: 'apply', active: true },
  { slug: 'sanitation-infection-control', name: 'Sanitation & Infection Control', category: 'healthcare', formType: 'apply', active: true },
  { slug: 'software-development', name: 'Software Development', category: 'technology', formType: 'apply', active: true },
  { slug: 'solar-panel-installation', name: 'Solar Panel Installation', category: 'trades', formType: 'apply', active: true },
  { slug: 'start-hospitality', name: 'START Hospitality Training', category: 'hospitality', formType: 'apply', active: true },
  { slug: 'tax-preparation', name: 'Tax Preparation', category: 'business', formType: 'apply', active: true },
  { slug: 'web-development', name: 'Web Development', category: 'technology', formType: 'apply', active: true },
  { slug: 'welding', name: 'Welding Certification', category: 'trades', formType: 'apply', active: true },
  { slug: 'youth-culinary-apprenticeship', name: 'Youth Culinary Apprenticeship', category: 'apprenticeship', formType: 'apply', active: true },
];

export const VALID_SLUGS = new Set(PROGRAMS.map((program) => program.slug));
export function resolveProgram(rawSlug: string): ProgramEntry | undefined { const slug = rawSlug.toLowerCase().trim(); return PROGRAMS.find((program) => program.slug === slug); }
export function resolveSlug(rawSlug: string): string | undefined { return resolveProgram(rawSlug)?.slug; }
export function getActivePrograms(): ProgramEntry[] { return PROGRAMS.filter((program) => program.active); }
export function getActiveProgramsByCategory(): { category: string; programs: ProgramEntry[] }[] { const grouped = new Map<string, ProgramEntry[]>(); for (const program of getActivePrograms()) { const list = grouped.get(program.category) ?? []; list.push(program); grouped.set(program.category, list); } return Array.from(grouped.entries()).map(([category, programs]) => ({ category, programs })); }
