'use client';

import React, { useState, useRef, useEffect } from 'react';
import Link from 'next/link';
import {
  Send, Bot, User, Loader2, Copy, Check, Sparkles, Paperclip,
  AlertTriangle, Database, Terminal, Zap, ChevronDown, ChevronRight,
  BookOpen, Video, FileText, PenLine, ExternalLink, Play, RefreshCw,
} from 'lucide-react';

interface EllieAction { id: string; type: string; label: string; params: Record<string, unknown>; targetCount: number; dangerLevel: 'low' | 'medium' | 'high'; description: string; }
interface Message { role: 'user' | 'assistant'; content: string; toolCalls?: { tool: string; args: Record<string, unknown>; result: string }[]; provider?: string; model?: string; action?: EllieAction | null; actionOutcome?: { status: 'executed' | 'rejected' | 'failed'; message: string }; }
interface AIChatProps { fileContext?: string; onApplyCode?: (filename: string, code: string) => void; ellieMode?: boolean; }
type ProviderId = 'auto' | 'groq' | 'openai' | 'anthropic' | 'gemini';
const MODEL_OPTIONS: Record<ProviderId, string[]> = { auto: ['auto'], groq: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant'], openai: ['gpt-4.1-mini', 'gpt-4.1', 'gpt-4o-mini'], anthropic: ['claude-sonnet-4-5', 'claude-3-5-haiku-latest'], gemini: ['gemini-2.5-flash', 'gemini-2.0-flash', 'gemini-1.5-flash'] };
const PROVIDER_LABELS: Record<ProviderId, string> = { auto: 'Auto', groq: 'Groq', openai: 'ChatGPT / OpenAI', anthropic: 'Claude / Anthropic', gemini: 'Gemini' };
export const TOOL_META: Record<string, { label: string; color: string; icon: React.ElementType<{ className?: string }> }> = {
  list_programs:{label:'Programs',color:'text-brand-blue-700',icon:Database}, list_enrollments:{label:'Enrollments',color:'text-brand-green-700',icon:Database}, get_dashboard_stats:{label:'Stats',color:'text-amber-700',icon:Zap}, get_recent_applications:{label:'Applications',color:'text-orange-700',icon:Database}, inspect_platform_registry:{label:'Platform Registry',color:'text-brand-blue-700',icon:Database}, query_program_by_slug:{label:'Program',color:'text-brand-blue-700',icon:Database}, inspect_route:{label:'Route',color:'text-slate-700',icon:Terminal}, get_component_source:{label:'Source',color:'text-slate-700',icon:Terminal}, search_schema:{label:'Schema',color:'text-brand-blue-700',icon:Database}, search_code:{label:'Code Search',color:'text-slate-700',icon:Terminal}, audit_auth_flow:{label:'Auth Audit',color:'text-red-700',icon:Database}, inspect_build_errors:{label:'Build Logs',color:'text-amber-700',icon:Terminal}, list_blueprints:{label:'Blueprints',color:'text-purple-700',icon:Database}, design_page_template:{label:'Page Template',color:'text-indigo-700',icon:Sparkles}, run_safe_command:{label:'Shell',color:'text-slate-700',icon:Terminal}, build_course:{label:'Build Course',color:'text-purple-700',icon:BookOpen}, save_course:{label:'Save Course',color:'text-brand-green-700',icon:BookOpen}, generate_videos:{label:'Generate Videos',color:'text-rose-700',icon:Video}, analyze_document:{label:'Analyze Document',color:'text-amber-700',icon:FileText}, apply_document_to_application:{label:'Apply to App',color:'text-brand-green-700',icon:PenLine}
};

interface CourseModule { title: string; lessons?: string[]; lesson_count?: number }
interface CourseDraft { title?: string; description?: string; modules?: CourseModule[]; course_id?: string; total_lessons?: number; status?: string; }
function CourseCard({ result }: { result: string }) {
  let data: CourseDraft; try { data = JSON.parse(result); } catch { return null; } if (!data.title && !data.course_id) return null;
  return <div className="mt-2 rounded-xl border border-purple-200 bg-purple-50 overflow-hidden"><div className="flex items-center gap-2 px-3 py-2 bg-purple-100 border-b border-purple-200"><BookOpen className="w-4 h-4 text-purple-700"/><span className="text-sm font-semibold text-purple-900">{data.title ?? 'Course Draft'}</span>{data.status&&<span className="ml-auto text-[10px] px-2 py-0.5 rounded-full bg-purple-200 text-purple-700 font-medium uppercase tracking-wide">{data.status}</span>}</div>{data.description&&<p className="px-3 py-2 text-xs text-slate-600 border-b border-purple-100">{data.description}</p>}{data.modules&&data.modules.length>0&&<div className="px-3 py-2 space-y-1">{data.modules.slice(0,6).map((mod,i)=><div key={i} className="flex items-start gap-2 text-xs text-slate-700"><span className="flex-shrink-0 w-5 h-5 rounded-full bg-purple-200 text-purple-800 flex items-center justify-center text-[10px] font-bold">{i+1}</span><span className="font-medium">{mod.title}</span>{(mod.lessons?.length??mod.lesson_count)&&<span className="ml-auto text-slate-400 flex-shrink-0">{mod.lessons?.length??mod.lesson_count} lessons</span>}</div>)}</div>}{(data.total_lessons||data.course_id)&&<div className="flex items-center gap-3 px-3 py-2 bg-purple-100 border-t border-purple-200 text-[11px] text-purple-700">{data.total_lessons&&<span>{data.total_lessons} total lessons</span>}{data.course_id&&<a href={`https://admin.elevateforhumanity.org/courses/${data.course_id}`} target="_blank" rel="noreferrer" className="ml-auto flex items-center gap-1 hover:underline">Open course <ExternalLink className="w-3 h-3"/></a>}</div>}</div>;
}

interface VideoJob { lesson_id?: string; title?: string; status?: string; video_url?: string; duration_s?: number }
interface VideoGenResult { jobs?: VideoJob[]; total?: number; queued?: number; completed?: number; failed?: number }
function VideoProgressCard({ result }: { result: string }) { let data: VideoGenResult; try { data=JSON.parse(result); } catch { return null; } if(!data.jobs&&!data.total)return null; const jobs=data.jobs??[]; const done=data.completed??jobs.filter(j=>j.status==='completed').length; const total=data.total??jobs.length; const pct=total>0?Math.round((done/total)*100):0; return <div className="mt-2 rounded-xl border border-rose-200 bg-rose-50 overflow-hidden"><div className="flex items-center gap-2 px-3 py-2 bg-rose-100 border-b border-rose-200"><Video className="w-4 h-4 text-rose-700"/><span className="text-sm font-semibold text-rose-900">Video Generation</span><span className="ml-auto text-xs text-rose-700">{done}/{total} complete</span></div><div className="px-3 py-2"><div className="w-full bg-rose-200 rounded-full h-1.5 mb-2"><div className="bg-rose-600 h-1.5 rounded-full transition-all" style={{width:`${pct}%`}}/></div>{jobs.slice(0,8).map((job,i)=><div key={i} className="flex items-center gap-2 text-xs">{job.status==='completed'?<span className="w-3.5 h-3.5 rounded-full bg-brand-green-600 inline-block"/>:job.status==='failed'?<AlertTriangle className="w-3.5 h-3.5 text-red-500"/>:<Loader2 className="w-3.5 h-3.5 text-rose-500 animate-spin"/>}<span className="text-slate-700 truncate flex-1">{job.title??job.lesson_id??`Job ${i+1}`}</span>{job.video_url&&<a href={job.video_url} target="_blank" rel="noreferrer" className="text-rose-600 hover:underline">Play</a>}</div>)}</div></div>; }

export default function AIChat({ fileContext, onApplyCode, ellieMode=false }: AIChatProps) {
  const [messages,setMessages]=useState<Message[]>([]); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [provider,setProvider]=useState<ProviderId>('auto'); const [model,setModel]=useState('auto'); const endRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'});},[messages]);
  async function send(){ if(!input.trim()||loading)return; const text=input; setInput(''); setMessages(m=>[...m,{role:'user',content:text}]); setLoading(true); try { const endpoint=ellieMode?'/api/admin/ai-assistant':'/api/admin/dev-studio/ai/chat'; const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,messages,fileContext,provider,model})}); const data=await res.json(); setMessages(m=>[...m,{role:'assistant',content:data.reply??data.message??'No response',provider:data.provider,model:data.model,action:data.action??null}]); } catch(error){ setMessages(m=>[...m,{role:'assistant',content:error instanceof Error?error.message:'Request failed'}]); } finally { setLoading(false); } }
  return <div className="flex h-full flex-col"><div className="flex items-center gap-2 border-b p-3"><Bot className="h-5 w-5"/><select value={provider} onChange={e=>{const p=e.target.value as ProviderId;setProvider(p);setModel(MODEL_OPTIONS[p][0]);}}>{Object.entries(PROVIDER_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={model} onChange={e=>setModel(e.target.value)}>{MODEL_OPTIONS[provider].map(m=><option key={m}>{m}</option>)}</select></div><div className="flex-1 overflow-y-auto p-3 space-y-3">{messages.map((m,i)=><div key={i} className={m.role==='user'?'text-right':'text-left'}><div className="inline-block max-w-[90%] rounded-xl bg-slate-100 p-3 text-sm">{m.content}</div></div>)}<div ref={endRef}/></div><div className="border-t p-3 flex gap-2"><textarea value={input} onChange={e=>setInput(e.target.value)} className="flex-1 rounded-lg border p-2"/><button onClick={send} disabled={loading} className="rounded-lg bg-slate-900 px-3 text-white">{loading?<Loader2 className="animate-spin"/>:<Send/>}</button></div></div>;
}