services:
  asterisk:
    image: mlan/asterisk:xtra-1.1.13
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./asterisk:/etc/asterisk:ro
      - asterisk-data:/var/lib/asterisk
      - asterisk-logs:/var/log/asterisk
volumes:
  asterisk-data:
  asterisk-logs:
