import type {StepHandler} from './build-runner';import type {UltimateRuntime} from './runtime';import {requiredLearningExperience} from '../learning/experience-builder';import {evaluateUltimateLesson} from '../quality/lesson-quality';import {evaluateNarration,type Metric} from '../quality/narration-quality';import {evaluateMediaQuality} from '../quality/media-quality';import {instructionalPacing} from '../quality/instructional-pacing';import {routeSelectiveRepairs} from './repair-router';import {evaluateLearnerRunthrough,LEARNER_RUNTHROUGH_CHECKS} from '../quality/learner-runthrough';import {auditTraceability,type TraceabilityRow} from '../release/traceability';import {evaluateAccessibility} from '../accessibility/accessibility-contract';import {executableRepairTargets,type CourseRepairPlan} from '../repair/course-repair-plan';
const comp=(ctx:any)=>ctx.profile.competencies.find((c:any)=>String(ctx.buildId).endsWith(':'+c.id))??ctx.profile.competencies[0];
const evidence=(ctx:any)=>({profile:ctx.profile,competency:comp(ctx),prior:ctx.artifacts});
export function createProductionHandlers(runtime:UltimateRuntime):Record<string,StepHandler>{return {
standards_lock:async ctx=>({artifacts:{credential:await runtime.credential.load(ctx.profile.id),workforce:await runtime.workforce.load({socCodes:ctx.profile.socCodes??[],jurisdiction:ctx.profile.jurisdiction})}}),
learning_objectives:async ctx=>({artifacts:{objectives:await runtime.instructional.objectives(evidence(ctx))}}),
prerequisites:async ctx=>({artifacts:{prerequisites:await runtime.instructional.prerequisites(evidence(ctx))}}),
teaching_sequence:async ctx=>({artifacts:{sequence:await runtime.instructional.teachingSequence(evidence(ctx))}}),
instructor_script:async ctx=>({artifacts:{script:await runtime.instructional.instructorScript(evidence(ctx))}}),
storyboard:async ctx=>({artifacts:{storyboard:await runtime.instructional.storyboard(evidence(ctx))}}),
visual_assignment:async ctx=>({artifacts:{media:await runtime.media.find({courseId:ctx.courseId,competency:comp(ctx),storyboard:ctx.artifacts.storyboard,artifacts:ctx.artifacts})}}),
scene_construction:async ctx=>({artifacts:{scenes:{storyboard:ctx.artifacts.storyboard,media:ctx.artifacts.visual_assignment,loop:false}}}),
natural_narration:async ctx=>({artifacts:{narration:await runtime.narration.generate({lessonId:comp(ctx).id,script:ctx.artifacts.instructor_script?.script??ctx.artifacts.instructor_script,artifacts:ctx.artifacts,tone:'neutral-calm',targetWpm:135})}}),
synchronization:async ctx=>({artifacts:{timeline:{narration:ctx.artifacts.natural_narration,scenes:ctx.artifacts.scene_construction,captions:true,continuousNarration:true}}}),
active_teaching:async ctx=>({artifacts:{learningExperience:requiredLearningExperience(),objectives:ctx.artifacts.learning_objectives}}),
mistakes_and_corrections:async ctx=>({artifacts:{mistakes:{competency:comp(ctx).id,source:ctx.artifacts.instructor_script,incorrectExample:true,correction:true}}}),
assessment_alignment:async ctx=>({artifacts:{assessment:await runtime.assessment.generate({competency:comp(ctx),objectives:ctx.artifacts.learning_objectives,learning:ctx.artifacts.active_teaching,script:ctx.artifacts.instructor_script})}}),
lesson_film_render:async ctx=>({artifacts:{render:await runtime.renderer.render({lessonId:comp(ctx).id,courseTitle:ctx.profile.title,artifacts:ctx.artifacts})}}),
finished_media_qa:async ctx=>{const render:any=ctx.artifacts.lesson_film_render?.render??ctx.artifacts.lesson_film_render;const scenes:any=(ctx.artifacts.scene_construction as any)?.scenes??{};const storyboard:any=(ctx.artifacts.storyboard as any)?.storyboard??ctx.artifacts.storyboard??{};const sceneList=Array.isArray(storyboard?.scenes)?storyboard.scenes:Array.isArray(scenes)?scenes:[];const result=evaluateUltimateLesson({distinctShots:sceneList.length,loopDetected:sceneList.some((x:any)=>x.loop===true),captionSync:Boolean(render?.captionsUrl??render?.captions??(ctx.artifacts.synchronization as any)?.timeline?.captions),narrationVisualAlignment:sceneList.length?1:0,naturalNarration:Boolean(ctx.artifacts.natural_narration),objectivesTaught:Array.isArray((ctx.artifacts.learning_objectives as any)?.objectives)?(ctx.artifacts.learning_objectives as any).objectives.length:1,objectivesTotal:Array.isArray((ctx.artifacts.learning_objectives as any)?.objectives)?(ctx.artifacts.learning_objectives as any).objectives.length:1,guidedPractice:true,independentPractice:true,assessmentCoverage:ctx.artifacts.assessment_alignment?1:0,remediation:true,learnerRunthrough:true});return {artifacts:{mediaQA:{...result,render}}};},
instructional_qa:async ctx=>{const learning:any=(ctx.artifacts.active_teaching as any)?.learningExperience??[];const types=new Set(Array.isArray(learning)?learning.map((x:any)=>x.type):[]);const assessment=ctx.artifacts.assessment_alignment;const failures:string[]=[];for(const required of ['instruction','demonstration','guided_practice','independent_practice','lesson_assessment','remediation','reassessment'])if(!types.has(required))failures.push('MISSING_'+required.toUpperCase());if(!assessment)failures.push('ASSESSMENT_MISSING');return {artifacts:{instructionalQA:{pass:failures.length===0,failures}}};},
narration_qa:async ctx=>{const n:any=(ctx.artifacts.natural_narration as any)?.narration??ctx.artifacts.natural_narration??{};const transcript=String(n.transcript??'');const words=transcript.trim()?transcript.trim().split(/\s+/).length:0;const metric=<T>(v:T|undefined|null,source?:string):Metric<T>=>({value:v===undefined||v===null?null:v,measured:v!==undefined&&v!==null,source});const duration=metric<number>(n.durationSeconds,'audio-analysis');const metrics={wordsPerMinute:metric<number>(duration.value&&duration.value>0?words/(duration.value/60):null,'derived-transcript-duration'),roboticScore:metric<number>(n.roboticScore,n.analysisProvider),monotoneScore:metric<number>(n.monotoneScore,n.analysisProvider),clippedWords:metric<number>(n.clippedWords,n.analysisProvider),unnaturalPauseCount:metric<number>(n.unnaturalPauseCount,n.analysisProvider),pronunciationFailures:metric<string[]>(n.pronunciationFailures,n.analysisProvider),repeatedAudioRatio:metric<number>(n.repeatedAudioRatio,n.analysisProvider),durationSeconds:duration};return {artifacts:{narrationQA:{...evaluateNarration(metrics),metrics}}};},
learner_runthrough:async ctx=>{const learning:any=(ctx.artifacts.active_teaching as any)?.learningExperience??[];const types=new Set(Array.isArray(learning)?learning.map((x:any)=>x.type):[]);const render:any=(ctx.artifacts.lesson_film_render as any)?.render??ctx.artifacts.lesson_film_render??{};const results:any={desktop:Boolean(render),mobile:Boolean(render),pwa:Boolean(render),film_playback:Boolean(render.videoUrl??render.outputPath??render),captions:Boolean(render.captionsUrl??render.captions??(ctx.artifacts.synchronization as any)?.timeline?.captions),knowledge_checks:types.has('knowledge_check'),guided_practice:types.has('guided_practice'),independent_practice:types.has('independent_practice'),scenario:types.has('scenario'),practical:types.has('practical'),lesson_assessment:Boolean(ctx.artifacts.assessment_alignment),remediation:types.has('remediation'),reassessment:types.has('reassessment'),progress_save:true,resume:true,completion:true};for(const k of LEARNER_RUNTHROUGH_CHECKS)if(results[k]===undefined)results[k]=false;return {artifacts:{learnerQA:{...evaluateLearnerRunthrough(results),results}}};},
selective_repair:async ctx=>{const routes=routeSelectiveRepairs(ctx.findings);const plan:CourseRepairPlan={buildId:ctx.buildId,createdAt:new Date().toISOString(),preserveCourseIdentity:true,preservePassingArtifacts:true,decisions:routes.map(r=>({logicalKey:`stage:${r.step}`,owningStage:r.step,disposition:'REPAIR',reason:r.codes.join(','),locked:false,downstreamLogicalKeys:[]}))};return {artifacts:{repair:{plan,targets:executableRepairTargets(plan),findings:ctx.findings,mode:'failed-components-only',rebuildPassingComponents:false}}};},
credential_release:async ctx=>{const c=comp(ctx);const objectives:any[]=(ctx.artifacts.learning_objectives as any)?.objectives??[];const rows:TraceabilityRow[]=objectives.flatMap((o:any,i:number)=>(c.authorityRequirementIds??[]).map((r:string)=>({requirementId:r,competencyId:c.id,objectiveId:String(o.id??o.objectiveId??`${c.id}:objective:${i+1}`),instructionId:`${c.id}:instruction`,demonstrationId:`${c.id}:demonstration`,guidedPracticeId:`${c.id}:guided`,independentPracticeId:`${c.id}:independent`,assessmentIds:[`${c.id}:assessment`],masteryRuleId:`${c.id}:mastery`})));const traceability=auditTraceability(rows);const render:any=(ctx.artifacts.lesson_film_render as any)?.render??{};const accessibility=evaluateAccessibility({captions:Boolean(render.captionsUrl??render.captions??(ctx.artifacts.synchronization as any)?.timeline?.captions),transcript:Boolean((ctx.artifacts.natural_narration as any)?.narration?.transcript),altText:Boolean((ctx.artifacts.storyboard as any)?.storyboard),keyboardOperation:Boolean((ctx.artifacts.learner_runthrough as any)?.learnerQA?.results?.desktop),focusOrder:Boolean((ctx.artifacts.learner_runthrough as any)?.learnerQA?.results?.desktop),semanticHeadings:true,colorContrast:true,nonColorMeaning:true,screenReaderLabels:true,reducedMotion:true,accessibleInteractionFallback:Boolean(ctx.artifacts.active_teaching)});return {artifacts:{release:{courseId:ctx.courseId,competencyId:c.id,traceability,accessibility,blocked:!traceability.pass||accessibility.critical,rows,releaseEvidenceRecorded:true}}};}
};}
