/**
 * lib/curriculum/blueprints/entrepreneurship.ts
 *
 * Canonical Entrepreneurship & Small Business course blueprint.
 * Alignment target: Certiport Entrepreneurship and Small Business (ESB) U.S. v.2.
 *
 * This is original Elevate instructional content architecture. It does not copy,
 * reproduce, or embed CCI Learning/XED/GMetrix proprietary course content.
 */
import type { CredentialBlueprint } from './types';

const lesson = (
  slug: string,
  title: string,
  order: number,
  domainKey: string,
  learningObjectives: string[],
  durationMinutes = 45,
) => ({
  slug,
  title,
  order,
  domainKey,
  learningObjectives,
  durationMinutes,
});

export const entrepreneurshipBlueprint: CredentialBlueprint = {
  id: 'entrepreneurship-esb-v2-us',
  version: '2.0.0',
  title: 'Entrepreneurship & Small Business — ESB U.S. v.2',
  credentialSlug: 'certiport-esb-v2-us',
  credentialTitle: 'Entrepreneurship and Small Business (ESB) U.S. v.2',
  credentialCode: 'ESB-V2-US',
  sourceAuthority: 'Certiport, a Pearson VUE business',
  sourceReference: 'Entrepreneurship and Small Business certification objective domains and ESB v.2 transition guidance',
  effectiveDate: '2026-07-01',
  state: 'US',
  programSlug: 'entrepreneurship',
  programType: 'workforce',
  targetRole: 'Entrepreneur / Small Business Owner',
  status: 'active',
  socCode: '11-1021.00',
  trackVariants: ['esb-v2-us'],
  certiportExamCodes: ['ESB-V2-US', 'ESB'],
  skipLqs: true,

  certificationPathway: {
    certificationBodyId: 'certiport',
    certificationName: 'Entrepreneurship and Small Business (ESB) U.S. v.2',
    examCode: 'ESB-V2-US',
  },

  externalCourses: [
    {
      title: 'Certiport ESB Certification Information',
      provider: 'Certiport / Pearson VUE',
      url: 'https://certiport.pearsonvue.com/Certifications/ESB/Certification/Certify',
      required: false,
      notes: 'Use for official exam information and current Certiport policies. Elevate course content is independently authored.',
    },
  ],

  generationRules: {
    allowRemediation: true,
    allowExpansionLessons: false,
    maxTotalLessons: 36,
    requiresFinalExam: true,
    requiresUniversalReview: false,
    generatorMode: 'fixed',
    minModules: 5,
    maxModules: 5,
    minLessonsPerModule: 5,
    maxLessonsPerModule: 9,
    requireCheckpointPerModule: true,
    requireFinalExam: true,
    passingScore: 80,
    allowedLessonTypes: ['orientation', 'lesson', 'concept', 'scenario', 'practical', 'assignment', 'checkpoint', 'exam'],
  },

  expectedModuleCount: 5,
  expectedLessonCount: 35,

  finalExam: {
    questionCount: 50,
    passingScore: 80,
    domainDistribution: {
      entrepreneurial_small_business_concepts: 35,
      marketing_sales: 25,
      production_distribution: 20,
      business_financials: 20,
    },
  },

  certificateRequirements: {
    includeHours: true,
    includeCompetencies: true,
    includeInstructorVerification: false,
    includeCompletionDate: true,
    includeVerificationUrl: true,
    requireAllCriticalCompetencies: true,
  },

  videoConfig: {
    videoGenerator: 'canvas-slides',
    template: 'elevate-slide',
    instructorName: 'Elevate Business Instructor',
    instructorTitle: 'Entrepreneurship & Small Business Instructor',
    instructorImagePath: '/images/instructors/business-coach.jpg',
    brandName: 'Elevate for Humanity',
    logoPath: '/images/logo.png',
    captions: true,
    backgroundMusic: false,
    ttsVoice: 'nova',
    ttsSpeed: 1.0,
    slideCount: 6,
    segments: ['intro', 'concept', 'example', 'application', 'knowledge-check', 'wrapup'],
    width: 1920,
    height: 1080,
  },

  assessmentRules: [
    {
      assessmentType: 'module',
      scope: 'all',
      minQuestions: 10,
      maxQuestions: 15,
      passingThreshold: 0.8,
    },
    {
      assessmentType: 'final',
      scope: 'all',
      minQuestions: 50,
      maxQuestions: 50,
      passingThreshold: 0.8,
    },
  ],

  modules: [
    {
      slug: 'esb-v2-entrepreneurial-small-business-concepts',
      title: 'Domain 1 — Entrepreneurial & Small Business Concepts',
      description: 'Foundational entrepreneurship concepts, business ownership, entrepreneurial mindset, opportunity recognition, business planning, design thinking, and intellectual property.',
      orderIndex: 1,
      domainKey: 'entrepreneurial_small_business_concepts',
      minLessons: 9,
      maxLessons: 9,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      requiredLessonTypes: [
        { lessonType: 'orientation', requiredCount: 1 },
        { lessonType: 'lesson', requiredCount: 6 },
        { lessonType: 'practical', requiredCount: 1 },
        { lessonType: 'checkpoint', requiredCount: 1 },
      ],
      competencies: [
        { competencyKey: 'esb_1_1_foundations', domainKey: 'entrepreneurial_small_business_concepts', isCritical: true, minimumTouchpoints: 3, assessmentMethod: 'quiz' },
        { competencyKey: 'esb_1_2_entrepreneur_knowledge_skills', domainKey: 'entrepreneurial_small_business_concepts', isCritical: true, minimumTouchpoints: 2, assessmentMethod: 'quiz' },
        { competencyKey: 'esb_1_3_opportunity_recognition', domainKey: 'entrepreneurial_small_business_concepts', isCritical: true, minimumTouchpoints: 2, assessmentMethod: 'assignment' },
        { competencyKey: 'esb_1_4_business_plan', domainKey: 'entrepreneurial_small_business_concepts', isCritical: true, minimumTouchpoints: 2, assessmentMethod: 'assignment' },
        { competencyKey: 'esb_1_5_intellectual_property', domainKey: 'entrepreneurial_small_business_concepts', isCritical: true, minimumTouchpoints: 1, assessmentMethod: 'quiz' },
      ],
      interactionSpecs: {
        includeKnowledgeChecks: true,
        knowledgeCheckCount: 12,
        includeScenarios: true,
        scenarioCount: 3,
        includeFlashcards: true,
        flashcardCount: 18,
        includeMatching: true,
        matchingCount: 2,
        includeCaseStudies: true,
        caseStudyCount: 2,
      },
      suggestedLessonSkeleton: [
        'ESB v2 Orientation and Entrepreneurial Foundations',
        'Business Types, Legal Structures, Roles, and Compensation',
        'Business Life Cycle and Design Thinking',
        'Entrepreneurial Mindset: Risks, Benefits, and Opportunity',
        'Recognizing and Testing Business Opportunities',
        'Business Plans, Pitch Decks, and Lean Canvas',
        'Intellectual Property and Licensed Materials',
        'Practical: Build Your Venture Concept',
        'Domain 1 Checkpoint',
      ],
      lessons: [
        lesson('esb-v2-orientation', 'ESB v2 Orientation and Entrepreneurial Foundations', 1, 'entrepreneurial_small_business_concepts', [
          'Define entrepreneurship and small business.',
          'Explain how the ESB v2 domains connect to starting and operating a venture.',
          'Distinguish entrepreneurship from ordinary employment and self-employment scenarios.',
        ], 50),
        lesson('esb-v2-business-types-structures', 'Business Types, Legal Structures, Roles, and Compensation', 2, 'entrepreneurial_small_business_concepts', [
          'Classify common types of businesses.',
          'Compare sole proprietorships, partnerships, LLCs, and corporations at a foundational level.',
          'Identify business roles, responsibilities, and common compensation structures.',
        ], 60),
        lesson('esb-v2-lifecycle-design-thinking', 'Business Life Cycle and Design Thinking', 3, 'entrepreneurial_small_business_concepts', [
          'Identify stages of a business life cycle.',
          'Recognize core elements of the design-thinking process.',
          'Apply customer-focused problem solving to an early venture idea.',
        ], 50),
        lesson('esb-v2-entrepreneurial-mindset', 'Entrepreneurial Mindset: Risks, Benefits, and Opportunity', 4, 'entrepreneurial_small_business_concepts', [
          'Identify characteristics of an entrepreneurial mindset.',
          'Evaluate common risks, benefits, opportunities, and drawbacks of entrepreneurship.',
          'Select appropriate responses to uncertainty using scenario-based reasoning.',
        ], 50),
        lesson('esb-v2-opportunity-viability', 'Recognizing and Testing Business Opportunities', 5, 'entrepreneurial_small_business_concepts', [
          'Identify characteristics of a viable business opportunity.',
          'Evaluate demand, customer problems, competition, and feasibility.',
          'Use evidence to decide whether to proceed, pivot, or stop.',
        ], 60),
        lesson('esb-v2-business-plan-pitch-lean', 'Business Plans, Pitch Decks, and Lean Canvas', 6, 'entrepreneurial_small_business_concepts', [
          'Explain the purpose and value of a business plan, pitch deck, and lean canvas.',
          'Identify the key components of a business plan and pitch deck.',
          'Select the right planning artifact for a given business situation.',
        ], 65),
        lesson('esb-v2-intellectual-property', 'Intellectual Property and Licensed Materials', 7, 'entrepreneurial_small_business_concepts', [
          'Differentiate trademarks, trade secrets, copyrights, and patents.',
          'Identify business risks associated with improper use of protected or licensed materials.',
          'Apply basic intellectual-property concepts to realistic small-business scenarios.',
        ], 50),
        lesson('esb-v2-venture-concept-lab', 'Practical: Build Your Venture Concept', 8, 'entrepreneurial_small_business_concepts', [
          'Write a concise customer problem statement and value proposition.',
          'Select a legal structure for a hypothetical venture and justify the choice.',
          'Produce a one-page lean canvas or venture concept summary.',
        ], 90),
        lesson('esb-v2-domain-1-checkpoint', 'Domain 1 Checkpoint — Entrepreneurial & Small Business Concepts', 9, 'entrepreneurial_small_business_concepts', [
          'Demonstrate readiness across ESB v2 Domain 1 concepts.',
          'Identify weak objectives requiring remediation.',
        ], 40),
      ],
    },

    {
      slug: 'esb-v2-marketing-sales',
      title: 'Domain 2 — Marketing & Sales',
      description: 'Market research, customer value, pricing, competition, SWOT, marketing processes, acquisition economics, sales channels, and customer service.',
      orderIndex: 2,
      domainKey: 'marketing_sales',
      minLessons: 7,
      maxLessons: 7,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      requiredLessonTypes: [
        { lessonType: 'lesson', requiredCount: 5 },
        { lessonType: 'practical', requiredCount: 1 },
        { lessonType: 'checkpoint', requiredCount: 1 },
      ],
      competencies: [
        { competencyKey: 'esb_2_1_market_research', domainKey: 'marketing_sales', isCritical: true, minimumTouchpoints: 3, assessmentMethod: 'assignment' },
        { competencyKey: 'esb_2_2_marketing_processes', domainKey: 'marketing_sales', isCritical: true, minimumTouchpoints: 3, assessmentMethod: 'quiz' },
        { competencyKey: 'esb_2_3_sales_channels', domainKey: 'marketing_sales', isCritical: true, minimumTouchpoints: 2, assessmentMethod: 'quiz' },
      ],
      interactionSpecs: {
        includeKnowledgeChecks: true,
        knowledgeCheckCount: 10,
        includeScenarios: true,
        scenarioCount: 4,
        includeDragDrop: true,
        includeMatching: true,
        matchingCount: 2,
        includeSimulations: true,
        simulationCount: 1,
      },
      suggestedLessonSkeleton: [
        'Target Market, Value Proposition, and Pricing',
        'Market Research and Data',
        'Competition and SWOT Analysis',
        'Marketing Platforms, Methods, and the Marketing Plan',
        'Sales Data, Customer Acquisition, and Retention',
        'Sales Channels, Sales Process, and Customer Support',
        'Domain 2 Checkpoint',
      ],
      lessons: [
        lesson('esb-v2-target-market-value-pricing', 'Target Market, Value Proposition, and Pricing', 1, 'marketing_sales', [
          'Define target market, value proposition, and pricing.',
          'Connect customer needs to a differentiated value proposition.',
          'Recognize pricing decisions that fit a target customer and business model.',
        ], 55),
        lesson('esb-v2-market-research-data', 'Market Research and Data', 2, 'marketing_sales', [
          'Distinguish primary from secondary data.',
          'Select appropriate research methods for a business question.',
          'Interpret basic market-research findings for decision making.',
        ], 55),
        lesson('esb-v2-competition-swot', 'Competition and SWOT Analysis', 3, 'marketing_sales', [
          'Evaluate direct and indirect competitors.',
          'Complete a SWOT analysis.',
          'Use competitive findings to adjust positioning.',
        ], 60),
        lesson('esb-v2-marketing-process-plan', 'Marketing Platforms, Methods, and the Marketing Plan', 4, 'marketing_sales', [
          'Identify appropriate digital and traditional marketing platforms.',
          'Apply common marketing methods to business scenarios.',
          'Identify the major elements of a marketing plan.',
        ], 60),
        lesson('esb-v2-sales-data-cac-retention', 'Sales Data, Customer Acquisition, and Retention', 5, 'marketing_sales', [
          'Analyze basic market reactions and sales data.',
          'Explain customer acquisition cost and retention cost concepts.',
          'Use simple performance data to recommend marketing adjustments.',
        ], 65),
        lesson('esb-v2-sales-channels-process-support', 'Practical: Sales Channels, Sales Process, and Customer Support', 6, 'marketing_sales', [
          'Identify the stages of a basic sales process.',
          'Compare digital and physical sales channels.',
          'Explain how customer service and support influence sales and retention.',
          'Design a simple channel and customer-support strategy for a venture.',
        ], 80),
        lesson('esb-v2-domain-2-checkpoint', 'Domain 2 Checkpoint — Marketing & Sales', 7, 'marketing_sales', [
          'Demonstrate readiness across ESB v2 Domain 2 concepts.',
          'Use assessment feedback to target remediation.',
        ], 40),
      ],
    },

    {
      slug: 'esb-v2-production-distribution',
      title: 'Domain 3 — Production & Distribution',
      description: 'Minimum viable product, product/market fit, quality standards, production options, supply chains, regulatory considerations, and distribution strategies.',
      orderIndex: 3,
      domainKey: 'production_distribution',
      minLessons: 6,
      maxLessons: 6,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      requiredLessonTypes: [
        { lessonType: 'lesson', requiredCount: 4 },
        { lessonType: 'practical', requiredCount: 1 },
        { lessonType: 'checkpoint', requiredCount: 1 },
      ],
      competencies: [
        { competencyKey: 'esb_3_1_mvp', domainKey: 'production_distribution', isCritical: true, minimumTouchpoints: 2, assessmentMethod: 'assignment' },
        { competencyKey: 'esb_3_2_supply_chain_production', domainKey: 'production_distribution', isCritical: true, minimumTouchpoints: 3, assessmentMethod: 'quiz' },
        { competencyKey: 'esb_3_3_distribution', domainKey: 'production_distribution', isCritical: true, minimumTouchpoints: 2, assessmentMethod: 'assignment' },
      ],
      interactionSpecs: {
        includeKnowledgeChecks: true,
        knowledgeCheckCount: 8,
        includeScenarios: true,
        scenarioCount: 3,
        includeCaseStudies: true,
        caseStudyCount: 2,
        includeDecisionTrees: true,
        decisionTreeCount: 1,
      },
      suggestedLessonSkeleton: [
        'Minimum Viable Product and Product/Market Fit',
        'Performance and Quality Criteria',
        'Production Inputs and Production Options',
        'Quality Control, Regulation, and Safety',
        'Practical: Distribution and Fulfillment Strategy',
        'Domain 3 Checkpoint',
      ],
      lessons: [
        lesson('esb-v2-mvp-product-market-fit', 'Minimum Viable Product and Product/Market Fit', 1, 'production_distribution', [
          'Explain the value of a minimum viable product.',
          'Define elements of a product/market fit hypothesis.',
          'Use customer evidence to refine a product or service concept.',
        ], 60),
        lesson('esb-v2-performance-quality', 'Performance and Quality Criteria', 2, 'production_distribution', [
          'Define performance and quality criteria for products and services.',
          'Differentiate customer expectations from measurable quality standards.',
          'Create simple acceptance criteria for an MVP.',
        ], 50),
        lesson('esb-v2-production-inputs-options', 'Production Inputs and Production Options', 3, 'production_distribution', [
          'Identify knowledge, labor, technology, and materials required to create an offering.',
          'Compare production options for digital products, physical products, and services.',
          'Identify make-versus-buy and capacity considerations at a foundational level.',
        ], 60),
        lesson('esb-v2-quality-regulatory-safety', 'Quality Control, Regulation, and Safety', 4, 'production_distribution', [
          'Identify quality-control testing approaches for products and services.',
          'Recognize when government regulatory or safety requirements affect production.',
          'Apply quality-control concepts to realistic business scenarios.',
        ], 60),
        lesson('esb-v2-distribution-fulfillment-lab', 'Practical: Distribution and Fulfillment Strategy', 5, 'production_distribution', [
          'Identify factors used to select distribution channels.',
          'Differentiate direct distribution from third-party fulfillment services.',
          'Design a distribution and fulfillment approach for a sample venture.',
        ], 80),
        lesson('esb-v2-domain-3-checkpoint', 'Domain 3 Checkpoint — Production & Distribution', 6, 'production_distribution', [
          'Demonstrate readiness across ESB v2 Domain 3 concepts.',
          'Use missed objectives to create a remediation plan.',
        ], 40),
      ],
    },

    {
      slug: 'esb-v2-business-financials',
      title: 'Domain 4 — Business Financials & Funding',
      description: 'Pricing, financial statements, costs, cash flow, ROI, budgets, startup costs, funding options, and funding readiness.',
      orderIndex: 4,
      domainKey: 'business_financials',
      minLessons: 7,
      maxLessons: 7,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      requiredLessonTypes: [
        { lessonType: 'lesson', requiredCount: 5 },
        { lessonType: 'practical', requiredCount: 1 },
        { lessonType: 'checkpoint', requiredCount: 1 },
      ],
      competencies: [
        { competencyKey: 'esb_4_1_business_financials', domainKey: 'business_financials', isCritical: true, minimumTouchpoints: 4, assessmentMethod: 'quiz' },
        { competencyKey: 'esb_4_2_funding_options', domainKey: 'business_financials', isCritical: true, minimumTouchpoints: 3, assessmentMethod: 'assignment' },
      ],
      interactionSpecs: {
        includeKnowledgeChecks: true,
        knowledgeCheckCount: 12,
        includeScenarios: true,
        scenarioCount: 4,
        includeSimulations: true,
        simulationCount: 2,
        includeCaseStudies: true,
        caseStudyCount: 2,
      },
      suggestedLessonSkeleton: [
        'Selling Price and Unit Economics',
        'Income Statement and Balance Sheet Basics',
        'Fixed Costs, Variable Costs, and Break-Even Thinking',
        'Cash Flow and Working Capital',
        'Return on Investment',
        'Practical: Startup Budget and Funding Readiness',
        'Domain 4 Checkpoint',
      ],
      lessons: [
        lesson('esb-v2-selling-price-unit-economics', 'Selling Price and Unit Economics', 1, 'business_financials', [
          'Determine a selling price using cost, margin, competition, and customer-value considerations.',
          'Recognize the relationship among revenue, cost, and gross profit.',
          'Solve foundational pricing scenarios.',
        ], 60),
        lesson('esb-v2-financial-statements', 'Income Statement and Balance Sheet Basics', 2, 'business_financials', [
          'Interpret basic income-statement information.',
          'Interpret basic balance-sheet information.',
          'Use financial statements to answer simple business questions.',
        ], 60),
        lesson('esb-v2-fixed-variable-breakeven', 'Fixed Costs, Variable Costs, and Break-Even Thinking', 3, 'business_financials', [
          'Differentiate fixed and variable costs.',
          'Classify business expenses correctly.',
          'Use cost behavior to reason about break-even and pricing.',
        ], 60),
        lesson('esb-v2-cash-flow', 'Cash Flow and Working Capital', 4, 'business_financials', [
          'Analyze a simple cash-flow scenario.',
          'Explain why profitable businesses can still experience cash shortages.',
          'Identify practical actions that improve cash-flow management.',
        ], 60),
        lesson('esb-v2-roi', 'Return on Investment', 5, 'business_financials', [
          'Calculate a simple return on investment.',
          'Compare investment alternatives using ROI and business context.',
          'Identify limitations of relying on one financial metric.',
        ], 55),
        lesson('esb-v2-startup-budget-funding', 'Practical: Startup Budget and Funding Readiness', 6, 'business_financials', [
          'Determine a basic operating budget and startup costs.',
          'Identify bootstrapping, debt, grants, crowdfunding, angel, and equity funding concepts.',
          'Identify common requirements lenders or investors may evaluate.',
          'Prepare a simple sources-and-uses funding plan.',
        ], 90),
        lesson('esb-v2-domain-4-checkpoint', 'Domain 4 Checkpoint — Business Financials & Funding', 7, 'business_financials', [
          'Demonstrate readiness across ESB v2 Domain 4 concepts.',
          'Prioritize financial topics requiring remediation.',
        ], 45),
      ],
    },

    {
      slug: 'esb-v2-capstone-exam-readiness',
      title: 'Capstone — Business Launch & ESB v2 Exam Readiness',
      description: 'Integrates all four ESB v2 domains through a venture capstone, cumulative review, practice assessment, remediation, and final course exam.',
      orderIndex: 5,
      domainKey: 'capstone_exam_readiness',
      minLessons: 6,
      maxLessons: 6,
      quizRequired: true,
      practicalRequired: true,
      isCritical: true,
      requiredLessonTypes: [
        { lessonType: 'practical', requiredCount: 2 },
        { lessonType: 'lesson', requiredCount: 1 },
        { lessonType: 'checkpoint', requiredCount: 2 },
        { lessonType: 'exam', requiredCount: 1 },
      ],
      competencies: [
        { competencyKey: 'esb_integrated_business_model', domainKey: 'capstone_exam_readiness', isCritical: true, minimumTouchpoints: 2, assessmentMethod: 'assignment' },
        { competencyKey: 'esb_pitch_readiness', domainKey: 'capstone_exam_readiness', isCritical: true, minimumTouchpoints: 1, assessmentMethod: 'observation' },
        { competencyKey: 'esb_exam_readiness', domainKey: 'capstone_exam_readiness', isCritical: true, minimumTouchpoints: 3, assessmentMethod: 'exam' },
      ],
      interactionSpecs: {
        includeKnowledgeChecks: true,
        knowledgeCheckCount: 16,
        includeScenarios: true,
        scenarioCount: 6,
        includeCaseStudies: true,
        caseStudyCount: 3,
        includeSimulations: true,
        simulationCount: 2,
      },
      suggestedLessonSkeleton: [
        'Capstone: Build the Business Model',
        'Capstone: Marketing, Operations, and Financial Plan',
        'Pitch Lab and Business Launch Readiness',
        'Cumulative ESB v2 Review',
        'Practice Exam and Remediation',
        'Final Course Exam',
      ],
      lessons: [
        lesson('esb-v2-capstone-business-model', 'Capstone: Build the Business Model', 1, 'capstone_exam_readiness', [
          'Integrate opportunity, customer, value proposition, ownership, and business-plan concepts.',
          'Create a coherent one-page venture model.',
          'Document major assumptions requiring validation.',
        ], 100),
        lesson('esb-v2-capstone-go-to-market-financial', 'Capstone: Marketing, Operations, and Financial Plan', 2, 'capstone_exam_readiness', [
          'Create a concise go-to-market plan.',
          'Define production and distribution decisions for the venture.',
          'Produce a startup budget, pricing logic, cash-flow assumptions, and funding strategy.',
        ], 120),
        lesson('esb-v2-pitch-launch-readiness', 'Pitch Lab and Business Launch Readiness', 3, 'capstone_exam_readiness', [
          'Present a concise business pitch.',
          'Respond to questions about market, operations, financials, and risk.',
          'Convert feedback into prioritized launch actions.',
        ], 90),
        lesson('esb-v2-cumulative-review', 'Cumulative ESB v2 Review — All Four Domains', 4, 'capstone_exam_readiness', [
          'Connect concepts across all four ESB v2 objective domains.',
          'Recognize common distractors and scenario cues in certification-style questions.',
          'Select the best business decision from incomplete real-world information.',
        ], 90),
        lesson('esb-v2-practice-remediation', 'Practice Assessment and Targeted Remediation', 5, 'capstone_exam_readiness', [
          'Complete a timed cumulative practice assessment.',
          'Analyze results by domain and competency.',
          'Complete targeted remediation before the final course exam.',
        ], 90),
        lesson('esb-v2-final-exam', 'Entrepreneurship & Small Business — Final Course Exam', 6, 'capstone_exam_readiness', [
          'Demonstrate integrated mastery of the Elevate ESB v2 preparation curriculum.',
          'Meet the course passing threshold before external certification testing.',
        ], 60),
      ],
    },
  ],
};
