/**
 * lib/curriculum/blueprints/index.ts
 *
 * Registry of all credential blueprints.
 * Import from here — do not import individual blueprint files directly.
 *
 * All blueprints use the single CredentialBlueprint type from types.ts.
 * The generator, builder, auditor, and validator all consume that type.
 */

export type {
  CredentialBlueprint,
  BlueprintModule,
  BlueprintLessonRef,
  BlueprintCompetency,
  BlueprintLessonTypeRule,
  BlueprintAssessmentRule,
  BlueprintGenerationRules,
  BlueprintAuditResult,
  BlueprintAuditViolation,
} from './types';

export { validateBlueprint } from './validateBlueprint';

import type { CredentialBlueprint } from './types';
import { STATIC_PROGRAM_MAP } from '@/data/programs/index';
import { buildProgramBlueprints } from './program-blueprint-factory';

let _registry: CredentialBlueprint[] | null = null;

function isBlockedExternalCourse(course: { provider?: string; url?: string }) {
  const provider = String(course.provider || '').toLowerCase();
  const url = String(course.url || '').toLowerCase();
  return provider.includes('coursera') || url.includes('coursera.org');
}

function sanitizeBlueprint(blueprint: CredentialBlueprint): CredentialBlueprint {
  if (!blueprint.externalCourses?.length) return blueprint;
  const externalCourses = blueprint.externalCourses.filter((course) => !isBlockedExternalCourse(course));
  if (externalCourses.length === blueprint.externalCourses.length) return blueprint;
  return { ...blueprint, externalCourses };
}

export async function getAllBlueprints(): Promise<CredentialBlueprint[]> {
  if (_registry) return _registry;
  const [
    { bookkeepingQuickbooksBlueprint },
    { barberApprenticeshipBlueprint },
    { crsIndianaBlueprint },
    { peerRecoverySpecialistBlueprint },
    { CCMA_BLUEPRINT },
    { prsIndianaBlueprint },
    { itHelpDeskBlueprint },
    { entrepreneurshipBlueprint },
  ] = await Promise.all([
    import('./bookkeeping-quickbooks'),
    import('./barber-apprenticeship'),
    import('./crs-indiana'),
    import('./peer-recovery-specialist'),
    import('./ccma'),
    import('./prs-indiana'),
    import('./it-help-desk'),
    import('./entrepreneurship'),
  ]);

  const explicitBlueprints = [
    bookkeepingQuickbooksBlueprint,
    barberApprenticeshipBlueprint,
    crsIndianaBlueprint,
    peerRecoverySpecialistBlueprint,
    CCMA_BLUEPRINT,
    prsIndianaBlueprint,
    itHelpDeskBlueprint,
    entrepreneurshipBlueprint,
  ];

  const explicitProgramSlugs = new Set(explicitBlueprints.map((bp) => bp.programSlug));
  const autoGeneratedBlueprints = buildProgramBlueprints(
    [...STATIC_PROGRAM_MAP.values()].filter(
      (program) => program.slug !== 'hvac-technician' && !explicitProgramSlugs.has(program.slug),
    ),
  );

  _registry = [...explicitBlueprints, ...autoGeneratedBlueprints].map(sanitizeBlueprint);
  return _registry;
}

export async function getBlueprintByCredentialSlug(
  credentialSlug: string,
): Promise<CredentialBlueprint | null> {
  const registry = await getAllBlueprints();
  return registry.find((bp) => bp.credentialSlug === credentialSlug) ?? null;
}

export async function getBlueprintById(id: string): Promise<CredentialBlueprint | null> {
  const registry = await getAllBlueprints();
  return registry.find((bp) => bp.id === id) ?? null;
}

export async function getBlueprintByProgramSlug(
  programSlug: string,
): Promise<CredentialBlueprint | null> {
  const registry = await getAllBlueprints();
  return registry.find((bp) => bp.programSlug === programSlug) ?? null;
}

/**
 * Returns the external courses declared on a blueprint for a given program slug.
 * Returns an empty array if the program has no blueprint or no external courses.
 */
export async function getExternalCoursesForProgram(
  programSlug: string,
): Promise<NonNullable<CredentialBlueprint['externalCourses']>> {
  const bp = await getBlueprintByProgramSlug(programSlug);
  return bp?.externalCourses ?? [];
}

/** @deprecated Use getBlueprintById('hvac-epa608-v1') instead */
export async function getHvacBlueprint(): Promise<CredentialBlueprint | null> {
  return getBlueprintById('hvac-epa608-v1');
}
