/**
 * lib/curriculum/blueprints/index.ts
 *
 * Registry of all credential blueprints.
 * Import from here — do not import individual blueprint files directly.
 *
 * All blueprints use the single CredentialBlueprint type from types.ts.
 * The generator, builder, auditor, and validator all consume that type.
 */

export type {
  CredentialBlueprint,
  BlueprintModule,
  BlueprintLessonRef,
  BlueprintCompetency,
  BlueprintLessonTypeRule,
  BlueprintAssessmentRule,
  BlueprintGenerationRules,
  BlueprintAuditResult,
  BlueprintAuditViolation,
} from './types';

export { validateBlueprint } from './validateBlueprint';

import type { CredentialBlueprint } from './types';
import { STATIC_PROGRAM_MAP } from '@/data/programs/index';
import { buildProgramBlueprints } from './program-blueprint-factory';
import { getRegisteredProgramStandard } from '@/lib/apprenticeship/registered-program-contract';

let _registry: CredentialBlueprint[] | null = null;

function isBlockedExternalCourse(course: { provider?: string; url?: string }) {
  const provider = String(course.provider || '').toLowerCase();
  const url = String(course.url || '').toLowerCase();
  return provider.includes('coursera') || url.includes('coursera.org');
}

function attachRegisteredApprenticeshipConfig(blueprint: CredentialBlueprint): CredentialBlueprint {
  const contract = getRegisteredProgramStandard(blueprint.programSlug);
  if (!contract) return blueprint;
  return {
    ...blueprint,
    apprenticeshipConfig: {
      approach: 'competency_based',
      rtiHours: contract.completion.requiredRtiHours,
      competencyCount: contract.completion.competencyCount,
      rapidsProgramCode: contract.standard.rapidsCode,
      registeredProgramSlug: contract.canonicalProgramSlug,
      fixedOjlCompletionHours: contract.completion.fixedOjlCompletionHours,
      standardKey: contract.standardKey,
      sponsorRegistrationNumber: contract.sponsor.registrationNumber,
      standardRevision: contract.sponsor.revisionDate,
    },
  };
}

function sanitizeBlueprint(blueprint: CredentialBlueprint): CredentialBlueprint {
  const registered = attachRegisteredApprenticeshipConfig(blueprint);
  if (!registered.externalCourses?.length) return registered;
  const externalCourses = registered.externalCourses.filter((course) => !isBlockedExternalCourse(course));
  if (externalCourses.length === registered.externalCourses.length) return registered;
  return { ...registered, externalCourses };
}

export async function getAllBlueprints(): Promise<CredentialBlueprint[]> {
  if (_registry) return _registry;
  const [
    { bookkeepingQuickbooksBlueprint },
    { barberApprenticeshipBlueprint },
    { estheticianBlueprint },
    { nailTechnicianBlueprint },
    { cosmetologyBlueprint },
    { crsIndianaBlueprint },
    { peerRecoverySpecialistBlueprint },
    { CCMA_BLUEPRINT },
    { prsIndianaBlueprint },
    { HVAC_EPA608_BLUEPRINT },
    { itHelpDeskBlueprint },
    { entrepreneurshipBlueprint },
    { businessEntrepreneurshipBlueprint },
  ] = await Promise.all([
    import('./bookkeeping-quickbooks'),
    import('./barber-apprenticeship'),
    import('./esthetician'),
    import('./nail-technician'),
    import('./cosmetology'),
    import('./crs-indiana'),
    import('./peer-recovery-specialist'),
    import('./ccma'),
    import('./prs-indiana'),
    import('./hvac-epa-608'),
    import('./it-help-desk'),
    import('./entrepreneurship'),
    import('./business-entrepreneurship'),
  ]);

  const elevateEsbBlueprint: CredentialBlueprint = {
    ...entrepreneurshipBlueprint,
    title: 'Elevate ESB',
    credentialTitle: 'Elevate ESB',
  };

  const explicitBlueprints = [
    bookkeepingQuickbooksBlueprint,
    barberApprenticeshipBlueprint,
    estheticianBlueprint,
    nailTechnicianBlueprint,
    cosmetologyBlueprint,
    crsIndianaBlueprint,
    peerRecoverySpecialistBlueprint,
    CCMA_BLUEPRINT,
    prsIndianaBlueprint,
    HVAC_EPA608_BLUEPRINT,
    itHelpDeskBlueprint,
    elevateEsbBlueprint,
    businessEntrepreneurshipBlueprint,
  ].map(sanitizeBlueprint);

  const explicitProgramSlugs = new Set(explicitBlueprints.map((bp) => bp.programSlug));
  const autoGeneratedBlueprints = buildProgramBlueprints(
    [...STATIC_PROGRAM_MAP.values()].filter(
      (program) => !explicitProgramSlugs.has(program.slug),
    ),
  ).map(sanitizeBlueprint);

  _registry = [...explicitBlueprints, ...autoGeneratedBlueprints];
  return _registry;
}

export async function getBlueprintByCredentialSlug(
  credentialSlug: string,
): Promise<CredentialBlueprint | null> {
  const registry = await getAllBlueprints();
  return registry.find((bp) => bp.credentialSlug === credentialSlug) ?? null;
}

export async function getBlueprintById(id: string): Promise<CredentialBlueprint | null> {
  const registry = await getAllBlueprints();
  return registry.find((bp) => bp.id === id) ?? null;
}

export async function getBlueprintByProgramSlug(
  programSlug: string,
): Promise<CredentialBlueprint | null> {
  const registry = await getAllBlueprints();
  return registry.find((bp) => bp.programSlug === programSlug) ?? null;
}

export async function getExternalCoursesForProgram(
  programSlug: string,
): Promise<NonNullable<CredentialBlueprint['externalCourses']>> {
  const bp = await getBlueprintByProgramSlug(programSlug);
  return bp?.externalCourses ?? [];
}

/** @deprecated Use getBlueprintById('hvac-epa608-v1') instead */
export async function getHvacBlueprint(): Promise<CredentialBlueprint | null> {
  return getBlueprintById('hvac-epa608-v1');
}
