import fs from 'node:fs';const docker=fs.readFileSync('Dockerfile.ultimate-worker','utf8');const provision=fs.readFileSync('scripts/northflank/provision-ultimate-worker.ts','utf8');const pkg=JSON.parse(fs.readFileSync('packages/ultimate-course-worker/package.json','utf8'));const requiredDocker=['node:22-bookworm-slim','npm install --omit=dev','chromium','ffmpeg','packages/ultimate-course-worker/package.json','RUN npm install --omit=dev --ignore-scripts --no-audit --no-fund','COPY lib/ultimate-course-builder ./lib/ultimate-course-builder','REMOTION_BROWSER_EXECUTABLE=/usr/bin/chromium',"find lib server -type f -name '*.ts'",'CMD ["node","--import=tsx"','test ! -d node_modules/stripe','workers/ultimate-course-builder.ts'];const requiredDeps=['@supabase/supabase-js','kokoro-js','tsx','server-only','@remotion/bundler','@remotion/renderer','@remotion/licensing','remotion'];const forbiddenDocker=['espeak-ng','COPY lib ./lib','COPY server ./server','--conditions=react-server'];const requiredProvision=["NORTHFLANK_GIT_BRANCH||'main'","deploymentPlan:'nf-compute-400'","configType:'default'",'Dockerfile.ultimate-worker',"AI_PROVIDER:'none'","AI_NARRATION_PROVIDER:'cloudflare'","ULTIMATE_WORKER_ID:'northflank-ultimate-worker'"];const missing=[...requiredDocker.filter(x=>!docker.includes(x)).map(x=>'docker:'+x),...requiredDeps.filter(x=>!pkg.dependencies?.[x]).map(x=>'dependency:'+x),...requiredProvision.filter(x=>!provision.includes(x)).map(x=>'provision:'+x),...forbiddenDocker.filter(x=>docker.includes(x)).map(x=>'forbidden:'+x)];if(missing.length){console.error('Ultimate worker parity FAILED:',missing);process.exit(1)}console.log('Ultimate worker parity PASS: dedicated workspace + minimal runtime + native container startup');
const activeMedia=fs.readFileSync('lib/ultimate-course-builder/adapters/platform-media.ts','utf8');
const forbiddenActiveMedia=['UltimateEnvatoMarketClient','this.envato.search(','this.envato.acquire(','/v1/discovery/search/search/item','/v3/market/buyer/download'];
const mediaViolations=forbiddenActiveMedia.filter((token)=>activeMedia.includes(token));
if(mediaViolations.length){console.error('Ultimate worker parity FAILED: active visual_assignment must use authenticated licensed workspace/library only',mediaViolations);process.exit(1)}
console.log('Ultimate media parity PASS: active visual_assignment is workspace/library-bound; no Envato Market API acquisition path');

const subscriptionRoute=fs.readFileSync('apps/admin/app/api/admin/integrations/envato/route.ts','utf8');
const forbiddenSubscriptionRoute=['https://api.envato.com','ENVATO_API_TOKEN','/v3/market/','marketAccount(','listPurchases('];
const subscriptionViolations=forbiddenSubscriptionRoute.filter(token=>subscriptionRoute.includes(token));
if(subscriptionViolations.length){console.error('Ultimate subscription parity FAILED: Market must be disconnected',subscriptionViolations);process.exit(1)}
if(!subscriptionRoute.includes('marketEnabled: false')||!subscriptionRoute.includes('subscriptionVerified: false')){console.error('Ultimate subscription parity FAILED: status must not invent subscription verification');process.exit(1)}
console.log('Ultimate subscription parity PASS: Market disconnected; subscription verification is explicit');
