-- Reconcile literal Supabase mutation payloads with the production Data API contract.
-- Additive and idempotent: preserves all existing data, constraints, RLS policies, and columns.
set lock_timeout = '5s';
set statement_timeout = '15min';

alter table public."account_deletion_requests" add column if not exists "email" text;
alter table public."account_export_events" add column if not exists "email" text;
alter table public."account_export_events" add column if not exists "format" text;
alter table public."achievements" add column if not exists "user_id" uuid;
alter table public."admin_activity_log" add column if not exists "metadata" jsonb;
alter table public."admin_activity_log" add column if not exists "user_id" uuid;
alter table public."affiliate_payouts" add column if not exists "payment_details" jsonb;
alter table public."affiliate_payouts" add column if not exists "user_id" uuid;
alter table public."affiliates" add column if not exists "commission_rate" numeric;
alter table public."affiliates" add column if not exists "created_by" uuid;
alter table public."affiliates" add column if not exists "notes" text;
alter table public."affiliates" add column if not exists "phone" text;
alter table public."affiliates" add column if not exists "website" text;
alter table public."ai_chat_sessions" add column if not exists "instructor_id" uuid;
alter table public."ai_chat_sessions" add column if not exists "program_slug" text;
alter table public."ai_chat_sessions" add column if not exists "started_at" timestamp with time zone;
alter table public."ai_chat_sessions" add column if not exists "student_id" uuid;
alter table public."ai_chat_sessions" add column if not exists "user_id" uuid;
alter table public."ai_instructor_assignments" add column if not exists "instructor_id" uuid;
alter table public."ai_instructor_assignments" add column if not exists "program_slug" text;
alter table public."ai_instructor_assignments" add column if not exists "student_id" uuid;
alter table public."ai_instructor_interactions" add column if not exists "assistant_response" text;
alter table public."ai_instructor_interactions" add column if not exists "instructor_id" uuid;
alter table public."ai_instructor_interactions" add column if not exists "instructor_name" text;
alter table public."ai_instructor_interactions" add column if not exists "interaction_type" text;
alter table public."ai_instructor_interactions" add column if not exists "program_id" uuid;
alter table public."ai_instructor_interactions" add column if not exists "timestamp" timestamp with time zone;
alter table public."ai_instructor_interactions" add column if not exists "user_id" uuid;
alter table public."ai_instructor_interactions" add column if not exists "user_message" text;
alter table public."ai_instructor_logs" add column if not exists "enrollment_id" uuid;
alter table public."ai_instructor_logs" add column if not exists "response" jsonb;
alter table public."ai_instructor_logs" add column if not exists "student_id" uuid;
alter table public."ai_messages" add column if not exists "conversation_id" uuid;
alter table public."ai_messages" add column if not exists "instructor_id" uuid;
alter table public."ai_messages" add column if not exists "metadata" jsonb;
alter table public."ai_messages" add column if not exists "role" text;
alter table public."ai_messages" add column if not exists "student_id" uuid;
alter table public."ai_repo_index" add column if not exists "file_hash" text;
alter table public."ai_repo_index" add column if not exists "repo_path" text;
alter table public."ai_repo_index" add column if not exists "updated_at" timestamp with time zone;
alter table public."ai_tasks" add column if not exists "config" jsonb;
alter table public."ai_tutor_interactions" add column if not exists "course_id" uuid;
alter table public."ai_tutor_interactions" add column if not exists "session_id" text;
alter table public."ai_tutor_interactions" add column if not exists "timestamp" timestamp with time zone;
alter table public."ai_tutor_interactions" add column if not exists "user_id" uuid;
alter table public."ambient_music_log" add column if not exists "audio_src" text;
alter table public."ambient_music_log" add column if not exists "page_id" uuid;
alter table public."ambient_music_log" add column if not exists "played_at" timestamp with time zone;
alter table public."analytics_events" add column if not exists "event" text;
alter table public."analytics_events" add column if not exists "metric_id" text;
alter table public."analytics_events" add column if not exists "metric_name" text;
alter table public."analytics_events" add column if not exists "metric_value" numeric;
alter table public."analytics_events" add column if not exists "path" text;
alter table public."analytics_events" add column if not exists "properties" jsonb;
alter table public."analytics_events" add column if not exists "recorded_at" timestamp with time zone;
alter table public."analytics_events" add column if not exists "referrer" text;
alter table public."analytics_events" add column if not exists "screen_height" integer;
alter table public."analytics_events" add column if not exists "screen_width" integer;
alter table public."analytics_events" add column if not exists "user_agent" text;
alter table public."announcements" add column if not exists "author_id" uuid;
alter table public."announcements" add column if not exists "content" text;
alter table public."announcements" add column if not exists "priority" text;
alter table public."announcements" add column if not exists "send_email" text;
alter table public."announcements" add column if not exists "send_push" text;
alter table public."announcements" add column if not exists "send_sms" text;
alter table public."api_keys" add column if not exists "api_key" text;
alter table public."api_keys" add column if not exists "api_secret" text;
alter table public."api_keys" add column if not exists "key_name" text;
alter table public."api_keys" add column if not exists "request_count" integer;
alter table public."api_request_logs" add column if not exists "error_message" text;
alter table public."api_request_logs" add column if not exists "user_agent" text;
alter table public."app_screenshot_views" add column if not exists "app_type" text;
alter table public."app_screenshot_views" add column if not exists "user_id" uuid;
alter table public."app_screenshot_views" add column if not exists "viewed_at" timestamp with time zone;
alter table public."application_claim_log" add column if not exists "applications_claimed" text;
alter table public."application_claim_log" add column if not exists "claimed_at" timestamp with time zone;
alter table public."application_claim_log" add column if not exists "email" text;
alter table public."applications" add column if not exists "assigned_at" timestamp with time zone;
alter table public."applications" add column if not exists "assigned_shop_id" uuid;
alter table public."applications" add column if not exists "claimed_at" timestamp with time zone;
alter table public."applications" add column if not exists "rejection_reason" text;
alter table public."appointments" add column if not exists "calendly_event_uri" text;
alter table public."appointments" add column if not exists "canceled_at" timestamp with time zone;
alter table public."appointments" add column if not exists "cancellation_reason" text;
alter table public."appointments" add column if not exists "completed_at" timestamp with time zone;
alter table public."appointments" add column if not exists "contact_name" text;
alter table public."appointments" add column if not exists "meeting_link" text;
alter table public."appointments" add column if not exists "meeting_type" text;
alter table public."appointments" add column if not exists "notes" text;
alter table public."appointments" add column if not exists "phone_number" text;
alter table public."appointments" add column if not exists "scheduled_at" timestamp with time zone;
alter table public."appointments" add column if not exists "scheduled_time" time without time zone;
alter table public."appointments" add column if not exists "student_id" uuid;
alter table public."appointments" add column if not exists "title" text;
alter table public."apprentice_service_logs" add column if not exists "enrollment_id" uuid;
alter table public."apprentice_service_logs" add column if not exists "hours" integer;
alter table public."apprentice_service_logs" add column if not exists "logged_at" timestamp with time zone;
alter table public."apprentice_service_logs" add column if not exists "services_performed" jsonb;
alter table public."apprentice_service_logs" add column if not exists "total_services" integer;
alter table public."apprentices" add column if not exists "application_id" uuid;
alter table public."apprentices" add column if not exists "competencies_completed" boolean;
alter table public."apprentices" add column if not exists "competencies_required" boolean;
alter table public."apprentices" add column if not exists "enrollment_date" date;
alter table public."apprentices" add column if not exists "enrollment_id" uuid;
alter table public."apprentices" add column if not exists "host_shop_id" uuid;
alter table public."apprentices" add column if not exists "hours_completed" numeric;
alter table public."apprentices" add column if not exists "ojl_hours" numeric;
alter table public."apprentices" add column if not exists "ojl_hours_required" boolean;
alter table public."apprentices" add column if not exists "program_name" text;
alter table public."apprentices" add column if not exists "rti_hours" numeric;
alter table public."apprentices" add column if not exists "rti_hours_required" boolean;
alter table public."apprentices" add column if not exists "total_hours_required" text;
alter table public."apprentices" add column if not exists "transfer_hours_credited" text;
alter table public."apprenticeship_shop_drafts" add column if not exists "application_id" uuid;
alter table public."apprenticeship_shop_drafts" add column if not exists "form_data" jsonb;
alter table public."apprenticeship_shop_drafts" add column if not exists "user_id" uuid;
alter table public."approval_workflows" add column if not exists "checklist_json" text;
alter table public."approval_workflows" add column if not exists "completed_approvals" text;
alter table public."approval_workflows" add column if not exists "package_json" text;
alter table public."approval_workflows" add column if not exists "program_id" uuid;
alter table public."approval_workflows" add column if not exists "program_title" text;
alter table public."approval_workflows" add column if not exists "required_approvals" text;
alter table public."approval_workflows" add column if not exists "review_notes" text;
alter table public."approval_workflows" add column if not exists "revision_notes" text;
alter table public."approval_workflows" add column if not exists "submitted_at" timestamp with time zone;
alter table public."approval_workflows" add column if not exists "submitted_by" uuid;
alter table public."approval_workflows" add column if not exists "version" integer;
alter table public."assessment_attempts" add column if not exists "graded_at" timestamp with time zone;
alter table public."assessment_attempts" add column if not exists "max_score" text;
alter table public."assessment_attempts" add column if not exists "score" numeric;
alter table public."assessments" add column if not exists "course_id" uuid;
alter table public."assessments" add column if not exists "created_by" uuid;
alter table public."assessments" add column if not exists "module_id" uuid;
alter table public."assessments" add column if not exists "questions" jsonb;
alter table public."assessments" add column if not exists "randomize_questions" boolean;
alter table public."assessments" add column if not exists "total_points" integer;
alter table public."assignment_submissions" add column if not exists "comment" text;
alter table public."assignment_submissions" add column if not exists "file_path" text;
alter table public."assignment_submissions" add column if not exists "files" jsonb;
alter table public."assignment_submissions" add column if not exists "student_id" uuid;
alter table public."assignments" add column if not exists "points_possible" integer;
alter table public."attendance_log" add column if not exists "activity_type" text;
alter table public."attendance_log" add column if not exists "course_id" uuid;
alter table public."attendance_log" add column if not exists "duration_minutes" integer;
alter table public."attendance_log" add column if not exists "logout_time" timestamp with time zone;
alter table public."attendance_records" add column if not exists "check_in_method" text;
alter table public."attendance_records" add column if not exists "checked_in_at" timestamp with time zone;
alter table public."attendance_records" add column if not exists "latitude" numeric;
alter table public."attendance_records" add column if not exists "longitude" numeric;
alter table public."attendance_records" add column if not exists "meeting_id" text;
alter table public."attendance_records" add column if not exists "session_id" text;
alter table public."attendance_records" add column if not exists "verification_method" text;
alter table public."attendance_records" add column if not exists "verified" boolean;
alter table public."attendance_sessions" add column if not exists "required" boolean;
alter table public."audit_logs" add column if not exists "actor_type" text;
alter table public."autopilot_logs" add column if not exists "course_id" uuid;
alter table public."autopilot_logs" add column if not exists "data" jsonb;
alter table public."autopilot_logs" add column if not exists "options" jsonb;
alter table public."autopilot_logs" add column if not exists "started_at" timestamp with time zone;
alter table public."autopilot_logs" add column if not exists "status" text;
alter table public."autopilot_logs" add column if not exists "timestamp" timestamp with time zone;
alter table public."autopilot_settings" add column if not exists "course_id" uuid;
alter table public."autopilot_settings" add column if not exists "enabled" boolean;
alter table public."autopilot_settings" add column if not exists "last_updated" timestamp with time zone;
alter table public."autopilot_settings" add column if not exists "settings" jsonb;
alter table public."backups" add column if not exists "record_count" integer;
alter table public."backups" add column if not exists "size_bytes" bigint;
alter table public."backups" add column if not exists "tables" text;
alter table public."barber_practical_submissions" add column if not exists "rejection_reason" text;
alter table public."barbershop_partner_applications" add column if not exists "partner_id" uuid;
alter table public."billing_accounts" add column if not exists "employer_id" uuid;
alter table public."billing_accounts" add column if not exists "onboarding_completed" boolean;
alter table public."billing_accounts" add column if not exists "stripe_account_id" text;
alter table public."billing_cycles" add column if not exists "next_billing_date" date;
alter table public."billing_cycles" add column if not exists "user_id" uuid;
alter table public."blog_posts" add column if not exists "reading_time" text;
alter table public."blog_posts" add column if not exists "views" text;
alter table public."bridge_payment_plans" add column if not exists "auto_payment_enabled" boolean;
alter table public."bridge_payment_plans" add column if not exists "credential_hold" text;
alter table public."bridge_payment_plans" add column if not exists "down_payment_amount" numeric;
alter table public."bridge_payment_plans" add column if not exists "enrollment_id" uuid;
alter table public."bridge_payment_plans" add column if not exists "max_term_months" integer;
alter table public."bridge_payment_plans" add column if not exists "monthly_payment_amount" numeric;
alter table public."bridge_payment_plans" add column if not exists "plan_end_date" date;
alter table public."bridge_payment_plans" add column if not exists "total_amount" numeric;
alter table public."campaigns" add column if not exists "audience" text;
alter table public."campaigns" add column if not exists "body" text;
alter table public."campaigns" add column if not exists "scheduled_at" timestamp with time zone;
alter table public."campaigns" add column if not exists "subject" text;
alter table public."captcha_attempts" add column if not exists "attempted_at" timestamp with time zone;
alter table public."captcha_attempts" add column if not exists "attempts" integer;
alter table public."captcha_attempts" add column if not exists "form_id" uuid;
alter table public."captcha_attempts" add column if not exists "ip_address" text;
alter table public."captcha_attempts" add column if not exists "user_agent" text;
alter table public."cart_items" add column if not exists "cart_id" uuid;
alter table public."cart_items" add column if not exists "total" numeric;
alter table public."cart_items" add column if not exists "updated_at" timestamp with time zone;
alter table public."cart_items" add column if not exists "variant_id" uuid;
alter table public."case_tasks" add column if not exists "completed_at" timestamp with time zone;
alter table public."case_tasks" add column if not exists "completed_by" uuid;
alter table public."case_tasks" add column if not exists "evidence_metadata" jsonb;
alter table public."case_tasks" add column if not exists "evidence_url" text;
alter table public."certificates" add column if not exists "certificate_subtype" text;
alter table public."certificates" add column if not exists "recipient_name" text;
alter table public."certificates" add column if not exists "updated_at" timestamp with time zone;
alter table public."chat_messages" add column if not exists "session_id" text;
alter table public."clinical_hours_logs" add column if not exists "supervisor_signature" text;
alter table public."clinical_hours_logs" add column if not exists "supervisor_verified" boolean;
alter table public."clinical_hours_logs" add column if not exists "verified_at" timestamp with time zone;
alter table public."clinical_sites" add column if not exists "active" boolean;
alter table public."cohorts" add column if not exists "cohort_name" text;
alter table public."collaboration_messages" add column if not exists "room_id" uuid;
alter table public."collaboration_messages" add column if not exists "user_name" text;
alter table public."collaboration_presence" add column if not exists "last_seen" timestamp with time zone;
alter table public."collaboration_presence" add column if not exists "room_id" uuid;
alter table public."collaboration_presence" add column if not exists "user_id" uuid;
alter table public."collaboration_presence" add column if not exists "user_name" text;
alter table public."compliance_alerts" add column if not exists "message" text;
alter table public."compliance_alerts" add column if not exists "metadata" jsonb;
alter table public."compliance_alerts" add column if not exists "resolved" boolean;
alter table public."consent_preferences" add column if not exists "analytics" boolean;
alter table public."consent_preferences" add column if not exists "functional" boolean;
alter table public."consent_preferences" add column if not exists "marketing" boolean;
alter table public."contact_hours" add column if not exists "sessions_count" integer;
alter table public."contact_hours" add column if not exists "student_id" uuid;
alter table public."contact_hours" add column if not exists "total_hours" numeric;
alter table public."contact_hours" add column if not exists "week_start" date;
alter table public."content_library" add column if not exists "view_count" integer;
alter table public."conversations" add column if not exists "instructor_id" uuid;
alter table public."conversations" add column if not exists "program_slug" text;
alter table public."conversations" add column if not exists "student_id" uuid;
alter table public."conversations" add column if not exists "user_id" uuid;
alter table public."copilot_usage_log" add column if not exists "admin_id" uuid;
alter table public."copilot_usage_log" add column if not exists "record_count" integer;
alter table public."copilot_usage_log" add column if not exists "session_id" text;
alter table public."copilot_usage_log" add column if not exists "timestamp" timestamp with time zone;
alter table public."coupons" add column if not exists "created_by" uuid;
alter table public."course_announcements" add column if not exists "author_id" uuid;
alter table public."course_announcements" add column if not exists "course_id" uuid;
alter table public."course_enrollments" add column if not exists "revoke_reason" text;
alter table public."course_enrollments" add column if not exists "revoked_at" timestamp with time zone;
alter table public."course_generation_jobs" add column if not exists "completed_at" timestamp with time zone;
alter table public."course_generation_jobs" add column if not exists "credential_type" text;
alter table public."course_generation_jobs" add column if not exists "metadata" jsonb;
alter table public."course_generation_jobs" add column if not exists "occupation" text;
alter table public."course_generation_jobs" add column if not exists "soc_code" text;
alter table public."course_generation_jobs" add column if not exists "target_hours" numeric;
alter table public."course_generation_jobs" add column if not exists "title" text;
alter table public."course_modules" add column if not exists "created_by" uuid;
alter table public."course_reviews" add column if not exists "body" text;
alter table public."course_reviews" add column if not exists "course_id" uuid;
alter table public."course_reviews" add column if not exists "helpful_count" integer;
alter table public."course_reviews" add column if not exists "title" text;
alter table public."course_versions" add column if not exists "version" integer;
alter table public."courses" add column if not exists "created_by" uuid;
alter table public."courses" add column if not exists "metadata" jsonb;
alter table public."credential_verification" add column if not exists "state_verification_date" date;
alter table public."credential_verification" add column if not exists "state_verified" boolean;
alter table public."credentials" add column if not exists "course_id" uuid;
alter table public."credentials" add column if not exists "credential_type" text;
alter table public."credentials" add column if not exists "issuer_org_id" uuid;
alter table public."credentials" add column if not exists "metadata" jsonb;
alter table public."credentials" add column if not exists "program_id" uuid;
alter table public."credentials" add column if not exists "revoked_reason" text;
alter table public."credentials" add column if not exists "student_id" uuid;
alter table public."crm_appointments" add column if not exists "assigned_to" uuid;
alter table public."crm_appointments" add column if not exists "title" text;
alter table public."crm_contacts" add column if not exists "created_by" uuid;
alter table public."crm_deals" add column if not exists "company_name" text;
alter table public."crm_follow_ups" add column if not exists "description" text;
alter table public."crm_follow_ups" add column if not exists "priority" text;
alter table public."crm_follow_ups" add column if not exists "title" text;
alter table public."crm_leads" add column if not exists "last_contact_at" timestamp with time zone;
alter table public."cta_clicks" add column if not exists "clicked_at" timestamp with time zone;
alter table public."cta_clicks" add column if not exists "cta_type" text;
alter table public."cta_clicks" add column if not exists "source" text;
alter table public."cta_clicks" add column if not exists "user_id" uuid;
alter table public."curriculum_versions" add column if not exists "changes_json" text;
alter table public."curriculum_versions" add column if not exists "package_json" text;
alter table public."curriculum_versions" add column if not exists "program_id" uuid;
alter table public."curriculum_versions" add column if not exists "status" text;
alter table public."customer_service_tickets" add column if not exists "user_id" uuid;
alter table public."daily_streaks" add column if not exists "user_id" uuid;
alter table public."delivery_logs" add column if not exists "recipient_name" text;
alter table public."demo_analytics" add column if not exists "event_type" text;
alter table public."demo_analytics" add column if not exists "extra_data" jsonb;
alter table public."demo_analytics" add column if not exists "session_id" text;
alter table public."demo_analytics" add column if not exists "step_id" uuid;
alter table public."demo_analytics" add column if not exists "timestamp" timestamp with time zone;
alter table public."demo_analytics" add column if not exists "user_id" uuid;
alter table public."digital_binders" add column if not exists "student_id" uuid;
alter table public."discussion_replies" add column if not exists "author_id" uuid;
alter table public."discussion_replies" add column if not exists "content" text;
alter table public."discussion_replies" add column if not exists "discussion_id" uuid;
alter table public."discussion_replies" add column if not exists "parent_reply_id" uuid;
alter table public."discussions" add column if not exists "author_id" uuid;
alter table public."discussions" add column if not exists "course_id" uuid;
alter table public."discussions" add column if not exists "program_id" uuid;
alter table public."discussions" add column if not exists "tags" text[];
alter table public."documents" add column if not exists "applied_at" timestamp with time zone;
alter table public."documents" add column if not exists "applied_to_application" text;
alter table public."documents" add column if not exists "storage_path" text;
alter table public."documents" add column if not exists "validation_checks" jsonb;
alter table public."donations" add column if not exists "status" text;
alter table public."donations" add column if not exists "stripe_session_id" text;
alter table public."drug_tests" add column if not exists "collection_site" text;
alter table public."drug_tests" add column if not exists "created_by" uuid;
alter table public."drug_tests" add column if not exists "enrollment_id" uuid;
alter table public."drug_tests" add column if not exists "lab_report_url" text;
alter table public."drug_tests" add column if not exists "mro_review_required" boolean;
alter table public."drug_tests" add column if not exists "notes" text;
alter table public."drug_tests" add column if not exists "organization_id" uuid;
alter table public."drug_tests" add column if not exists "panel_type" text;
alter table public."drug_tests" add column if not exists "required_by_employer" text;
alter table public."drug_tests" add column if not exists "required_by_funding" text;
alter table public."drug_tests" add column if not exists "required_by_program" text;
alter table public."drug_tests" add column if not exists "result_date" date;
alter table public."drug_tests" add column if not exists "result_details" jsonb;
alter table public."drug_tests" add column if not exists "scheduled_date" date;
alter table public."drug_tests" add column if not exists "student_id" uuid;
alter table public."ecr_snapshots" add column if not exists "enrollment_id" uuid;
alter table public."ecr_snapshots" add column if not exists "student_id" uuid;
alter table public."ecr_sync_logs" add column if not exists "successful" integer;
alter table public."ecr_sync_logs" add column if not exists "sync_date" date;
alter table public."ecr_sync_logs" add column if not exists "total_students" integer;
alter table public."email_logs" add column if not exists "email_type" text;
alter table public."email_queue" add column if not exists "from_email" text;
alter table public."email_queue" add column if not exists "html_body" text;
alter table public."email_queue" add column if not exists "message_id" text;
alter table public."email_queue" add column if not exists "related_id" uuid;
alter table public."email_queue" add column if not exists "related_type" text;
alter table public."email_queue" add column if not exists "scheduled_for" timestamp with time zone;
alter table public."email_queue" add column if not exists "template_data" jsonb;
alter table public."email_queue" add column if not exists "template_name" text;
alter table public."email_queue" add column if not exists "text_body" text;
alter table public."email_queue" add column if not exists "to_email" text;
alter table public."employees" add column if not exists "status" text;
alter table public."employer_incentives" add column if not exists "created_by" uuid;
alter table public."employer_incentives" add column if not exists "hours_completed" numeric;
alter table public."employer_incentives" add column if not exists "hours_required" numeric;
alter table public."employer_sponsorships" add column if not exists "employer_name" text;
alter table public."employer_sponsorships" add column if not exists "employment_end_reason" text;
alter table public."employer_sponsorships" add column if not exists "employment_ended" text;
alter table public."employer_sponsorships" add column if not exists "employment_ended_at" timestamp with time zone;
alter table public."employer_sponsorships" add column if not exists "monthly_reimbursement" numeric;
alter table public."employer_sponsorships" add column if not exists "reimbursement_stopped_at" timestamp with time zone;
alter table public."employer_sponsorships" add column if not exists "user_id" uuid;
alter table public."employers" add column if not exists "contact_email" text;
alter table public."employers" add column if not exists "contact_phone" text;
alter table public."employers" add column if not exists "name" text;
alter table public."employers" add column if not exists "notes" text;
alter table public."employers" add column if not exists "status" text;
alter table public."employers" add column if not exists "website" text;
alter table public."enrollment_acknowledgments" add column if not exists "acknowledgment_type" text;
alter table public."enrollment_acknowledgments" add column if not exists "program_id" uuid;
alter table public."enrollment_acknowledgments" add column if not exists "user_id" uuid;
alter table public."enrollment_cases" add column if not exists "funding_source" text;
alter table public."enrollment_cases" add column if not exists "program_id" uuid;
alter table public."enrollment_cases" add column if not exists "program_slug" text;
alter table public."enrollment_cases" add column if not exists "program_type" text;
alter table public."enrollment_cases" add column if not exists "region_id" text;
alter table public."enrollment_events" add column if not exists "metadata" jsonb;
alter table public."enrollment_module_progress" add column if not exists "last_accessed_at" timestamp with time zone;
alter table public."enrollment_module_progress" add column if not exists "partner_completion_proof_url" text;
alter table public."entity_eligibility_checks" add column if not exists "cage_valid" boolean;
alter table public."entity_eligibility_checks" add column if not exists "checked_at" timestamp with time zone;
alter table public."entity_eligibility_checks" add column if not exists "eligible" boolean;
alter table public."entity_eligibility_checks" add column if not exists "entity_id" uuid;
alter table public."entity_eligibility_checks" add column if not exists "issues" jsonb;
alter table public."entity_eligibility_checks" add column if not exists "not_excluded" boolean;
alter table public."entity_eligibility_checks" add column if not exists "registration_not_expired" text;
alter table public."entity_eligibility_checks" add column if not exists "reps_certs_current" boolean;
alter table public."entity_eligibility_checks" add column if not exists "sam_active" boolean;
alter table public."entity_eligibility_checks" add column if not exists "sam_data" jsonb;
alter table public."entity_eligibility_checks" add column if not exists "sam_registered" boolean;
alter table public."entity_eligibility_checks" add column if not exists "score" numeric;
alter table public."entity_eligibility_checks" add column if not exists "uei" text;
alter table public."entity_eligibility_checks" add column if not exists "uei_valid" boolean;
alter table public."entity_eligibility_checks" add column if not exists "warnings" jsonb;
alter table public."exam_attempt_questions" add column if not exists "answered_at" timestamp with time zone;
alter table public."exam_attempt_questions" add column if not exists "is_correct" boolean;
alter table public."exam_attempt_questions" add column if not exists "student_answer" text;
alter table public."exam_attempts" add column if not exists "attempt_number" integer;
alter table public."exam_attempts" add column if not exists "completed_at" timestamp with time zone;
alter table public."exam_attempts" add column if not exists "exam_id" uuid;
alter table public."exam_attempts" add column if not exists "ip_address" text;
alter table public."exam_attempts" add column if not exists "student_id" uuid;
alter table public."exam_attempts" add column if not exists "user_agent" text;
alter table public."exam_schedule_requests" add column if not exists "notes" text;
alter table public."exam_schedule_requests" add column if not exists "preferred_date" date;
alter table public."exam_schedule_requests" add column if not exists "program_id" uuid;
alter table public."external_modules" add column if not exists "approved_at" timestamp with time zone;
alter table public."external_modules" add column if not exists "approved_by" uuid;
alter table public."external_modules" add column if not exists "rejected_at" timestamp with time zone;
alter table public."external_modules" add column if not exists "rejected_by" uuid;
alter table public."faq_search_analytics" add column if not exists "search_query" text;
alter table public."faq_search_analytics" add column if not exists "searched_at" timestamp with time zone;
alter table public."faq_search_analytics" add column if not exists "user_id" uuid;
alter table public."feedback" add column if not exists "browser_info" text;
alter table public."feedback" add column if not exists "category" text;
alter table public."feedback" add column if not exists "page_url" text;
alter table public."feedback" add column if not exists "priority" text;
alter table public."feedback" add column if not exists "screenshot_url" text;
alter table public."feedback" add column if not exists "status" text;
alter table public."feedback" add column if not exists "votes" integer;
alter table public."feedback_votes" add column if not exists "feedback_id" uuid;
alter table public."financial_aid_calculations" add column if not exists "dependents" integer;
alter table public."financial_aid_calculations" add column if not exists "estimated_grant" numeric;
alter table public."financial_aid_calculations" add column if not exists "estimated_loan" numeric;
alter table public."financial_aid_calculations" add column if not exists "income_range" text;
alter table public."financial_aid_calculations" add column if not exists "tuition_amount" numeric;
alter table public."financial_assurance_records" add column if not exists "coverage_type" text;
alter table public."financial_assurance_records" add column if not exists "created_by" uuid;
alter table public."financial_assurance_records" add column if not exists "policy_number" text;
alter table public."followup_schedule" add column if not exists "enrollment_id" uuid;
alter table public."followup_schedule" add column if not exists "follow_up_type" text;
alter table public."forum_categories" add column if not exists "active" boolean;
alter table public."forum_categories" add column if not exists "order" integer;
alter table public."forum_posts" add column if not exists "course_id" uuid;
alter table public."forum_posts" add column if not exists "edited" boolean;
alter table public."forum_posts" add column if not exists "edited_at" timestamp with time zone;
alter table public."forum_posts" add column if not exists "flag_reason" text;
alter table public."forum_posts" add column if not exists "flagged" boolean;
alter table public."forum_posts" add column if not exists "moderated" boolean;
alter table public."forum_posts" add column if not exists "moderation_action" text;
alter table public."forum_posts" add column if not exists "moderation_notes" text;
alter table public."forum_replies" add column if not exists "thread_id" uuid;
alter table public."forum_thread_views" add column if not exists "thread_id" uuid;
alter table public."forum_thread_views" add column if not exists "user_id" uuid;
alter table public."forum_thread_views" add column if not exists "viewed_at" timestamp with time zone;
alter table public."forum_threads" add column if not exists "author_id" uuid;
alter table public."forum_threads" add column if not exists "last_activity_at" timestamp with time zone;
alter table public."gdpr_requests" add column if not exists "completed_at" timestamp with time zone;
alter table public."gdpr_requests" add column if not exists "request_type" text;
alter table public."generated_assets" add column if not exists "asset_type" text;
alter table public."generated_assets" add column if not exists "copy_text" jsonb;
alter table public."generated_assets" add column if not exists "created_by" uuid;
alter table public."generated_assets" add column if not exists "dimensions" jsonb;
alter table public."generated_assets" add column if not exists "html" text;
alter table public."generated_assets" add column if not exists "summary" text;
alter table public."generated_courses" add column if not exists "credential_type" text;
alter table public."generated_courses" add column if not exists "delivery_mode" text;
alter table public."generated_courses" add column if not exists "job_id" text;
alter table public."generated_courses" add column if not exists "metadata" jsonb;
alter table public."generated_courses" add column if not exists "occupation" text;
alter table public."generated_courses" add column if not exists "soc_code" text;
alter table public."generated_courses" add column if not exists "subtitle" text;
alter table public."generated_courses" add column if not exists "target_audience" text;
alter table public."generated_courses" add column if not exists "target_hours" numeric;
alter table public."generated_lessons" add column if not exists "description" text;
alter table public."generated_lessons" add column if not exists "duration_minutes" integer;
alter table public."generated_lessons" add column if not exists "job_id" text;
alter table public."generated_lessons" add column if not exists "lesson_number" integer;
alter table public."generated_lessons" add column if not exists "module_id" uuid;
alter table public."generated_lessons" add column if not exists "objectives" jsonb;
alter table public."generated_lessons" add column if not exists "order_index" integer;
alter table public."generated_lessons" add column if not exists "summary" text;
alter table public."generated_modules" add column if not exists "description" text;
alter table public."generated_modules" add column if not exists "estimated_hours" integer;
alter table public."generated_modules" add column if not exists "job_id" text;
alter table public."generated_modules" add column if not exists "objectives" jsonb;
alter table public."generated_pages" add column if not exists "html" text;
alter table public."generated_quizzes" add column if not exists "course_id" uuid;
alter table public."generated_quizzes" add column if not exists "job_id" text;
alter table public."generated_quizzes" add column if not exists "passing_score" integer;
alter table public."generated_quizzes" add column if not exists "questions" jsonb;
alter table public."generated_quizzes" add column if not exists "title" text;
alter table public."grades" add column if not exists "grade" text;
alter table public."grades" add column if not exists "grade_item_id" uuid;
alter table public."grades" add column if not exists "graded_by" uuid;
alter table public."grades" add column if not exists "grader_id" uuid;
alter table public."grades" add column if not exists "rubric_scores" jsonb;
alter table public."grades" add column if not exists "submission_id" text;
alter table public."grant_eligibility_results" add column if not exists "checked_at" timestamp with time zone;
alter table public."grant_eligibility_results" add column if not exists "eligibility_check_id" uuid;
alter table public."grant_eligibility_results" add column if not exists "eligible" boolean;
alter table public."grant_eligibility_results" add column if not exists "entity_id" uuid;
alter table public."grant_eligibility_results" add column if not exists "entity_type_match" text;
alter table public."grant_eligibility_results" add column if not exists "grant_id" uuid;
alter table public."grant_eligibility_results" add column if not exists "location_match" text;
alter table public."grant_eligibility_results" add column if not exists "match_score" numeric;
alter table public."grant_eligibility_results" add column if not exists "naics_match" text;
alter table public."grant_eligibility_results" add column if not exists "reasons" text[];
alter table public."grant_federal_forms" add column if not exists "application_id" uuid;
alter table public."grant_federal_forms" add column if not exists "generated_at" timestamp with time zone;
alter table public."grant_federal_forms" add column if not exists "sf424_data" jsonb;
alter table public."grant_federal_forms" add column if not exists "sf424a_data" jsonb;
alter table public."grant_federal_forms" add column if not exists "sflll_data" jsonb;
alter table public."grant_notification_log" add column if not exists "email_sent" boolean;
alter table public."grant_notification_log" add column if not exists "notification_id" uuid;
alter table public."grant_notification_log" add column if not exists "recipients_count" integer;
alter table public."grant_notification_log" add column if not exists "sent_at" timestamp with time zone;
alter table public."grant_notification_log" add column if not exists "sms_sent" boolean;
alter table public."grant_notifications" add column if not exists "application_id" uuid;
alter table public."grant_notifications" add column if not exists "entity_id" uuid;
alter table public."grant_notifications" add column if not exists "grant_id" uuid;
alter table public."grant_notifications" add column if not exists "message" text;
alter table public."grant_notifications" add column if not exists "metadata" jsonb;
alter table public."grant_notifications" add column if not exists "priority" text;
alter table public."grant_notifications" add column if not exists "read" boolean;
alter table public."grant_notifications" add column if not exists "type" text;
alter table public."grant_opportunities" add column if not exists "agency_name" text;
alter table public."grant_opportunities" add column if not exists "opportunity_url" text;
alter table public."grant_packages" add column if not exists "application_id" uuid;
alter table public."grant_packages" add column if not exists "entity_id" uuid;
alter table public."grant_packages" add column if not exists "files_included" boolean;
alter table public."grant_packages" add column if not exists "grant_id" uuid;
alter table public."grant_packages" add column if not exists "package_version" text;
alter table public."grant_submissions" add column if not exists "application_id" uuid;
alter table public."grant_submissions" add column if not exists "confirmation_receipt" text;
alter table public."grant_submissions" add column if not exists "entity_id" uuid;
alter table public."grant_submissions" add column if not exists "grant_id" uuid;
alter table public."grant_submissions" add column if not exists "method" text;
alter table public."grant_submissions" add column if not exists "notes" text;
alter table public."grant_submissions" add column if not exists "tracking_number" text;
alter table public."help_search_log" add column if not exists "query" text;
alter table public."help_search_log" add column if not exists "result_count" integer;
alter table public."help_search_log" add column if not exists "searched_at" timestamp with time zone;
alter table public."incentives" add column if not exists "amount" numeric;
alter table public."incentives" add column if not exists "created_by" uuid;
alter table public."incentives" add column if not exists "employer_name" text;
alter table public."incentives" add column if not exists "end_date" date;
alter table public."incentives" add column if not exists "start_date" date;
alter table public."incentives" add column if not exists "type" text;
alter table public."inquiries" add column if not exists "funding_type" text;
alter table public."inquiries" add column if not exists "program_interest" text;
alter table public."inquiries" add column if not exists "source" text;
alter table public."inquiries" add column if not exists "status" text;
alter table public."intake_records" add column if not exists "funding_pathway_assigned_at" timestamp with time zone;
alter table public."intake_records" add column if not exists "funding_pathway_assigned_by" text;
alter table public."invoices" add column if not exists "notes" text;
alter table public."invoices" add column if not exists "stripe_invoice_id" text;
alter table public."job_applications" add column if not exists "job_id" text;
alter table public."job_applications" add column if not exists "user_id" uuid;
alter table public."job_queue" add column if not exists "completed_at" timestamp with time zone;
alter table public."job_queue" add column if not exists "last_error" text;
alter table public."job_queue" add column if not exists "run_after" timestamp with time zone;
alter table public."leads" add column if not exists "score" numeric;
alter table public."learner_credentials" add column if not exists "credly_badge_id" text;
alter table public."learner_credentials" add column if not exists "exam_attempt_id" uuid;
alter table public."learning_activity" add column if not exists "activity_date" date;
alter table public."learning_activity" add column if not exists "seconds_watched" numeric;
alter table public."learning_activity" add column if not exists "user_id" uuid;
alter table public."lesson_comments" add column if not exists "content" text;
alter table public."lesson_comments" add column if not exists "lesson_id" uuid;
alter table public."lesson_comments" add column if not exists "user_id" uuid;
alter table public."lesson_enhancements" add column if not exists "enhancements" jsonb;
alter table public."lesson_enhancements" add column if not exists "lesson_id" uuid;
alter table public."lesson_enhancements" add column if not exists "type" text;
alter table public."lesson_notes" add column if not exists "lesson_id" uuid;
alter table public."lesson_notes" add column if not exists "user_id" uuid;
alter table public."lesson_progress" add column if not exists "last_watched" timestamp with time zone;
alter table public."lesson_progress" add column if not exists "progress_seconds" numeric;
alter table public."lesson_questions" add column if not exists "author_id" uuid;
alter table public."lesson_questions" add column if not exists "lesson_id" uuid;
alter table public."license_agreement_acceptances" add column if not exists "document_url" text;
alter table public."license_agreement_acceptances" add column if not exists "email_at_signing" text;
alter table public."license_events" add column if not exists "description" text;
alter table public."license_events" add column if not exists "metadata" jsonb;
alter table public."license_requests" add column if not exists "internal_notes" text;
alter table public."licenses" add column if not exists "expiry_warning_sent" boolean;
alter table public."licenses" add column if not exists "max_students" integer;
alter table public."licenses" add column if not exists "valid_from" date;
alter table public."message_notifications" add column if not exists "read" boolean;
alter table public."message_notifications" add column if not exists "read_at" timestamp with time zone;
alter table public."messages" add column if not exists "content" text;
alter table public."messages" add column if not exists "edited" boolean;
alter table public."messages" add column if not exists "edited_at" timestamp with time zone;
alter table public."moderation_actions" add column if not exists "content_id" uuid;
alter table public."moderation_actions" add column if not exists "content_type" text;
alter table public."moderation_queue" add column if not exists "flagged_by" text;
alter table public."moderation_queue" add column if not exists "resolution" text;
alter table public."moderation_queue" add column if not exists "resolved_at" timestamp with time zone;
alter table public."moderation_queue" add column if not exists "resolved_by" uuid;
alter table public."moderation_reports" add column if not exists "content_id" uuid;
alter table public."moderation_reports" add column if not exists "content_type" text;
alter table public."moderation_reports" add column if not exists "moderator_notes" text;
alter table public."module_certificates" add column if not exists "issued_at" timestamp with time zone;
alter table public."mou_documents" add column if not exists "created_by" uuid;
alter table public."mou_documents" add column if not exists "party_email" text;
alter table public."mou_documents" add column if not exists "party_name" text;
alter table public."mou_documents" add column if not exists "party_type" text;
alter table public."mou_documents" add column if not exists "program" text;
alter table public."mou_documents" add column if not exists "status" text;
alter table public."notes" add column if not exists "content" text;
alter table public."notification_events" add column if not exists "timestamp" timestamp with time zone;
alter table public."notifications" add column if not exists "course_id" uuid;
alter table public."notifications" add column if not exists "data" jsonb;
alter table public."notifications" add column if not exists "notification_type" text;
alter table public."notifications" add column if not exists "priority" text;
alter table public."notifications" add column if not exists "recipient_type" text;
alter table public."notifications" add column if not exists "status" text;
alter table public."ojt_hours_log" add column if not exists "supervisor_signature" text;
alter table public."ojt_hours_log" add column if not exists "supervisor_verified" boolean;
alter table public."ojt_hours_log" add column if not exists "verified_at" timestamp with time zone;
alter table public."ojt_notes" add column if not exists "note" text;
alter table public."ojt_notes" add column if not exists "note_type" text;
alter table public."ojt_placements" add column if not exists "end_date" date;
alter table public."onboarding_progress" add column if not exists "completed" boolean;
alter table public."operator_tasks" add column if not exists "result" jsonb;
alter table public."organization_settings" add column if not exists "settings" jsonb;
alter table public."organization_subscriptions" add column if not exists "canceled_at" timestamp with time zone;
alter table public."organization_subscriptions" add column if not exists "plan" jsonb;
alter table public."organization_subscriptions" add column if not exists "seats" integer;
alter table public."organization_subscriptions" add column if not exists "trial_converted" boolean;
alter table public."organization_users" add column if not exists "org_id" uuid;
alter table public."orientation_completions" add column if not exists "orientation_type" text;
alter table public."orientation_completions" add column if not exists "visited_at" timestamp with time zone;
alter table public."partner_acknowledgments" add column if not exists "acknowledged_by" uuid;
alter table public."partner_acknowledgments" add column if not exists "application_id" uuid;
alter table public."partner_acknowledgments" add column if not exists "partner_id" uuid;
alter table public."partner_applications" add column if not exists "approved_at" timestamp with time zone;
alter table public."partner_applications" add column if not exists "approved_by" uuid;
alter table public."partner_applications" add column if not exists "denial_reason" text;
alter table public."partner_applications" add column if not exists "denied_at" timestamp with time zone;
alter table public."partner_applications" add column if not exists "denied_by" text;
alter table public."partner_applications" add column if not exists "notes" text;
alter table public."partner_certificates" add column if not exists "certificate_number" text;
alter table public."partner_certificates" add column if not exists "completed_at" timestamp with time zone;
alter table public."partner_certificates" add column if not exists "course_name" text;
alter table public."partner_certificates" add column if not exists "expires_at" timestamp with time zone;
alter table public."partner_certificates" add column if not exists "issued_at" timestamp with time zone;
alter table public."partner_certificates" add column if not exists "metadata" jsonb;
alter table public."partner_certificates" add column if not exists "program_id" uuid;
alter table public."partner_certificates" add column if not exists "provider_id" uuid;
alter table public."partner_certificates" add column if not exists "provider_name" text;
alter table public."partner_certificates" add column if not exists "revocation_reason" text;
alter table public."partner_certificates" add column if not exists "revoked" boolean;
alter table public."partner_certificates" add column if not exists "revoked_at" timestamp with time zone;
alter table public."partner_certificates" add column if not exists "student_name" text;
alter table public."partner_completions" add column if not exists "apprentice_id" uuid;
alter table public."partner_completions" add column if not exists "completed_at" timestamp with time zone;
alter table public."partner_completions" add column if not exists "milestone" text;
alter table public."partner_completions" add column if not exists "organization_id" uuid;
alter table public."partner_completions" add column if not exists "program_type" text;
alter table public."partner_completions" add column if not exists "recorded_by" uuid;
alter table public."partner_documents" add column if not exists "notes" text;
alter table public."partner_enrollments" add column if not exists "completion_data" jsonb;
alter table public."partner_enrollments" add column if not exists "completion_date" date;
alter table public."partner_enrollments" add column if not exists "partner" text;
alter table public."partner_enrollments" add column if not exists "program_slug" text;
alter table public."partner_enrollments" add column if not exists "user_id" uuid;
alter table public."partner_inquiries" add column if not exists "additional_info" text;
alter table public."partner_inquiries" add column if not exists "full_name" text;
alter table public."partner_inquiries" add column if not exists "ip_acknowledged" boolean;
alter table public."partner_inquiries" add column if not exists "relationship_type" text;
alter table public."partner_inquiries" add column if not exists "resources" jsonb;
alter table public."partner_inquiries" add column if not exists "reviewed_at" timestamp with time zone;
alter table public."partner_inquiries" add column if not exists "seeking" text;
alter table public."partner_inquiries" add column if not exists "submitted_at" timestamp with time zone;
alter table public."partner_inquiries" add column if not exists "written_agreement" text;
alter table public."partner_lms_enrollments" add column if not exists "certificate_id" uuid;
alter table public."partner_lms_enrollments" add column if not exists "payment_amount" numeric;
alter table public."partner_lms_enrollments" add column if not exists "payment_completed_at" timestamp with time zone;
alter table public."partner_lms_enrollments" add column if not exists "payment_session_id" uuid;
alter table public."partners" add column if not exists "auto_approved" boolean;
alter table public."partners" add column if not exists "enrollment_id" uuid;
alter table public."partners" add column if not exists "geocoded_at" timestamp with time zone;
alter table public."partners" add column if not exists "lat" numeric;
alter table public."partners" add column if not exists "lng" numeric;
alter table public."partners" add column if not exists "partner_application_id" uuid;
alter table public."payment_integrity_flags" add column if not exists "resolution_note" text;
alter table public."payment_integrity_flags" add column if not exists "resolution_type" text;
alter table public."payment_splits" add column if not exists "elevate_amount" numeric;
alter table public."payment_splits" add column if not exists "vendor_amount" numeric;
alter table public."payment_splits" add column if not exists "vendor_name" text;
alter table public."payment_splits" add column if not exists "vendor_paid_at" timestamp with time zone;
alter table public."payments" add column if not exists "course_id" uuid;
alter table public."payments" add column if not exists "stripe_customer_id" text;
alter table public."peer_reviews" add column if not exists "comment" text;
alter table public."performance_alerts" add column if not exists "message" text;
alter table public."performance_alerts" add column if not exists "type" text;
alter table public."performance_alerts" add column if not exists "url" text;
alter table public."performance_alerts" add column if not exists "user_agent" text;
alter table public."performance_alerts" add column if not exists "value" text;
alter table public."processed_stripe_events" add column if not exists "environment" text;
alter table public."product_page_views" add column if not exists "product_id" uuid;
alter table public."product_page_views" add column if not exists "user_id" uuid;
alter table public."product_page_views" add column if not exists "viewed_at" timestamp with time zone;
alter table public."profiles" add column if not exists "suspended" boolean;
alter table public."program_banner_views" add column if not exists "banner_type" text;
alter table public."program_banner_views" add column if not exists "user_id" uuid;
alter table public."program_banner_views" add column if not exists "viewed_at" timestamp with time zone;
alter table public."program_completion_certificates" add column if not exists "issued_by" text;
alter table public."program_discussions" add column if not exists "program_id" uuid;
alter table public."program_discussions" add column if not exists "title" text;
alter table public."program_enrollments" add column if not exists "access_status" text;
alter table public."program_enrollments" add column if not exists "approved_at" timestamp with time zone;
alter table public."program_enrollments" add column if not exists "approved_by" uuid;
alter table public."program_enrollments" add column if not exists "at_risk_flagged_at" timestamp with time zone;
alter table public."program_enrollments" add column if not exists "at_risk_reason" text;
alter table public."program_enrollments" add column if not exists "cancelled_at" timestamp with time zone;
alter table public."program_enrollments" add column if not exists "enrollment_method" text;
alter table public."program_enrollments" add column if not exists "funding_verified_at" timestamp with time zone;
alter table public."program_enrollments" add column if not exists "funding_verified_by" uuid;
alter table public."program_enrollments" add column if not exists "last_accessed" timestamp with time zone;
alter table public."program_enrollments" add column if not exists "last_progress_update" date;
alter table public."program_enrollments" add column if not exists "pause_reason" text;
alter table public."program_enrollments" add column if not exists "paused_at" timestamp with time zone;
alter table public."program_enrollments" add column if not exists "payment_amount_cents" integer;
alter table public."program_enrollments" add column if not exists "payment_method" text;
alter table public."program_enrollments" add column if not exists "payment_provider" text;
alter table public."program_enrollments" add column if not exists "payment_reference" text;
alter table public."program_enrollments" add column if not exists "practical_hours_completed" boolean;
alter table public."program_enrollments" add column if not exists "progress_percentage" numeric;
alter table public."program_enrollments" add column if not exists "rapids_registered" boolean;
alter table public."program_enrollments" add column if not exists "refunded_at" timestamp with time zone;
alter table public."program_enrollments" add column if not exists "revocation_reason" text;
alter table public."program_enrollments" add column if not exists "suspended_at" timestamp with time zone;
alter table public."program_enrollments" add column if not exists "suspension_reason" text;
alter table public."program_enrollments" add column if not exists "theory_hours_completed" boolean;
alter table public."program_enrollments" add column if not exists "total_hours_completed" numeric;
alter table public."program_holders" add column if not exists "enrollments_restricted" boolean;
alter table public."program_holders" add column if not exists "mou_admin_name" text;
alter table public."program_holders" add column if not exists "mou_admin_sig_url" text;
alter table public."program_holders" add column if not exists "mou_admin_signed_at" timestamp with time zone;
alter table public."program_holders" add column if not exists "mou_terminated" boolean;
alter table public."program_holders" add column if not exists "probation_reason" text;
alter table public."program_holders" add column if not exists "probation_started_at" timestamp with time zone;
alter table public."program_holders" add column if not exists "restricted_at" timestamp with time zone;
alter table public."program_holders" add column if not exists "restriction_reason" text;
alter table public."program_holders" add column if not exists "suspended_at" timestamp with time zone;
alter table public."program_holders" add column if not exists "suspension_reason" text;
alter table public."program_holders" add column if not exists "terminated_at" timestamp with time zone;
alter table public."program_holders" add column if not exists "termination_reason" text;
alter table public."program_holders" add column if not exists "updated_at" timestamp with time zone;
alter table public."program_holders" add column if not exists "verification_status" text;
alter table public."program_modules" add column if not exists "updated_at" timestamp with time zone;
alter table public."programs" add column if not exists "archived_at" timestamp with time zone;
alter table public."programs" add column if not exists "duration_hours" numeric;
alter table public."programs" add column if not exists "org_id" uuid;
alter table public."provider_program_approvals" add column if not exists "program_snapshot" jsonb;
alter table public."provider_program_approvals" add column if not exists "submitted_by" uuid;
alter table public."provisioning_jobs" add column if not exists "correlation_id" text;
alter table public."provisioning_jobs" add column if not exists "job_type" text;
alter table public."provisioning_jobs" add column if not exists "payload" jsonb;
alter table public."provisioning_jobs" add column if not exists "payment_intent_id" text;
alter table public."provisioning_jobs" add column if not exists "run_at" timestamp with time zone;
alter table public."provisioning_jobs" add column if not exists "stripe_event_id" text;
alter table public."provisioning_jobs" add column if not exists "tenant_id" uuid;
alter table public."purchases" add column if not exists "amount_cents" integer;
alter table public."purchases" add column if not exists "currency" text;
alter table public."purchases" add column if not exists "purchased_at" timestamp with time zone;
alter table public."purchases" add column if not exists "refunded_at" timestamp with time zone;
alter table public."purchases" add column if not exists "status" text;
alter table public."purchases" add column if not exists "stripe_session_id" text;
alter table public."push_notification_send_log" add column if not exists "body" text;
alter table public."push_notification_send_log" add column if not exists "sender_id" uuid;
alter table public."push_notification_send_log" add column if not exists "sent_at" timestamp with time zone;
alter table public."push_notification_send_log" add column if not exists "status" text;
alter table public."push_notification_send_log" add column if not exists "title" text;
alter table public."push_notification_send_log" add column if not exists "url" text;
alter table public."push_subscriptions" add column if not exists "active" boolean;
alter table public."qa_checklist_completions" add column if not exists "user_id" uuid;
alter table public."question_banks" add column if not exists "course_id" uuid;
alter table public."question_banks" add column if not exists "created_by" uuid;
alter table public."questions" add column if not exists "bank_id" uuid;
alter table public."questions" add column if not exists "created_by" uuid;
alter table public."quiz_answers" add column if not exists "answered_at" timestamp with time zone;
alter table public."quiz_answers" add column if not exists "attempt_id" integer;
alter table public."quiz_questions" add column if not exists "correct_answer" jsonb;
alter table public."quiz_questions" add column if not exists "options" jsonb;
alter table public."quiz_questions" add column if not exists "order_index" integer;
alter table public."quizzes" add column if not exists "question_count" integer;
alter table public."quizzes" add column if not exists "status" text;
alter table public."rapids_registrations" add column if not exists "application_id" uuid;
alter table public."rapids_registrations" add column if not exists "occupation_title" text;
alter table public."rapids_registrations" add column if not exists "program_number" text;
alter table public."rapids_registrations" add column if not exists "sponsor_name" text;
alter table public."rapids_tracking" add column if not exists "notes" text;
alter table public."rapids_tracking" add column if not exists "occupation_code" text;
alter table public."rapids_tracking" add column if not exists "program_id" uuid;
alter table public."rapids_tracking" add column if not exists "student_id" uuid;
alter table public."recap_generation_log" add column if not exists "generated_at" timestamp with time zone;
alter table public."recap_generation_log" add column if not exists "meeting_date" timestamp with time zone;
alter table public."recap_generation_log" add column if not exists "recap_id" uuid;
alter table public."recap_generation_log" add column if not exists "transcript_length" integer;
alter table public."referral_codes" add column if not exists "commission_percentage" numeric;
alter table public."referral_codes" add column if not exists "discount_percentage" numeric;
alter table public."referral_codes" add column if not exists "enabled" boolean;
alter table public."referrals" add column if not exists "completed_at" timestamp with time zone;
alter table public."referrals" add column if not exists "referred_id" uuid;
alter table public."referrals" add column if not exists "reward_paid" boolean;
alter table public."resumes" add column if not exists "resume_data" jsonb;
alter table public."resumes" add column if not exists "user_id" uuid;
alter table public."review_queue" add column if not exists "assignedat" text;
alter table public."review_queue" add column if not exists "assignedto" text;
alter table public."review_queue" add column if not exists "confidence_score" numeric;
alter table public."review_queue" add column if not exists "context" jsonb;
alter table public."review_queue" add column if not exists "decidedat" text;
alter table public."review_queue" add column if not exists "decisionnote" text;
alter table public."review_queue" add column if not exists "extracted_data" jsonb;
alter table public."review_queue" add column if not exists "failed_rules" text;
alter table public."review_queue" add column if not exists "system_recommendation" text;
alter table public."sam_alerts" add column if not exists "is_read" boolean;
alter table public."sam_documents" add column if not exists "document_type" text;
alter table public."sam_documents" add column if not exists "entity_id" uuid;
alter table public."sam_documents" add column if not exists "file_name" text;
alter table public."sam_documents" add column if not exists "file_size" bigint;
alter table public."sam_documents" add column if not exists "file_url" text;
alter table public."sam_entities" add column if not exists "current_step" integer;
alter table public."sam_entities" add column if not exists "registration_status" text;
alter table public."sam_entities" add column if not exists "user_id" uuid;
alter table public."scheduled_posts" add column if not exists "hashtags" text[];
alter table public."scheduled_posts" add column if not exists "text" text;
alter table public."scorm_attempts" add column if not exists "attempt_id" integer;
alter table public."scorm_attempts" add column if not exists "package_id" text;
alter table public."scorm_attempts" add column if not exists "scorm_version" text;
alter table public."scorm_attempts" add column if not exists "started_at" timestamp with time zone;
alter table public."scorm_attempts" add column if not exists "user_id" uuid;
alter table public."scorm_packages" add column if not exists "status" text;
alter table public."scraper_detection_events" add column if not exists "detected_at" timestamp without time zone;
alter table public."scraper_detection_events" add column if not exists "event_type" text;
alter table public."scraper_detection_events" add column if not exists "url" text;
alter table public."scraper_detection_events" add column if not exists "user_agent" text;
alter table public."script_acknowledgments" add column if not exists "acknowledged_at" timestamp with time zone;
alter table public."script_acknowledgments" add column if not exists "intake_id" uuid;
alter table public."script_acknowledgments" add column if not exists "script_id" uuid;
alter table public."script_acknowledgments" add column if not exists "user_id" uuid;
alter table public."script_deviations" add column if not exists "intake_id" uuid;
alter table public."script_deviations" add column if not exists "script_id" uuid;
alter table public."script_deviations" add column if not exists "user_id" uuid;
alter table public."search_history" add column if not exists "search_type" text;
alter table public."search_logs" add column if not exists "query" text;
alter table public."search_logs" add column if not exists "results_count" integer;
alter table public."sezzle_card_events" add column if not exists "card_last_four" text;
alter table public."sezzle_card_events" add column if not exists "order_id" text;
alter table public."sezzle_card_events" add column if not exists "timestamp" timestamp with time zone;
alter table public."sezzle_card_events" add column if not exists "user_id" uuid;
alter table public."signatures" add column if not exists "user_agent" text;
alter table public."slow_resources" add column if not exists "duration" integer;
alter table public."slow_resources" add column if not exists "name" text;
alter table public."slow_resources" add column if not exists "size" text;
alter table public."slow_resources" add column if not exists "type" text;
alter table public."slow_resources" add column if not exists "url" text;
alter table public."slow_resources" add column if not exists "user_agent" text;
alter table public."sms_messages" add column if not exists "message_text" text;
alter table public."sms_messages" add column if not exists "phone_number" text;
alter table public."sms_messages" add column if not exists "sent_by" uuid;
alter table public."social_media_posts" add column if not exists "error_message" text;
alter table public."social_media_posts" add column if not exists "platform_post_id" uuid;
alter table public."social_media_posts" add column if not exists "posted_at" timestamp with time zone;
alter table public."staff_training_progress" add column if not exists "certification_date" date;
alter table public."staff_training_progress" add column if not exists "quiz_score" integer;
alter table public."state_rules" add column if not exists "state" text;
alter table public."store_entitlements" add column if not exists "revoke_reason" text;
alter table public."store_entitlements" add column if not exists "revoked_at" timestamp with time zone;
alter table public."student_ai_instructors" add column if not exists "instructor_id" uuid;
alter table public."student_ai_instructors" add column if not exists "is_active" boolean;
alter table public."student_ai_instructors" add column if not exists "program_id" uuid;
alter table public."student_ai_instructors" add column if not exists "student_id" uuid;
alter table public."student_payments" add column if not exists "stripe_invoice_id" text;
alter table public."student_payments" add column if not exists "stripe_subscription_id" text;
alter table public."student_payments" add column if not exists "student_id" uuid;
alter table public."student_payments" add column if not exists "type" text;
alter table public."student_requirements" add column if not exists "due_date" timestamp with time zone;
alter table public."student_requirements" add column if not exists "enrollment_id" uuid;
alter table public."student_requirements" add column if not exists "requirement_type" text;
alter table public."student_subscriptions" add column if not exists "current_period_end" timestamp with time zone;
alter table public."student_subscriptions" add column if not exists "current_period_start" timestamp with time zone;
alter table public."student_subscriptions" add column if not exists "last_payment_at" timestamp with time zone;
alter table public."students" add column if not exists "phone" text;
alter table public."students" add column if not exists "status" text;
alter table public."study_group_members" add column if not exists "group_id" uuid;
alter table public."study_group_members" add column if not exists "role" text;
alter table public."study_groups" add column if not exists "course_id" uuid;
alter table public."study_groups" add column if not exists "creator_id" uuid;
alter table public."study_groups" add column if not exists "is_public" boolean;
alter table public."study_groups" add column if not exists "program_id" uuid;
alter table public."subscriptions" add column if not exists "stripe_customer_id" text;
alter table public."subscriptions" add column if not exists "stripe_subscription_id" text;
alter table public."survey_responses" add column if not exists "survey_id" uuid;
alter table public."survey_responses" add column if not exists "user_id" uuid;
alter table public."surveys" add column if not exists "created_by" uuid;
alter table public."surveys" add column if not exists "end_date" date;
alter table public."surveys" add column if not exists "response_count" integer;
alter table public."surveys" add column if not exists "start_date" date;
alter table public."surveys" add column if not exists "target_audience" text;
alter table public."tasks" add column if not exists "assigned_to" uuid;
alter table public."tasks" add column if not exists "description" text;
alter table public."tasks" add column if not exists "priority" text;
alter table public."tasks" add column if not exists "related_id" uuid;
alter table public."tasks" add column if not exists "related_type" text;
alter table public."tasks" add column if not exists "status" text;
alter table public."tenant_licenses" add column if not exists "active" boolean;
alter table public."tenant_licenses" add column if not exists "expires_at" timestamp with time zone;
alter table public."tenant_licenses" add column if not exists "max_apprentices" integer;
alter table public."tenant_licenses" add column if not exists "max_employers" integer;
alter table public."tenants" add column if not exists "settings" jsonb;
alter table public."tenants" add column if not exists "stripe_customer_id" text;
alter table public."tenants" add column if not exists "stripe_subscription_id" text;
alter table public."transcript_search_log" add column if not exists "query" text;
alter table public."transcript_search_log" add column if not exists "searched_at" timestamp with time zone;
alter table public."transcript_search_log" add column if not exists "video_id" text;
alter table public."transfer_hours" add column if not exists "approved_hours" numeric;
alter table public."transfer_hours" add column if not exists "effective_date" date;
alter table public."transfer_hours" add column if not exists "enrollment_id" uuid;
alter table public."transfer_hours" add column if not exists "hours_approved" numeric;
alter table public."transfer_hours" add column if not exists "hours_other_accepted" text;
alter table public."transfer_hours" add column if not exists "hours_other_submitted" text;
alter table public."transfer_hours" add column if not exists "hours_practical_accepted" text;
alter table public."transfer_hours" add column if not exists "hours_practical_submitted" text;
alter table public."transfer_hours" add column if not exists "hours_theory_accepted" text;
alter table public."transfer_hours" add column if not exists "hours_theory_submitted" text;
alter table public."transfer_hours" add column if not exists "license_type" text;
alter table public."transfer_hours" add column if not exists "notes" text;
alter table public."transfer_hours" add column if not exists "proof_doc_path" text;
alter table public."transfer_hours" add column if not exists "reviewed_at" timestamp with time zone;
alter table public."transfer_hours" add column if not exists "reviewed_by" uuid;
alter table public."transfer_hours" add column if not exists "source_school_name" text;
alter table public."transfer_hours" add column if not exists "source_state" text;
alter table public."trial_signups" add column if not exists "stripe_customer_id" text;
alter table public."trial_signups" add column if not exists "stripe_subscription_id" text;
alter table public."tts_usage_log" add column if not exists "content_id" uuid;
alter table public."tts_usage_log" add column if not exists "text_length" integer;
alter table public."tts_usage_log" add column if not exists "used_at" timestamp with time zone;
alter table public."tuition_payments" add column if not exists "amount_paid" numeric;
alter table public."tuition_payments" add column if not exists "payment_option" text;
alter table public."tuition_payments" add column if not exists "program_id" uuid;
alter table public."tuition_payments" add column if not exists "stripe_invoice_id" text;
alter table public."tuition_payments" add column if not exists "stripe_session_id" text;
alter table public."tuition_payments" add column if not exists "stripe_subscription_id" text;
alter table public."tuition_payments" add column if not exists "student_id" uuid;
alter table public."tuition_subscriptions" add column if not exists "last_failed_date" date;
alter table public."tuition_subscriptions" add column if not exists "last_payment_date" timestamp with time zone;
alter table public."tuition_subscriptions" add column if not exists "monthly_amount" numeric;
alter table public."tuition_subscriptions" add column if not exists "program_id" uuid;
alter table public."tuition_subscriptions" add column if not exists "stripe_subscription_id" text;
alter table public."tuition_subscriptions" add column if not exists "student_id" uuid;
alter table public."turnstile_verifications" add column if not exists "event_type" text;
alter table public."turnstile_verifications" add column if not exists "form_id" uuid;
alter table public."turnstile_verifications" add column if not exists "timestamp" timestamp with time zone;
alter table public."turnstile_verifications" add column if not exists "token_prefix" text;
alter table public."turnstile_verifications" add column if not exists "user_id" uuid;
alter table public."user_activity_events" add column if not exists "event_payload" jsonb;
alter table public."user_activity_events" add column if not exists "tenant_id" uuid;
alter table public."user_entitlements" add column if not exists "revoke_reason" text;
alter table public."user_entitlements" add column if not exists "revoked_at" timestamp with time zone;
alter table public."user_feedback" add column if not exists "browser_info" text;
alter table public."user_feedback" add column if not exists "feedback_type" text;
alter table public."user_feedback" add column if not exists "page_url" text;
alter table public."user_feedback" add column if not exists "status" text;
alter table public."user_learning_paths" add column if not exists "current_step" integer;
alter table public."user_learning_paths" add column if not exists "learning_path_id" uuid;
alter table public."user_learning_paths" add column if not exists "progress_percentage" numeric;
alter table public."user_learning_paths" add column if not exists "started_at" timestamp with time zone;
alter table public."user_onboarding" add column if not exists "steps_viewed" integer;
alter table public."user_onboarding" add column if not exists "total_steps" integer;
alter table public."user_onboarding" add column if not exists "tour_key" text;
alter table public."verification_actions" add column if not exists "action_type" text;
alter table public."verification_actions" add column if not exists "notes" text;
alter table public."verification_actions" add column if not exists "performed_by" uuid;
alter table public."verification_actions" add column if not exists "requirement_id" uuid;
alter table public."video_generation_jobs" add column if not exists "course_id" uuid;
alter table public."video_generation_jobs" add column if not exists "error" text;
alter table public."video_generation_jobs" add column if not exists "results" jsonb;
alter table public."video_generation_jobs" add column if not exists "started_at" timestamp with time zone;
alter table public."video_views" add column if not exists "completed" boolean;
alter table public."video_views" add column if not exists "user_id" uuid;
alter table public."video_views" add column if not exists "video_type" text;
alter table public."video_views" add column if not exists "video_url" text;
alter table public."video_views" add column if not exists "viewed_at" timestamp with time zone;
alter table public."webhook_health_log" add column if not exists "checked_at" timestamp with time zone;
alter table public."webhook_health_log" add column if not exists "notes" text;
alter table public."webhook_health_log" add column if not exists "open_flags" text;
alter table public."welcome_packet_items" add column if not exists "completed" boolean;
alter table public."welcome_packet_items" add column if not exists "completed_at" timestamp with time zone;
alter table public."welcome_packets" add column if not exists "completed_at" timestamp with time zone;
alter table public."welcome_packets" add column if not exists "enrollment_id" uuid;
alter table public."welcome_packets" add column if not exists "program_id" uuid;
alter table public."welcome_packets" add column if not exists "student_id" uuid;
alter table public."wioa_compliance_reports" add column if not exists "due_date" timestamp with time zone;
alter table public."wioa_participants" add column if not exists "authorization_date" date;
alter table public."wioa_participants" add column if not exists "case_manager" text;
alter table public."wioa_participants" add column if not exists "created_by" uuid;
alter table public."wioa_participants" add column if not exists "eligibility_verified_at" timestamp with time zone;
alter table public."wioa_participants" add column if not exists "eligibility_verified_by" uuid;
alter table public."wioa_participants" add column if not exists "expiration_date" date;
alter table public."wioa_participants" add column if not exists "funding_amount" numeric;
alter table public."wioa_participants" add column if not exists "notes" text;
alter table public."wioa_participants" add column if not exists "participant_email" text;
alter table public."wioa_participants" add column if not exists "participant_name" text;
alter table public."wioa_participants" add column if not exists "participant_phone" text;
alter table public."wioa_participants" add column if not exists "program" text;
alter table public."wioa_participants" add column if not exists "workone_center" text;
alter table public."workflows" add column if not exists "description" text;
alter table public."wotc_applications" add column if not exists "submitted_by" uuid;

notify pgrst, 'reload schema';
