-- Operational data for published Website Builder tenant sites.
CREATE TABLE IF NOT EXISTS public.tenant_site_leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id uuid NOT NULL REFERENCES public.user_websites(id) ON DELETE CASCADE,
  user_id uuid,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  message text NOT NULL,
  source_path text,
  source_host text,
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tenant_site_leads_website_created_idx
  ON public.tenant_site_leads (website_id, created_at DESC);
CREATE INDEX IF NOT EXISTS tenant_site_leads_owner_created_idx
  ON public.tenant_site_leads (user_id, created_at DESC);

ALTER TABLE public.tenant_site_leads ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_site_leads_owner_select ON public.tenant_site_leads;
CREATE POLICY tenant_site_leads_owner_select
  ON public.tenant_site_leads FOR SELECT
  USING (auth.uid() = user_id);
DROP POLICY IF EXISTS tenant_site_leads_owner_update ON public.tenant_site_leads;
CREATE POLICY tenant_site_leads_owner_update
  ON public.tenant_site_leads FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS tenant_site_leads_owner_delete ON public.tenant_site_leads;
CREATE POLICY tenant_site_leads_owner_delete
  ON public.tenant_site_leads FOR DELETE
  USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.tenant_site_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id uuid NOT NULL REFERENCES public.user_websites(id) ON DELETE CASCADE,
  event_name text NOT NULL,
  path text,
  source_host text,
  referrer text,
  session_key text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tenant_site_events_website_created_idx
  ON public.tenant_site_events (website_id, created_at DESC);
CREATE INDEX IF NOT EXISTS tenant_site_events_name_created_idx
  ON public.tenant_site_events (event_name, created_at DESC);

ALTER TABLE public.tenant_site_events ENABLE ROW LEVEL SECURITY;
-- Public writes are performed only through server-side service-role API routes.
-- Owners read analytics through authenticated server endpoints.
